package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// normalizeReports processes the XML test results and outputs a NDJSON stream with one document per test execution.
// Hence, each document corresponds to a testcase entry in the XML. It contains the following fields:
//
//   - 'timestamp': As the testsuite (parent of the entry) timestamp field.
//   - 'suite_name': As the entry class name.
//   - 'test': As the entry name.
//   - 'result': success/failure/skipped from the optional child node of the entry. No child node means success.
//   - 'reason': As the entry child (skipped or failure) contents. For example, in the source, <failure>SOURCE FOR REASON</failure>.
//   - 'duration_seconds': As the time field of the entry.
//   - 'workflow_run_id': As the content of the environment variable 'WORKFLOW_RUN_ID'
//   - 'workflow_run_link': As the content of the environment variable 'WORKFLOW_RUN_LINK'
//   - 'workflow_head_branch': As the content of the environment variable 'WORKFLOW_HEAD_BRANCH'
//   - 'workflow_retry_number': As the content of the environment variable 'WORKFLOW_RUN_NUMBER'
//   - 'commit_sha': As the content of the environment variable 'COMMIT_SHA'
//
// INPUT:
//   - The expected XML report filenames in logDir. For example, the test results generated by JUnit in the 'target/surefire-reports' directory.
//   - The following environment variables to enrich with the workflow information:
//   - WORKFLOW_RUN_ID
//   - WORKFLOW_RUN_LINK
//   - WORKFLOW_HEAD_BRANCH
//   - WORKFLOW_RUN_NUMBER
//   - COMMIT_SHA
//
// OUTPUT: One NDJSON file at logDir/normalized-test-results.ndjson.
func normalizeReports(logDir string, reports []string) error {
	var output bytes.Buffer
	for _, report := range reports {
		//nolint:gosec // Report paths are separate arguments; no shell is involved.
		parse := exec.Command("yq", "-p=xml", "--xml-strict-mode", "-o=json", ".", filepath.Join(logDir, report))
		parse.Stderr = os.Stderr
		data, err := parse.Output()
		if err != nil {
			return fmt.Errorf("parse test report %s: %w", report, err)
		}
		// yq can return null or top-level text for malformed XML without failing.
		var document map[string]json.RawMessage
		if err := json.Unmarshal(data, &document); err != nil {
			return fmt.Errorf("decode test report %s: %w", report, err)
		}
		_, hasRoot := document["testsuites"]
		_, hasText := document["+content"]
		if !hasRoot || hasText {
			return fmt.Errorf("test report %s must have a testsuites root with no surrounding text", report)
		}
		normalize := exec.Command("jq", "-c", `
			def elements: if type == "array" then .[] else . end;
			(.testsuites.testsuite // []) | elements |
			."+@timestamp" as $ts |
			(.testcase // []) | elements |
			select(."+@classname" != null) |
			{
			  "timestamp": $ts,
			  "suite_name": ."+@classname",
			  "test": ."+@name",
			  "result": (if has("failure") then "failure" elif has("skipped") then "skipped" else "success" end),
			  "reason": (.failure."+content" // .skipped."+@message" // null),
			  "duration_seconds": ((."+@time" | select(. != null and . != "") | tonumber) // null),
			  "workflow_run_id": (($ENV.WORKFLOW_RUN_ID | select(. != null and . != "") | tonumber) // 0),
			  "workflow_run_link": ($ENV.WORKFLOW_RUN_LINK // ""),
			  "workflow_head_branch": ($ENV.WORKFLOW_HEAD_BRANCH // ""),
			  "workflow_retry_number": (($ENV.WORKFLOW_RUN_NUMBER | select(. != null and . != "") | tonumber) // 0),
			  "commit_sha": ($ENV.COMMIT_SHA // ""),
			  "compatibility_matrix_id": (($ENV.COMBINATION_ID | select(. != "")) // null)
			}
		`)
		normalize.Stdin = bytes.NewReader(data)
		normalize.Stdout = &output
		normalize.Stderr = os.Stderr
		if err := normalize.Run(); err != nil {
			return fmt.Errorf("normalize test report %s: %w", report, err)
		}
	}
	return os.WriteFile(filepath.Join(logDir, "normalized-test-results.ndjson"), output.Bytes(), 0o600)
}
