package connelasticsearch

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"slices"
	"sync"
	"time"

	"github.com/PeerDB-io/peerdb/flow/generated/protos"
	"github.com/PeerDB-io/peerdb/flow/model"
	"github.com/PeerDB-io/peerdb/flow/shared"
	"github.com/PeerDB-io/peerdb/flow/shared/types"
)

func (esc *ElasticsearchConnector) SetupQRepMetadataTables(ctx context.Context,
	config *protos.QRepConfig,
) error {
	return nil
}

func upsertKeyColsHash(qRecord []types.QValue, upsertColIndices []int) string {
	hasher := sha256.New()

	for _, upsertColIndex := range upsertColIndices {
		_, _ = fmt.Fprint(hasher, qRecord[upsertColIndex].Value())
	}
	hashBytes := hasher.Sum(nil)
	return base64.RawURLEncoding.EncodeToString(hashBytes)
}

func (esc *ElasticsearchConnector) SyncQRepRecords(ctx context.Context, config *protos.QRepConfig,
	partition *protos.QRepPartition, stream *model.QRecordStream,
) (int64, shared.QRepWarnings, error) {
	startTime := time.Now()

	schema, err := stream.Schema()
	if err != nil {
		return 0, nil, err
	}

	var bulkIndexFatalError error
	var bulkIndexErrors []error
	var bulkIndexOnFailureMutex sync.Mutex
	var numRecords int64
	bulkIndexerHasShutdown := false

	var upsertKeyColIndices []int
	if config.WriteMode.WriteType == protos.QRepWriteType_QREP_WRITE_MODE_UPSERT {
		schemaColNames := schema.GetColumnNames()
		for _, upsertCol := range config.WriteMode.UpsertKeyColumns {
			idx := slices.Index(schemaColNames, upsertCol)
			if idx != -1 {
				upsertKeyColIndices = append(upsertKeyColIndices, idx)
			} else {
				hushKey := tableUpsertCol{table: config.DestinationTableIdentifier, col: upsertCol}
				if _, warned := esc.hushWarnUpsertColMissing[hushKey]; !warned {
					esc.logger.Warn(esc.logPrefix()+" upsert key column not found in schema, may cause duplicates",
						slog.String("destinationTable", config.DestinationTableIdentifier),
						slog.String("upsertKeyColumn", upsertCol),
						slog.Any("schemaColumns", schemaColNames))
					esc.hushWarnUpsertColMissing[hushKey] = struct{}{}
				}
			}
		}
	}

	bulkIndexer, err := esc.client.NewBulkIndexer(config.DestinationTableIdentifier)
	if err != nil {
		esc.logger.Error(esc.logPrefix()+" failed to initialize bulk indexer", slog.Any("error", err))
		return 0, nil, fmt.Errorf("%s failed to initialize bulk indexer: %w", esc.logPrefix(), err)
	}
	defer func() {
		if !bulkIndexerHasShutdown {
			if err := bulkIndexer.Close(context.Background()); err != nil {
				esc.logger.Error(esc.logPrefix()+" failed to close bulk indexer", slog.Any("error", err))
			}
		}
	}()

	for qRecord := range stream.Records {
		qRecordJSONMap := make(map[string]any)
		docID := ""

		switch len(upsertKeyColIndices) {
		case 0:
			// rely on autogenerated document IDs
		case 1:
			docID = fmt.Sprint(qRecord[upsertKeyColIndices[0]].Value())
		default:
			docID = upsertKeyColsHash(qRecord, upsertKeyColIndices)
		}
		for i, field := range schema.Fields {
			if r, ok := qRecord[i].(types.QValueJSON); ok {
				qRecordJSONMap[field.Name] = json.RawMessage(
					shared.UnsafeFastStringToReadOnlyBytes(r.Val))
			} else {
				qRecordJSONMap[field.Name] = qRecord[i].Value()
			}
		}
		qRecordJSONBytes, err := json.Marshal(qRecordJSONMap)
		if err != nil {
			esc.logger.Error(esc.logPrefix()+" failed to json.Marshal record", slog.Any("error", err))
			return 0, nil, fmt.Errorf("%s failed to json.Marshal record: %w", esc.logPrefix(), err)
		}

		if err := bulkIndexer.Add(ctx, searchBulkIndexerItem{
			Action:     actionIndex,
			DocumentID: docID,
			Body:       bytes.NewReader(qRecordJSONBytes),
			OnFailure: func(failure searchBulkIndexerFailure) {
				bulkIndexOnFailureMutex.Lock()
				defer bulkIndexOnFailureMutex.Unlock()
				cbErr := searchFailureToError(docID, failure)
				bulkIndexErrors = append(bulkIndexErrors, cbErr)
				if failure.ErrorType == "illegal_argument_exception" {
					bulkIndexFatalError = cbErr
				}
			},
		}); err != nil {
			esc.logger.Error(esc.logPrefix()+" failed to add record to bulk indexer", slog.Any("error", err))
			return 0, nil, fmt.Errorf("%s failed to add record to bulk indexer: %w", esc.logPrefix(), err)
		}
		if bulkIndexFatalError != nil {
			esc.logger.Error(esc.logPrefix()+" fatal error while indexing record", slog.Any("error", bulkIndexFatalError))
			return 0, nil, fmt.Errorf("%s fatal error while indexing record: %w", esc.logPrefix(), bulkIndexFatalError)
		}

		numRecords++
	}

	if err := stream.Err(); err != nil {
		esc.logger.Error(esc.logPrefix()+" failed to get record from stream", slog.Any("error", err))
		return 0, nil, fmt.Errorf("%s failed to get record from stream: %w", esc.logPrefix(), err)
	}
	if err := bulkIndexer.Close(ctx); err != nil {
		esc.logger.Error(esc.logPrefix()+" failed to close bulk indexer", slog.Any("error", err))
		return 0, nil, fmt.Errorf("%s failed to close bulk indexer: %w", esc.logPrefix(), err)
	}
	bulkIndexerHasShutdown = true
	if len(bulkIndexErrors) > 0 {
		for _, err := range bulkIndexErrors {
			esc.logger.Error(esc.logPrefix()+" failed to index record", slog.Any("err", err))
		}
	}

	if err := esc.FinishQRepPartition(ctx, partition, config.FlowJobName, startTime); err != nil {
		esc.logger.Error(esc.logPrefix()+" failed to log partition info", slog.Any("error", err))
		return 0, nil, fmt.Errorf("%s failed to log partition info: %w", esc.logPrefix(), err)
	}
	return numRecords, nil, nil
}
