peerdb_demo_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: sai-test.postgres.database.azure.com
      port: 5432
      user: sai
      pass: test123!
      dbname: postgres
      schema: public