name: peerdb-ancillary-services

services:
  mongodb:
    container_name: peerdb-mongodb
    image: ${MONGODB_IMAGE}
    entrypoint: ["bash", "-c", "openssl rand -base64 756 > /data/mongo.key && chmod 400 /data/mongo.key && exec mongod --replSet rs0 --oplogMinRetentionHours 24 --bind_ip_all --keyFile /data/mongo.key"]
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CI_MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CI_MONGO_ADMIN_PASSWORD}

    volumes:
      - mongo_data:/data/db
    ports:
      - "${CI_MONGO_PORT}:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 2s
      timeout: 10s
      retries: 5

  clickhouse:
    container_name: peerdb-clickhouse
    image: ${CLICKHOUSE_IMAGE}
    restart: unless-stopped
    ports:
      - "${CI_CLICKHOUSE_HTTP_PORT}:8123"
      - "${CI_CLICKHOUSE_NATIVE_PORT}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 2s
      timeout: 10s
      retries: 5

  mysql-gtid:
    container_name: peerdb-mysql-gtid
    image: mysql:9.5
    command:
      - "--binlog-row-metadata=FULL"
    restart: unless-stopped
    volumes:
      - mysql_gtid_data:/var/lib/mysql
    ports:
      - "${CI_MYSQL_GTID_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${CI_MYSQL_ROOT_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 10s
      retries: 5

  mysql-pos:
    container_name: peerdb-mysql-pos
    image: biarms/mysql:5.7
    command: ["--log_bin=mysql-bin", "--server-id=1", "--bind-address=::"]
    restart: unless-stopped
    volumes:
      - mysql_pos_data:/var/lib/mysql
    ports:
      - "${CI_MYSQL_POS_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${CI_MYSQL_ROOT_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${CI_MYSQL_ROOT_PASSWORD}"]
      interval: 2s
      timeout: 10s
      retries: 5

  mariadb:
    container_name: peerdb-mariadb
    image: mariadb:lts-ubi9@sha256:55a81b2d791d2ff8ad33fef413d9e45e0ac57a951127e0cfc69a8e59f922ba6e
    command:
      - "--log-bin=maria"
      - "--binlog-format=ROW"
      - "--binlog-row-metadata=FULL"
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${CI_MARIADB_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${CI_MYSQL_ROOT_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-p${CI_MYSQL_ROOT_PASSWORD}"]
      interval: 2s
      timeout: 10s
      retries: 5

  postgres:
    container_name: peerdb-postgres
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    environment:
      PGUSER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_INITDB_ARGS: --locale=C.UTF-8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 10s
      retries: 5

  postgres2:
    container_name: peerdb-postgres2
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    volumes:
      - postgres2_data:/var/lib/postgresql/data
    ports:
      - "${PG2_PORT}:5432"
    environment:
      PGUSER: ${PG2_USER}
      POSTGRES_PASSWORD: ${PG2_PASSWORD}
      POSTGRES_DB: ${PG2_DATABASE}
      POSTGRES_INITDB_ARGS: --locale=C.UTF-8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 10s
      retries: 5

  dozzle:
    container_name: dozzle-compose-monitor
    image: amir20/dozzle:latest
    restart: unless-stopped
    ports:
      - "8118:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  toxiproxy:
    container_name: peerdb-test-toxiproxy
    # Same image as CI flow
    image: ghcr.io/shopify/toxiproxy:2.12.0@sha256:9378ed52a28bc50edc1350f936f518f31fa95f0d15917d6eb40b8e376d1a214e
    restart: unless-stopped
    ports:
      - 18474:8474
      - 9902:9902
      - 9904:9904
      - 9903:9903
      - 42001:42001
      - 42002:42002
      - 42003:42003
      - 42004:42004
      - 42005:42005
      - 49001:49001
      - 49002:49002
      - 49003:49003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "/toxiproxy-cli", "list"]
      interval: 2s
      timeout: 10s
      retries: 5

  openssh:
    container_name: peerdb-test-ssh
    # Same image as CI flow
    image: linuxserver/openssh-server:latest@sha256:57c13941ef385d735cca18ee969eeba18e42ab95480c97af2182505aacdfe307
    restart: unless-stopped
    ports:
      - "2222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER_NAME=testuser
      - USER_PASSWORD=testpass
      - PASSWORD_ACCESS=true
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2222"]
      interval: 2s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  postgres2_data:
  clickhouse_data:
  mongo_data:
  mysql_gtid_data:
  mysql_pos_data:
  mariadb_data:

networks:
  default:
    name: peerdb_network
    external: true
