ignore:
  - "flow/alerting/email_alert_sender.go"
  - "flow/alerting/slack_alert_sender.go"
  - "flow/connectors/bigquery"
  - "flow/connectors/elasticsearch"
  - "flow/connectors/eventhub"
  - "flow/connectors/kafka"
  - "flow/connectors/pubsub"
  - "flow/connectors/snowflake"
  - "flow/middleware"
  - "flow/shared/aws_common"

component_management:
  individual_components:
    - component_id: full
      paths:
        - flow/datatypes/
        - flow/e2eshared/
      statuses:
        target: 100%
