package e2echeck

import "strings"

const sqlBoundaryWhitespace = " \t\n\r\f\v"
const generatedByServerSuffix = " /* generated by server */"

// Version IDs of the live e2e server images, using MySQL-style MMmmdd
// encoding.
const (
	queryTextMySQLVersionID   = 90700
	queryTextMariaDBVersionID = 130001
)

func EquivalentQueryText(a, b string, isMariaDB bool) bool {
	a = normalizeQueryTextBoundary(a)
	b = normalizeQueryTextBoundary(b)
	if equivalentNormalizedQueryText(a, b, isMariaDB) {
		return true
	}
	return queryTextWithOnlyEmptyTail(a, b, isMariaDB) || queryTextWithOnlyEmptyTail(b, a, isMariaDB)
}

func equivalentNormalizedQueryText(a, b string, isMariaDB bool) bool {
	return a == b || plainifySkippedComments(a, isMariaDB) == plainifySkippedComments(b, isMariaDB)
}

func IsHarnessControlQuery(s string) bool {
	q := normalizeQueryTextBoundary(s)
	if strings.HasSuffix(q, generatedByServerSuffix) {
		q = normalizeQueryTextBoundary(strings.TrimSuffix(q, generatedByServerSuffix))
	}
	return strings.HasPrefix(q, "DROP TABLE IF EXISTS `") && strings.HasSuffix(q, "`") ||
		strings.HasPrefix(q, "CREATE TABLE `fixture`")
}

func normalizeQueryTextBoundary(s string) string {
	s = strings.Trim(s, sqlBoundaryWhitespace)
	if strings.HasSuffix(s, ";") {
		s = strings.Trim(s[:len(s)-1], sqlBoundaryWhitespace)
	}
	return s
}

func queryTextWithOnlyEmptyTail(candidate, base string, isMariaDB bool) bool {
	for i := 0; i < len(candidate); {
		switch candidate[i] {
		case '\'', '"', '`':
			i = skipQuotedQueryText(candidate, i, candidate[i])
			continue
		case '[':
			i = skipQuotedQueryText(candidate, i, ']')
			continue
		case '#':
			i = skipLineCommentQueryText(candidate, i+1)
			continue
		case '-':
			if i+2 < len(candidate) && candidate[i+1] == '-' && isSQLBoundaryWhitespace(candidate[i+2]) {
				i = skipLineCommentQueryText(candidate, i+3)
				continue
			}
		case '/':
			if i+1 < len(candidate) && candidate[i+1] == '*' {
				i = skipBlockCommentQueryText(candidate, i+2)
				continue
			}
		case ';':
			head := normalizeQueryTextBoundary(candidate[:i+1])
			if equivalentNormalizedQueryText(head, base, isMariaDB) && onlyEmptyQueryTextStatements(candidate[i+1:]) {
				return true
			}
		}
		i++
	}
	return false
}

func onlyEmptyQueryTextStatements(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] != ';' && !isSQLBoundaryWhitespace(s[i]) {
			return false
		}
	}
	return true
}

func skipLineCommentQueryText(s string, pos int) int {
	for pos < len(s) && s[pos] != '\n' && s[pos] != 0 {
		pos++
	}
	return pos
}

func skipBlockCommentQueryText(s string, pos int) int {
	if end := strings.Index(s[pos:], "*/"); end >= 0 {
		return pos + end + 2
	}
	return len(s)
}

func isSQLBoundaryWhitespace(c byte) bool {
	return strings.IndexByte(sqlBoundaryWhitespace, c) >= 0
}

func plainifySkippedComments(s string, isMariaDB bool) string {
	var out []byte
	for i := 0; i+3 < len(s); {
		switch s[i] {
		case '\'', '"', '`':
			i = skipQuotedQueryText(s, i, s[i])
			continue
		case '[':
			i = skipQuotedQueryText(s, i, ']')
			continue
		}
		if s[i] != '/' || s[i+1] != '*' {
			i++
			continue
		}
		action, scanFrom := classifyExecutableCommentForQueryText(s, i, isMariaDB)
		switch action {
		case queryTextCommentSkipped:
			out = plainifySkippedCommentMarker(s, out, i)
			if end := strings.Index(s[i+2:], "*/"); end >= 0 {
				i += 2 + end + 2
			} else {
				i = len(s)
			}
			continue
		case queryTextCommentExecutable:
			i = scanFrom
			continue
		default:
			end := strings.Index(s[i+2:], "*/")
			if end < 0 {
				break
			}
			i += 2 + end + 2
		}
	}
	if out == nil {
		return s
	}
	return string(out)
}

type queryTextCommentAction int

const (
	queryTextCommentPlain queryTextCommentAction = iota
	queryTextCommentExecutable
	queryTextCommentSkipped
)

func classifyExecutableCommentForQueryText(s string, i int, isMariaDB bool) (queryTextCommentAction, int) {
	body := i + 2
	if body >= len(s) {
		return queryTextCommentPlain, body
	}
	switch {
	case s[body] == '!':
		if isMariaDB && body+1 < len(s) && s[body+1] == '!' {
			if versionLen, _ := queryTextVersionPrefix(s, body+2, true); versionLen > 0 {
				return queryTextCommentSkipped, body + 2 + versionLen
			}
			return queryTextCommentExecutable, body + 2
		}
		versionLen, version := queryTextVersionPrefix(s, body+1, isMariaDB)
		if versionLen > 0 {
			if isMariaDB {
				if version > queryTextMariaDBVersionID || (version >= 50700 && version <= 99999) {
					return queryTextCommentSkipped, body + 1 + versionLen
				}
			} else if version > queryTextMySQLVersionID {
				return queryTextCommentSkipped, body + 1 + versionLen
			}
		}
		return queryTextCommentExecutable, body + 1 + versionLen
	case isMariaDB && body+1 < len(s) && s[body] == 'M' && s[body+1] == '!':
		versionPos := body + 2
		if versionPos < len(s) && s[versionPos] == '!' {
			if versionLen, _ := queryTextVersionPrefix(s, versionPos+1, true); versionLen > 0 {
				return queryTextCommentSkipped, versionPos + 1 + versionLen
			}
			versionPos++
		}
		versionLen, version := queryTextVersionPrefix(s, versionPos, true)
		if versionLen > 0 && version > queryTextMariaDBVersionID {
			return queryTextCommentSkipped, versionPos + versionLen
		}
		return queryTextCommentExecutable, versionPos + versionLen
	default:
		return queryTextCommentPlain, body
	}
}

func plainifySkippedCommentMarker(s string, out []byte, i int) []byte {
	if i+2 >= len(s) || s[i] != '/' || s[i+1] != '*' {
		return out
	}
	body := i + 2
	switch {
	case body+1 < len(s) && s[body] == '!' && s[body+1] == '!':
		out = ensureQueryTextCopy(s, out)
		out[body] = ' '
		out[body+1] = ' '
		return out
	case body+1 < len(s) && s[body] == 'M' && s[body+1] == '!':
		out = ensureQueryTextCopy(s, out)
		out[body] = ' '
		out[body+1] = ' '
		return out
	case s[body] == '!':
		out = ensureQueryTextCopy(s, out)
		out[body] = ' '
		return out
	default:
		return out
	}
}

func ensureQueryTextCopy(s string, out []byte) []byte {
	if out != nil {
		return out
	}
	cp := []byte(s)
	return cp
}

func skipQuotedQueryText(s string, pos int, closer byte) int {
	i := pos + 1
	for i < len(s) {
		switch s[i] {
		case closer:
			if i+1 < len(s) && s[i+1] == closer {
				i += 2
				continue
			}
			return i + 1
		case '\\':
			i += 2
		default:
			i++
		}
	}
	return len(s)
}

func queryTextVersionPrefix(s string, pos int, isMariaDB bool) (int, int) {
	for i := range 5 {
		if pos+i >= len(s) || s[pos+i] < '0' || s[pos+i] > '9' {
			return 0, 0
		}
	}
	n := 5
	if pos+5 < len(s) && s[pos+5] >= '0' && s[pos+5] <= '9' &&
		(isMariaDB || pos+6 < len(s) && isSQLBoundaryWhitespace(s[pos+6])) {
		n = 6
	}
	version := 0
	for _, c := range []byte(s[pos : pos+n]) {
		version = version*10 + int(c-'0')
	}
	return n, version
}
