issues:
  exclude-dirs:
    - generated
    - connectors/postgres/sanitize
linters:
  enable:
    - containedctx
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - forbidigo
    - gci
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - ineffassign
    - intrange
    - lll
    - misspell
    - musttag
    - nakedret
    - nolintlint
    - nonamedreturns
    - perfsprint
    - prealloc
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
linters-settings:
  gci:
    sections:
      - standard
      - 'prefix(github.com/PeerDB-io)'
      - default
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - importShadow
      - paramTypeCombine
      - sprintfQuotedString
      - unnamedResult
      - whyNoLint
    settings:
      hugeParam:
        sizeThreshold: 512
  gosec:
    excludes:
      - G115
  govet:
    enable-all: true
    disable:
      - shadow
  stylecheck:
    checks:
      - all
      - '-ST1003'
  lll:
    line-length: 144
    tab-width: 4
