version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - containedctx
    - copyloopvar
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - exptostd
    - forbidigo
    - funcorder
    - gocritic
    - gosec
    - iface
    - intrange
    - lll
    - misspell
    - musttag
    - nakedret
    - nilnesserr
    - nolintlint
    - nonamedreturns
    - perfsprint
    - prealloc
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    funcorder:
      struct-method: false
    gocritic:
      disabled-checks:
        - ifElseChain
        - importShadow
        - paramTypeCombine
        - sprintfQuotedString
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 1024
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - shadow
      enable-all: true
    iface:
      enable:
        - identical
        - unused
        - opaque
    lll:
      line-length: 144
      tab-width: 4
    staticcheck:
      checks:
        - all
        - -ST1003
        - -QF1001
        - -QF1003
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - generated
      - connectors/postgres/sanitize
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/PeerDB-io)
        - default
  exclusions:
    generated: lax
    paths:
      - generated
      - connectors/postgres/sanitize
