run:
  skip-dirs:
    - generated
linters:
  enable:
    - dogsled
    - dupl
    - gofumpt
    - gosec
    - gosimple
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - prealloc
    - staticcheck
    - ineffassign
    - unused
    - lll
linters-settings:
  lll:
    line-length: 120
    tab-width: 4
