run:
  skip-dirs:
    - generated
linters:
  enable:
    - dogsled
    - durationcheck
    - errcheck
    - gofumpt
    - gosec
    - gosimple
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    - prealloc
    - thelper
    - ineffassign
    - unparam
    - unused
    - lll
linters-settings:
  stylecheck:
    checks:
      - all
      - '-ST1003'
  lll:
    line-length: 144
    tab-width: 4
