run:
  skip-dirs:
    - generated
linters:
  enable-all: true
  disable:
    - funlen
    - gocognit
    - godox
linters-settings:
  lll:
    line-length: 120
    tab-width: 4
  revive:
    rules:
      - name: if-return
        disabled: true
