run:
  skip-dirs:
    - generated
linters:
  enable:
    - dogsled
    - durationcheck
    - errcheck
    - forbidigo
    - gci
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - ineffassign
    - lll
    - misspell
    - musttag
    - nakedret
    - nolintlint
    - nonamedreturns
    - perfsprint
    - prealloc
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unparam
    - unused
    - wastedassign
    - whitespace
linters-settings:
  gci:
    sections:
      - standard
      - 'prefix(github.com/PeerDB-io)'
      - default
  gocritic:
    disabled-checks:
      - ifElseChain
  stylecheck:
    checks:
      - all
      - '-ST1003'
  lll:
    line-length: 144
    tab-width: 4
