run:
  skip-dirs:
    - generated
linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustivestruct
    - funlen
    - gocognit
    - godox
    - golint # deprecated in favor of revive
    - gomnd
    - nosnakecase
    - paralleltest
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl
linters-settings:
  forbidigo:
    tests: false
  stylecheck:
    checks:
      - all
      - '-ST1003'
  lll:
    line-length: 144
    tab-width: 4
  revive:
    rules:
      - name: if-return
        disabled: true
