SELECT COUNT(*) FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT INT8 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT -INT8 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (INT8 + 1) FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (INT8 - 1) FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (INT8 * 65536) FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (INT8 / INT8) FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT BOOL FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT NOT BOOL FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT DATE FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT DATE::TIMESTAMP FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT DATE + INTERVAL '1 DAY' FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT TIME FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT TIME + INTERVAL '-17 SECONDS' FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT INT2 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (INT2 - 2)::INT4 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT INT4 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (INT4 - 1729)::INT8 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT FLOAT4 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (FLOAT4 - 1.03)::FLOAT8 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (FLOAT4 - 2)::INT4 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT FLOAT8 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (FLOAT8 + 4000000000000)::INT8 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT TEXT FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT SUBSTRING(TEXT, 5, 6) FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT TIMESTAMP FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT TIMESTAMP::TIMESTAMPTZ FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (TIMESTAMP + INTERVAL '1 YEAR, 1 MONTH, 1 DAY, 1 SECOND') FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT TIMESTAMPTZ FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT TIMESTAMPTZ::TIMESTAMP FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT (TIMESTAMPTZ - INTERVAL '100 YEARS, 100 MONTHS, 100 DAYS, 100 SECONDS') FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT BYTEA FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT LENGTH(BYTEA) FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT UUID FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT JSONB FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT JSONB -> 'age' FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;
SELECT JSONB -> 'gender' FROM FIRST_POSTGRES.PUBLIC.ILMETZIK;

SELECT INT8 FROM FIRST_POSTGRES.PUBLIC.ILMETZIK WHERE INT4=172;

CREATE TABLE IF NOT EXISTS FIRST_POSTGRES.PUBLIC.TEST_TABLE(INT4 INT4, BOOL BOOL, INT8 INT8 PRIMARY KEY);
INSERT INTO FIRST_POSTGRES.PUBLIC.TEST_TABLE VALUES(17, true, 26);
SELECT * FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE;
UPDATE FIRST_POSTGRES.PUBLIC.TEST_TABLE SET INT4 = INT4 + 7 WHERE INT8 = 24;
SELECT * FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE;
UPDATE FIRST_POSTGRES.PUBLIC.TEST_TABLE SET INT4 = INT4 + 7 WHERE INT8 = 26;
SELECT * FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE;
DELETE FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE WHERE INT4 = 26;
SELECT * FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE;
DELETE FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE WHERE INT4 = 24;
SELECT * FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE;
INSERT INTO FIRST_POSTGRES.PUBLIC.TEST_TABLE VALUES(1, true, 1);
SELECT * FROM FIRST_POSTGRES.PUBLIC.TEST_TABLE;
TRUNCATE TABLE FIRST_POSTGRES.PUBLIC.TEST_TABLE;
DROP TABLE FIRST_POSTGRES.PUBLIC.TEST_TABLE;