SELECT COUNT(*) FROM pg_test.PUBLIC.ILMETZIK;

SELECT INT8 FROM pg_test.PUBLIC.ILMETZIK;
SELECT -INT8 FROM pg_test.PUBLIC.ILMETZIK;
SELECT (INT8 + 1) FROM pg_test.PUBLIC.ILMETZIK;
SELECT (INT8 - 1) FROM pg_test.PUBLIC.ILMETZIK;
SELECT (INT8 * 65536) FROM pg_test.PUBLIC.ILMETZIK;
SELECT (INT8 / INT8) FROM pg_test.PUBLIC.ILMETZIK;

SELECT BOOL FROM pg_test.PUBLIC.ILMETZIK;
SELECT NOT BOOL FROM pg_test.PUBLIC.ILMETZIK;

SELECT DATE FROM pg_test.PUBLIC.ILMETZIK;
SELECT DATE::TIMESTAMP FROM pg_test.PUBLIC.ILMETZIK;
SELECT DATE + INTERVAL '1 DAY' FROM pg_test.PUBLIC.ILMETZIK;

SELECT TIME FROM pg_test.PUBLIC.ILMETZIK;
SELECT TIME + INTERVAL '-17 SECONDS' FROM pg_test.PUBLIC.ILMETZIK;

SELECT INT2 FROM pg_test.PUBLIC.ILMETZIK;
SELECT (INT2 - 2)::INT4 FROM pg_test.PUBLIC.ILMETZIK;

SELECT INT4 FROM pg_test.PUBLIC.ILMETZIK;
SELECT (INT4 - 1729)::INT8 FROM pg_test.PUBLIC.ILMETZIK;

SELECT FLOAT4 FROM pg_test.PUBLIC.ILMETZIK;
SELECT (FLOAT4 - 1.03)::FLOAT8 FROM pg_test.PUBLIC.ILMETZIK;
SELECT (FLOAT4 - 2)::INT4 FROM pg_test.PUBLIC.ILMETZIK;

SELECT FLOAT8 FROM pg_test.PUBLIC.ILMETZIK;
SELECT (FLOAT8 + 4000000000000)::INT8 FROM pg_test.PUBLIC.ILMETZIK;

SELECT TEXT FROM pg_test.PUBLIC.ILMETZIK;
SELECT SUBSTRING(TEXT, 5, 6) FROM pg_test.PUBLIC.ILMETZIK;

SELECT TIMESTAMP FROM pg_test.PUBLIC.ILMETZIK;
SELECT TIMESTAMP::TIMESTAMPTZ FROM pg_test.PUBLIC.ILMETZIK;
SELECT (TIMESTAMP + INTERVAL '1 YEAR, 1 MONTH, 1 DAY, 1 SECOND') FROM pg_test.PUBLIC.ILMETZIK;

SELECT TIMESTAMPTZ FROM pg_test.PUBLIC.ILMETZIK;
SELECT TIMESTAMPTZ::TIMESTAMP FROM pg_test.PUBLIC.ILMETZIK;
SELECT (TIMESTAMPTZ - INTERVAL '100 YEARS, 100 MONTHS, 100 DAYS, 100 SECONDS') FROM pg_test.PUBLIC.ILMETZIK;

SELECT BYTEA FROM pg_test.PUBLIC.ILMETZIK;
SELECT LENGTH(BYTEA) FROM pg_test.PUBLIC.ILMETZIK;

SELECT UUID FROM pg_test.PUBLIC.ILMETZIK;

SELECT JSONB FROM pg_test.PUBLIC.ILMETZIK;
SELECT JSONB -> 'age' FROM pg_test.PUBLIC.ILMETZIK;
SELECT JSONB -> 'gender' FROM pg_test.PUBLIC.ILMETZIK;

SELECT INT8 FROM pg_test.PUBLIC.ILMETZIK WHERE INT4=172;

CREATE TABLE IF NOT EXISTS pg_test.PUBLIC.TEST_TABLE(INT4 INT4, BOOL BOOL, INT8 INT8 PRIMARY KEY);
INSERT INTO pg_test.PUBLIC.TEST_TABLE VALUES(17, true, 26);
SELECT * FROM pg_test.PUBLIC.TEST_TABLE;
UPDATE pg_test.PUBLIC.TEST_TABLE SET INT4 = INT4 + 7 WHERE INT8 = 24;
SELECT * FROM pg_test.PUBLIC.TEST_TABLE;
UPDATE pg_test.PUBLIC.TEST_TABLE SET INT4 = INT4 + 7 WHERE INT8 = 26;
SELECT * FROM pg_test.PUBLIC.TEST_TABLE;
DELETE FROM pg_test.PUBLIC.TEST_TABLE WHERE INT4 = 26;
SELECT * FROM pg_test.PUBLIC.TEST_TABLE;
DELETE FROM pg_test.PUBLIC.TEST_TABLE WHERE INT4 = 24;
SELECT * FROM pg_test.PUBLIC.TEST_TABLE;
INSERT INTO pg_test.PUBLIC.TEST_TABLE VALUES(1, true, 1);
SELECT * FROM pg_test.PUBLIC.TEST_TABLE;
TRUNCATE TABLE pg_test.PUBLIC.TEST_TABLE;
DROP TABLE pg_test.PUBLIC.TEST_TABLE;