/*Projections*/
-- SELECT distinct
SELECT DISTINCT NAME FROM SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1;

-- text concat
SELECT DISTINCT NAME || ID::TEXT FROM SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1;

-- simple additions
SELECT id+1 FROM SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1;

-- projection aliasing
SELECT id as id_alias FROM SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1;

-- division and multiplication in projections
SELECT id/5.0,id*5.0 FROM SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1;

-- typecasting in projections
SELECT id::text FROM SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1;

-- CASE in projections
SELECT CASE when id=1 then id else 0 end from SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1;

/*WHERE*/
-- Simple WHERE
SELECT * from SNOWFLAKE_CI.PUBLIC.USERS where id=1;

-- Multiple WHERE clause
SELECT * from SNOWFLAKE_CI.PUBLIC.USERS where id=1 AND country='India';

-- Non equality WHERE
SELECT * from SNOWFLAKE_CI.PUBLIC.USERS where id!=1 LIMIT 1;
SELECT id from SNOWFLAKE_CI.PUBLIC.USERS where id>1  and id < 5 LIMIT 1;
SELECT id from SNOWFLAKE_CI.PUBLIC.USERS where id>1  and id < 5 and country !='India' LIMIT 1;
SELECT country from SNOWFLAKE_CI.PUBLIC.USERS where id>1  and id <= 5 LIMIT 1;

/* ORDER BY */
SELECT id from SNOWFLAKE_CI.PUBLIC.USERS ORDER BY country LIMIT 1;
SELECT id from SNOWFLAKE_CI.PUBLIC.USERS ORDER BY country DESC LIMIT 1;
SELECT id from SNOWFLAKE_CI.PUBLIC.USERS ORDER BY id DESC LIMIT 1;
SELECT * from SNOWFLAKE_CI.PUBLIC.USERS ORDER BY country desc,id asc LIMIT 1;


/* Aggregates */
-- Aggregates
SELECT count(*),sum(id),count(distinct id),avg(id),max(id),min(id) from SNOWFLAKE_CI.PUBLIC.USERS;

-- group by with aggregates
SELECT country,count(*),sum(id),count(distinct id),avg(id),max(id),min(id) from SNOWFLAKE_CI.PUBLIC.USERS GROUP BY country;

-- group by with CASE
SELECT country,count(*),sum(CASE WHEN id=1 THEN 1 ELSE 0 END),count(distinct id),avg(id) from SNOWFLAKE_CI.PUBLIC.USERS GROUP BY country;

-- group by with ORDER BY
SELECT country,count(*) from SNOWFLAKE_CI.PUBLIC.USERS GROUP BY country ORDER BY 1;
SELECT country,count(*) from SNOWFLAKE_CI.PUBLIC.USERS GROUP BY country ORDER BY 2;
SELECT country,count(*) from SNOWFLAKE_CI.PUBLIC.USERS GROUP BY country ORDER BY 2 LIMIT 1;

-- group by, WHERE, ORDER BY, HAVING, LIMIT
SELECT country,count(*),sum(id),count(distinct id),avg(id),max(id),min(id) from SNOWFLAKE_CI.PUBLIC.USERS where id=1 AND country='India' GROUP BY country HAVING count(*)>0 ORDER BY country DESC LIMIT 1;

-- HAVING
SELECT country,count(*) from SNOWFLAKE_CI.PUBLIC.USERS GROUP BY country HAVING count(*)>1;

-- explicit join users and events with count
SELECT count(*) from SNOWFLAKE_CI.PUBLIC.USERS u JOIN SNOWFLAKE_CI.PUBLIC.EVENTS e ON u.id=e.user_id;

-- non explicit join users and events with count
SELECT count(*) from SNOWFLAKE_CI.PUBLIC.USERS u,SNOWFLAKE_CI.PUBLIC.EVENTS e WHERE u.id=e.user_id;

-- Join with GROUP BY, WHERE, ORDER BY, HAVING, LIMIT
SELECT country,count(*) from SNOWFLAKE_CI.PUBLIC.USERS u JOIN SNOWFLAKE_CI.PUBLIC.EVENTS e ON u.id=e.user_id where u.id>1 GROUP BY country HAVING count(*)>0 ORDER BY country DESC LIMIT 5;

-- LEFT JOIN
SELECT count(*) from SNOWFLAKE_CI.PUBLIC.EVENTS e LEFT JOIN SNOWFLAKE_CI.PUBLIC.USERS u ON u.id=e.user_id WHERE country='Indonesia';

-- RIGHT JOIN
SELECT count(*) from SNOWFLAKE_CI.PUBLIC.EVENTS e RIGHT JOIN SNOWFLAKE_CI.PUBLIC.USERS u ON u.id=e.user_id WHERE country='Indonesia';
SELECT count(*) from SNOWFLAKE_CI.PUBLIC.EVENTS e RIGHT JOIN SNOWFLAKE_CI.PUBLIC.USERS u ON u.id=e.user_id JOIN SNOWFLAKE_CI.PUBLIC.USERS u1 ON u1.id=u.id WHERE u1.country='Indonesia';

-- Basic VARIANT: checking if type can be retrieved.
SELECT T FROM SNOWFLAKE_CI.T_VARIANT LIMIT 1;
SELECT T -> country FROM SNOWFLAKE_CI.T_VARIANT LIMIT 1;
SELECT T -> country->code FROM SNOWFLAKE_CI.T_VARIANT LIMIT 1;

-- DATETIME data type tests
SELECT COUNT(*) FROM SNOWFLAKE_CI.PUBLIC.DATETIME;

-- DATE tests
SELECT DATE FROM SNOWFLAKE_CI.PUBLIC.DATETIME;
SELECT DATE + INTERVAL '1 DAY' FROM SNOWFLAKE_CI.PUBLIC.DATETIME;
SELECT DATE + INTERVAL '1 SECOND' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT DATE + INTERVAL '1000 YEARS, 1000 MONTHS, 100 DAYS, 10 HOURS, 1 MINUTE' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT DATE + INTERVAL '-1000 YEARS, -1000 MONTHS, -100 DAYS, -10 HOURS, -1 MINUTE' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE DATE < '2022-01-01'::DATE LIMIT 1;
SELECT DATE + INTERVAL '-1 YEAR, 1 DAY' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE DATE < '2022-01-01'::DATE LIMIT 1;
SELECT DATE::TIMESTAMP FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT DATE::TIMESTAMP WITH TIME ZONE FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;

-- TIME tests
SELECT TIME FROM SNOWFLAKE_CI.PUBLIC.DATETIME;
SELECT TIME + INTERVAL '1 MINUTE' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIME + INTERVAL '1 HOUR' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIME > '22:00'::TIME LIMIT 1;
SELECT TIME + INTERVAL '-23 HOURS, 1 SECOND' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIME > '22:00'::TIME LIMIT 1;
SELECT TIME + INTERVAL '-0.25 SECONDS' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIME + INTERVAL '1000000000000 SECONDS' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIME + INTERVAL '-1000000000000 SECONDS' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIME > '2200'::TIME LIMIT 1;

--TIMESTAMP WITHOUT TIME ZONE tests
SELECT TIMESTAMP_NTZ FROM SNOWFLAKE_CI.PUBLIC.DATETIME;
SELECT TIMESTAMP_NTZ + INTERVAL '-9 HOURS, -1 SECOND' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIMESTAMP_NTZ + INTERVAL '1 MINUTE' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIMESTAMP_NTZ < '2022-01-01' LIMIT 1;
SELECT TIMESTAMP_NTZ + INTERVAL '1 DAY' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIMESTAMP_NTZ > '2022-01-01' LIMIT 1;
SELECT TIMESTAMP_NTZ + INTERVAL '60 MINUTES, 60 SECONDS' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIMESTAMP_NTZ AT TIME ZONE 'UTC' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIMESTAMP_NTZ AT TIME ZONE 'Asia/Kolkata' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIMESTAMP_NTZ > '2022-01-01' LIMIT 1;

--TIMESTAMP WITH TIME ZONE tests
SELECT TIMESTAMP_TZ FROM SNOWFLAKE_CI.PUBLIC.DATETIME;
SELECT TIMESTAMP_TZ + INTERVAL '1 DAY' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIMESTAMP_TZ > '2023-01-01' LIMIT 1;
SELECT TIMESTAMP_TZ + INTERVAL '-3 HOURS, -1 SECOND' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIMESTAMP_TZ AT TIME ZONE 'UTC' FROM SNOWFLAKE_CI.PUBLIC.DATETIME LIMIT 1;
SELECT TIMESTAMP_TZ AT TIME ZONE 'Asia/Kolkata' FROM SNOWFLAKE_CI.PUBLIC.DATETIME WHERE TIMESTAMP_TZ > '2023-01-01' LIMIT 1;


DECLARE liahona CURSOR FOR SELECT NAME FROM SNOWFLAKE_CI.PUBLIC.USERS LIMIT 1000;
FETCH 1 IN liahona;
FETCH FORWARD 1 IN liahona;
FETCH NEXT IN liahona;