package e2e

import (
	"context"
	"fmt"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/PeerDB-io/peerdb/tools/ddlfuzz/internal/e2echeck"
	"github.com/go-mysql-org/go-mysql/client"
	gomysql "github.com/go-mysql-org/go-mysql/mysql"
	"github.com/go-mysql-org/go-mysql/replication"
)

type expectKind string

const (
	expectMarker    expectKind = "marker"
	expectDDL       expectKind = "ddl"
	expectControl   expectKind = "control"
	expectUncertain expectKind = "uncertain"
)

type caseExpect struct {
	Kind            expectKind
	WorkerID        int
	CaseID          string
	Submitted       string
	SQLModeName     string
	SQLModeRelevant uint64
	Before          snapshot
	After           snapshot
	BeforeTables    map[string]bool
	AfterTables     map[string]bool
	Source          string
	Queue           *queueItem
	DriverError     string
}

type expectQueue struct {
	mu    sync.Mutex
	cond  *sync.Cond
	items []caseExpect
}

func newExpectQueue() *expectQueue {
	q := &expectQueue{}
	q.cond = sync.NewCond(&q.mu)
	return q
}

func (q *expectQueue) Push(exp caseExpect) {
	q.mu.Lock()
	q.items = append(q.items, exp)
	q.mu.Unlock()
	q.cond.Broadcast()
}

func (q *expectQueue) PopWait(ctx context.Context, timeout time.Duration) (caseExpect, error) {
	deadline := time.Now().Add(timeout)
	stop := context.AfterFunc(ctx, func() {
		q.cond.Broadcast()
	})
	defer stop()

	q.mu.Lock()
	defer q.mu.Unlock()
	for len(q.items) == 0 {
		if err := ctx.Err(); err != nil {
			return caseExpect{}, err
		}
		remaining := time.Until(deadline)
		if remaining <= 0 {
			return caseExpect{}, fmt.Errorf("timed out waiting for matcher expectation")
		}
		timer := time.AfterFunc(remaining, func() {
			q.cond.Broadcast()
		})
		q.cond.Wait()
		timer.Stop()
	}
	exp := q.items[0]
	copy(q.items, q.items[1:])
	q.items = q.items[:len(q.items)-1]
	return exp, nil
}

func (q *expectQueue) Len() int {
	q.mu.Lock()
	defer q.mu.Unlock()
	return len(q.items)
}

func (q *expectQueue) snapshotLocked() []caseExpect {
	items := make([]caseExpect, len(q.items))
	copy(items, q.items)
	return items
}

func (q *expectQueue) popPrefixLocked(n int) []caseExpect {
	if n <= 0 {
		return nil
	}
	popped := make([]caseExpect, n)
	copy(popped, q.items[:n])
	copy(q.items, q.items[n:])
	q.items = q.items[:len(q.items)-n]
	return popped
}

// markerCaseID reports whether query is one of our per-case marker DROPs
// (DROP TABLE IF EXISTS `__m_<caseID>`), tolerating the server-appended
// " /* generated by server */" suffix, and returns the embedded caseID.
func markerCaseID(query string) (string, bool) {
	q := strings.TrimSuffix(query, " /* generated by server */")
	const pre = "DROP TABLE IF EXISTS `__m_"
	if !strings.HasPrefix(q, pre) || !strings.HasSuffix(q, "`") {
		return "", false
	}
	id := q[len(pre) : len(q)-1]
	if id == "" || strings.Contains(id, "`") {
		return "", false
	}
	return id, true
}

type matcher struct {
	ec       engineConfig
	stateDir string
	queues   map[string]*expectQueue
	stats    *Stats
	sides    *sideChannels
	errs     chan<- error
	syncer   *replication.BinlogSyncer
}

func startMatcher(ctx context.Context, ec engineConfig, stateDir string, queues map[string]*expectQueue, stats *Stats, sides *sideChannels, errs chan<- error) (*matcher, error) {
	pos, err := captureBinlogPosition(ec)
	if err != nil {
		return nil, err
	}
	syncer := replication.NewBinlogSyncer(replication.BinlogSyncerConfig{
		ServerID:         uint32(time.Now().UnixNano() & 0xffffffff),
		Flavor:           ec.Flavor,
		Host:             ec.Host,
		Port:             ec.Port,
		User:             rootUser,
		Password:         rootPassword,
		DisableRetrySync: true,
		UseDecimal:       true,
		ParseTime:        true,
		HeartbeatPeriod:  time.Minute,
	})
	stream, err := syncer.StartSync(pos)
	if err != nil {
		syncer.Close()
		return nil, err
	}
	m := &matcher{ec: ec, stateDir: stateDir, queues: queues, stats: stats, sides: sides, errs: errs, syncer: syncer}
	go m.run(ctx, stream)
	return m, nil
}

func (m *matcher) Close() {
	if m.syncer != nil {
		m.syncer.Close()
	}
}

func (m *matcher) run(ctx context.Context, stream *replication.BinlogStreamer) {
	for {
		select {
		case <-ctx.Done():
			return
		default:
		}
		eventCtx, cancel := context.WithTimeout(ctx, time.Second)
		ev, err := stream.GetEvent(eventCtx)
		cancel()
		if err != nil {
			if ctx.Err() != nil || strings.Contains(err.Error(), "context deadline") {
				m.updatePending()
				continue
			}
			m.reportHarness(fmt.Errorf("binlog stream: %w", err))
			return
		}
		qe, ok := ev.Event.(*replication.QueryEvent)
		if !ok {
			continue
		}
		schema := string(qe.Schema)
		q := m.queues[schema]
		if q == nil {
			continue
		}
		if err := m.processEvent(ctx, q, ev, qe); err != nil {
			m.reportHarness(fmt.Errorf("schema %s: %w", schema, err))
			return
		}
		m.updatePending()
	}
}

// processEvent aligns one QueryEvent against the worker's FIFO and dispatches
// the outcome. A returned error means the stream/FIFO invariant is broken
// (harness error); benign anomalies resolve into stats or findings instead.
func (m *matcher) processEvent(ctx context.Context, q *expectQueue, ev *replication.BinlogEvent, qe *replication.QueryEvent) error {
	out, err := m.alignEvent(ctx, q, qe)
	if err != nil {
		return err
	}
	m.resolveAlignOutcome(ev, qe, out)
	if out.matched && out.exp.Kind != expectUncertain {
		m.handleQueryEvent(ctx, ev, qe, out.exp)
	}
	return nil
}

type alignDecisionKind int

const (
	alignDecisionMatch alignDecisionKind = iota
	alignDecisionExtra
	alignDecisionInconclusive
	alignDecisionError
)

type alignDecision struct {
	kind  alignDecisionKind
	index int
	err   string
}

type alignOutcome struct {
	matched bool
	exp     caseExpect
	skipped []caseExpect
	extra   bool
}

func decideAlign(query string, items []caseExpect, isMariaDB bool) alignDecision {
	if _, isMarker := markerCaseID(query); isMarker {
		for i, item := range items {
			if item.Kind == expectMarker && controlQueryMatches(query, item.Submitted) {
				return alignDecision{kind: alignDecisionMatch, index: i}
			}
		}
		return alignDecision{kind: alignDecisionError, err: "marker event without matching expectation"}
	}

	boundarySeen := false
	for i, item := range items {
		switch item.Kind {
		case expectUncertain:
			if e2echeck.EquivalentQueryText(item.Submitted, query, isMariaDB) {
				return alignDecision{kind: alignDecisionMatch, index: i}
			}
		case expectControl:
			if controlQueryMatches(query, item.Submitted) {
				return alignDecision{kind: alignDecisionMatch, index: i}
			}
		case expectMarker:
			boundarySeen = true
		case expectDDL:
			if e2echeck.EquivalentQueryText(item.Submitted, query, isMariaDB) ||
				(!e2echeck.IsHarnessControlQuery(query) && !boundarySeen) {
				return alignDecision{kind: alignDecisionMatch, index: i}
			}
		}
	}
	if boundarySeen {
		return alignDecision{kind: alignDecisionExtra}
	}
	return alignDecision{kind: alignDecisionInconclusive}
}

func (m *matcher) alignEvent(ctx context.Context, q *expectQueue, qe *replication.QueryEvent) (alignOutcome, error) {
	deadline := time.Now().Add(30 * time.Second)
	stop := context.AfterFunc(ctx, func() {
		q.cond.Broadcast()
	})
	defer stop()

	q.mu.Lock()
	defer q.mu.Unlock()
	for {
		items := q.snapshotLocked()
		decision := decideAlign(string(qe.Query), items, m.ec.IsMariaDB)
		switch decision.kind {
		case alignDecisionMatch:
			popped := q.popPrefixLocked(decision.index + 1)
			return alignOutcome{
				matched: true,
				exp:     popped[len(popped)-1],
				skipped: popped[:len(popped)-1],
			}, nil
		case alignDecisionExtra:
			return alignOutcome{extra: true}, nil
		case alignDecisionError:
			return alignOutcome{}, fmt.Errorf("%s: %q", decision.err, string(qe.Query))
		case alignDecisionInconclusive:
			if err := ctx.Err(); err != nil {
				return alignOutcome{}, err
			}
			remaining := time.Until(deadline)
			if remaining <= 0 {
				return alignOutcome{}, fmt.Errorf("timed out waiting for matcher expectation")
			}
			timer := time.AfterFunc(remaining, func() {
				q.cond.Broadcast()
			})
			q.cond.Wait()
			timer.Stop()
		}
	}
}

func (m *matcher) resolveAlignOutcome(ev *replication.BinlogEvent, qe *replication.QueryEvent, out alignOutcome) {
	for _, exp := range out.skipped {
		m.resolveSkipped(exp)
	}
	if out.extra {
		m.handleUnexpectedEvent(ev, qe)
		return
	}
	if out.matched && out.exp.Kind == expectUncertain {
		m.handleExecRejectApplied(ev, qe, out.exp)
	}
}

func (m *matcher) resolveSkipped(exp caseExpect) {
	switch exp.Kind {
	case expectUncertain:
		m.stats.IncUncertainNoEvent(m.ec.Name)
	case expectMarker, expectControl:
		m.stats.IncSkippedControls(m.ec.Name)
	case expectDDL:
		actualDelta := diffSnapshots(exp.Before, exp.After)
		actualDelta.Renamed = inferRenames(exp.BeforeTables, exp.AfterTables)
		if actualDelta.Empty() {
			m.stats.IncNoopDDLs(m.ec.Name)
			if exp.Queue != nil {
				_ = completeQueueItem(m.stateDir, *exp.Queue, queueResult{
					Sig:     exp.Queue.Sig,
					Result:  "exec-reject",
					Details: "no binlog event (no-op statement)",
				})
				m.stats.IncQueueDone(m.ec.Name)
			}
			return
		}
		recordE2EFinding(m.stateDir, m.stats, findingInput{
			Class:       "e2e-missing-event",
			Engine:      m.ec,
			Statement:   []byte(exp.Submitted),
			SQLMode:     exp.SQLModeRelevant,
			SQLModeName: exp.SQLModeName,
			Delta:       actualDelta,
			Before:      exp.Before,
			After:       exp.After,
			Submitted:   exp.Submitted,
			Meta:        map[string]any{"source": exp.Source},
		})
		m.stats.IncMissingEvent(m.ec.Name)
		if exp.Queue != nil {
			_ = completeQueueItem(m.stateDir, *exp.Queue, queueResult{
				Sig:     exp.Queue.Sig,
				Result:  "still-diverges",
				Details: "schema changed but no binlog event",
			})
		}
	}
}

func (m *matcher) handleExecRejectApplied(ev *replication.BinlogEvent, qe *replication.QueryEvent, exp caseExpect) {
	actualDelta := diffSnapshots(exp.Before, exp.After)
	actualDelta.Renamed = inferRenames(exp.BeforeTables, exp.AfterTables)
	recordE2EFinding(m.stateDir, m.stats, findingInput{
		Class:       "e2e-exec-reject-applied",
		Engine:      m.ec,
		Statement:   []byte(exp.Submitted),
		SQLMode:     exp.SQLModeRelevant,
		SQLModeName: exp.SQLModeName,
		Delta:       actualDelta,
		Before:      exp.Before,
		After:       exp.After,
		RawEvent:    slices.Clone(ev.RawData),
		StatusVars:  slices.Clone(qe.StatusVars),
		Submitted:   exp.Submitted,
		BinlogText:  string(qe.Query),
		Meta: map[string]any{
			"driver_error": exp.DriverError,
			"source":       exp.Source,
		},
	})
	m.stats.IncExecRejectApplied(m.ec.Name)
}

func (m *matcher) handleUnexpectedEvent(ev *replication.BinlogEvent, qe *replication.QueryEvent) {
	recordE2EFinding(m.stateDir, m.stats, findingInput{
		Class:      "e2e-unexpected-event",
		Engine:     m.ec,
		Statement:  slices.Clone(qe.Query),
		RawEvent:   slices.Clone(ev.RawData),
		StatusVars: slices.Clone(qe.StatusVars),
		BinlogText: string(qe.Query),
		Meta: map[string]any{
			"schema": string(qe.Schema),
		},
	})
	m.stats.IncUnexpectedEvent(m.ec.Name)
}

func (m *matcher) handleQueryEvent(ctx context.Context, ev *replication.BinlogEvent, qe *replication.QueryEvent, exp caseExpect) {
	defer func() {
		if r := recover(); r != nil {
			actualDelta := diffSnapshots(exp.Before, exp.After)
			actualDelta.Renamed = inferRenames(exp.BeforeTables, exp.AfterTables)
			recordE2EFinding(m.stateDir, m.stats, findingInput{
				Class:       "e2e-panic",
				Engine:      m.ec,
				Statement:   []byte(exp.Submitted),
				SQLMode:     exp.SQLModeRelevant,
				SQLModeName: exp.SQLModeName,
				Delta:       actualDelta,
				Before:      exp.Before,
				After:       exp.After,
				RawEvent:    slices.Clone(ev.RawData),
				StatusVars:  slices.Clone(qe.StatusVars),
				Submitted:   exp.Submitted,
				BinlogText:  string(qe.Query),
				Meta: map[string]any{
					"panic": fmt.Sprint(r),
				},
			})
		}
	}()

	query := string(qe.Query)
	switch exp.Kind {
	case expectMarker:
		if !controlQueryMatches(query, exp.Submitted) {
			m.reportHarness(fmt.Errorf("marker mismatch schema=%s case=%s got=%q want=%q", string(qe.Schema), exp.CaseID, query, exp.Submitted))
			return
		}
		m.stats.IncMarker(m.ec.Name)
	case expectControl:
		if !controlQueryMatches(query, exp.Submitted) {
			m.reportHarness(fmt.Errorf("control mismatch schema=%s got=%q want=%q", string(qe.Schema), query, exp.Submitted))
			return
		}
		m.stats.IncControl(m.ec.Name)
	case expectDDL:
		checkLiveDDL(ctx, m.ec, m.stateDir, m.stats, m.sides, ev, qe, exp)
	}
}

func controlQueryMatches(got, want string) bool {
	return got == want || got == want+" /* generated by server */"
}

func (m *matcher) updatePending() {
	pending := 0
	for _, q := range m.queues {
		pending += q.Len()
	}
	m.stats.SetPending(m.ec.Name, pending)
}

func (m *matcher) reportHarness(err error) {
	select {
	case m.errs <- harnessError{Engine: m.ec.Name, Err: err}:
	default:
	}
}

func captureBinlogPosition(ec engineConfig) (gomysql.Position, error) {
	conn, err := client.Connect(ec.Addr, rootUser, rootPassword, "")
	if err != nil {
		return gomysql.Position{}, err
	}
	defer conn.Close()

	queries := []string{"SHOW BINARY LOG STATUS", "SHOW MASTER STATUS"}
	if ec.IsMariaDB {
		queries = []string{"SHOW BINLOG STATUS", "SHOW MASTER STATUS"}
	}
	var lastErr error
	for _, query := range queries {
		rs, err := conn.Execute(query)
		if err != nil {
			lastErr = err
			continue
		}
		if rs == nil || rs.Resultset == nil || rs.RowNumber() == 0 {
			lastErr = fmt.Errorf("%s returned no rows", query)
			continue
		}
		defer rs.Close()
		name, err := rs.GetString(0, 0)
		if err != nil {
			return gomysql.Position{}, err
		}
		pos, err := rs.GetUint(0, 1)
		if err != nil {
			return gomysql.Position{}, err
		}
		return gomysql.Position{Name: strings.Clone(name), Pos: uint32(pos)}, nil
	}
	return gomysql.Position{}, lastErr
}
