version: 2

sources:
  - name: peerdb_raw
    database: postgres
    schema: peerdb_stage
    tables:
      - name: raw_union_pool
  - name: direct_buys
    database: postgres
    schema: direct_buys
    tables:
      - name: client_code_mapping
      - name: currency_mapping
