{
 "title": "PeerDB mirror monitoring dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job_name",
    "query": {
     "query": "metrics(flow_worker_${job_type}_.*_total_records_pulled)"
    }
   },
   {
    "name": "job_type",
    "query": {
     "query": "metrics(flow_worker_.*_total_records_pulled)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "records synced / second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flow_worker_${job_type}_${job_name}_records_synced_per_second",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "overall mirror throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "flow_worker_${job_type}_${job_name}_records_throughput",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "records normalized / second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "flow_worker_${job_type}_${job_name}_records_normalized_per_second",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "records pulled / second with types",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "flow_worker_${job_type}_${job_name}_insert_records_pulled",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "flow_worker_${job_type}_${job_name}_update_records_pulled",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "flow_worker_${job_type}_${job_name}_delete_records_pulled",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "flow_worker_${job_type}_${job_name}_total_records_pulled",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}