CREATE TABLE IF NOT EXISTS peerdb_stats.alerting_config (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_type TEXT NOT NULL CHECK (service_type IN ('slack')),
    service_config JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS peerdb_stats.alerts_v1 (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    alert_key TEXT NOT NULL,
    alert_level TEXT NOT NULL CHECK (alert_level IN ('critical')) DEFAULT 'critical',
    alert_message TEXT NOT NULL,
    created_timestamp TIMESTAMP DEFAULT now()
);