--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: peerdb_stats; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA peerdb_stats;


--
-- Name: script_lang; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.script_lang AS ENUM (
    'lua'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alerting_config; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.alerting_config (
    id bigint NOT NULL,
    service_type text NOT NULL,
    service_config jsonb NOT NULL,
    CONSTRAINT alerting_config_service_type_check CHECK ((service_type = ANY (ARRAY['slack'::text, 'email'::text])))
);


--
-- Name: alerting_config_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.alerting_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME peerdb_stats.alerting_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alerts_v1; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.alerts_v1 (
    id bigint NOT NULL,
    alert_key text NOT NULL,
    alert_level text DEFAULT 'critical'::text NOT NULL,
    alert_message text NOT NULL,
    created_timestamp timestamp without time zone DEFAULT now(),
    alert_config_id bigint,
    CONSTRAINT alerts_v1_alert_level_check CHECK ((alert_level = 'critical'::text))
);


--
-- Name: alerts_v1_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.alerts_v1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME peerdb_stats.alerts_v1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cdc_batch_table; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.cdc_batch_table (
    flow_name text NOT NULL,
    batch_id bigint NOT NULL,
    destination_table_name text NOT NULL,
    num_rows bigint NOT NULL,
    metadata jsonb,
    id integer NOT NULL,
    insert_count integer,
    update_count integer,
    delete_count integer
);


--
-- Name: cdc_batch_table_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.cdc_batch_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cdc_batch_table_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.cdc_batch_table_id_seq OWNED BY peerdb_stats.cdc_batch_table.id;


--
-- Name: cdc_batches; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.cdc_batches (
    flow_name text NOT NULL,
    batch_id bigint NOT NULL,
    rows_in_batch integer NOT NULL,
    batch_start_lsn numeric NOT NULL,
    batch_end_lsn numeric NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    metadata jsonb,
    id integer NOT NULL
);


--
-- Name: cdc_batches_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.cdc_batches_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cdc_batches_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.cdc_batches_id_seq OWNED BY peerdb_stats.cdc_batches.id;


--
-- Name: cdc_flows; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.cdc_flows (
    flow_name text NOT NULL,
    latest_lsn_at_source numeric NOT NULL,
    latest_lsn_at_target numeric NOT NULL,
    metadata jsonb
);


--
-- Name: flow_errors; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.flow_errors (
    id bigint NOT NULL,
    flow_name text NOT NULL,
    error_message text NOT NULL,
    error_type text NOT NULL,
    error_timestamp timestamp without time zone DEFAULT now() NOT NULL,
    ack boolean DEFAULT false NOT NULL
);


--
-- Name: flow_errors_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.flow_errors ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME peerdb_stats.flow_errors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: peer_slot_size; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.peer_slot_size (
    id integer NOT NULL,
    slot_name text NOT NULL,
    peer_name text NOT NULL,
    redo_lsn text,
    restart_lsn text,
    confirmed_flush_lsn text,
    slot_size bigint,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    wal_status text
);


--
-- Name: peer_slot_size_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.peer_slot_size_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: peer_slot_size_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.peer_slot_size_id_seq OWNED BY peerdb_stats.peer_slot_size.id;


--
-- Name: qrep_partitions; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.qrep_partitions (
    flow_name text NOT NULL,
    run_uuid text NOT NULL,
    partition_uuid text NOT NULL,
    partition_start text NOT NULL,
    partition_end text NOT NULL,
    rows_in_partition integer,
    start_time timestamp without time zone,
    pull_end_time timestamp without time zone,
    end_time timestamp without time zone,
    restart_count integer NOT NULL,
    metadata jsonb,
    id integer NOT NULL,
    rows_synced bigint
);


--
-- Name: qrep_partitions_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.qrep_partitions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: qrep_partitions_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.qrep_partitions_id_seq OWNED BY peerdb_stats.qrep_partitions.id;


--
-- Name: qrep_runs; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.qrep_runs (
    flow_name text NOT NULL,
    run_uuid text NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    metadata jsonb,
    config_proto bytea,
    id integer NOT NULL,
    destination_table text,
    source_table text,
    fetch_complete boolean DEFAULT false,
    consolidate_complete boolean DEFAULT false
);


--
-- Name: qrep_runs_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.qrep_runs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: qrep_runs_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.qrep_runs_id_seq OWNED BY peerdb_stats.qrep_runs.id;


--
-- Name: schema_deltas_audit_log; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.schema_deltas_audit_log (
    id bigint NOT NULL,
    flow_job_name text NOT NULL,
    read_timestamp timestamp without time zone DEFAULT now(),
    workflow_id text NOT NULL,
    run_id text NOT NULL,
    delta_info jsonb NOT NULL
);


--
-- Name: schema_deltas_audit_log_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.schema_deltas_audit_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME peerdb_stats.schema_deltas_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alerting_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alerting_settings (
    id integer NOT NULL,
    config_name text NOT NULL,
    config_value text NOT NULL
);


--
-- Name: alerting_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.alerting_settings ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.alerting_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ch_s3_stage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ch_s3_stage (
    id integer NOT NULL,
    flow_job_name text NOT NULL,
    sync_batch_id bigint NOT NULL,
    avro_file jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ch_s3_stage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ch_s3_stage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ch_s3_stage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ch_s3_stage_id_seq OWNED BY public.ch_s3_stage.id;


--
-- Name: flows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flows (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    source_peer integer NOT NULL,
    destination_peer integer NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    source_table_identifier text,
    destination_table_identifier text,
    workflow_id text,
    flow_status text,
    flow_metadata jsonb,
    query_string text,
    config_proto bytea
);


--
-- Name: flows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.flows_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: flows_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.flows_id_seq OWNED BY public.flows.id;


--
-- Name: metadata_last_sync_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metadata_last_sync_state (
    job_name text NOT NULL,
    last_offset bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    sync_batch_id bigint NOT NULL,
    normalize_batch_id bigint
);


--
-- Name: metadata_qrep_partitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metadata_qrep_partitions (
    job_name text NOT NULL,
    partition_id text NOT NULL,
    sync_partition json NOT NULL,
    sync_start_time timestamp with time zone NOT NULL,
    sync_finish_time timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: peer_connections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peer_connections (
    id integer NOT NULL,
    conn_uuid uuid,
    peer_name text NOT NULL,
    query text,
    opened_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone
);


--
-- Name: peer_connections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.peer_connections_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: peer_connections_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.peer_connections_id_seq OWNED BY public.peer_connections.id;


--
-- Name: peers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peers (
    id integer NOT NULL,
    name text NOT NULL,
    type integer NOT NULL,
    options bytea NOT NULL
);


--
-- Name: peers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.peers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: peers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.peers_id_seq OWNED BY public.peers.id;


--
-- Name: refinery_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refinery_schema_history (
    version integer NOT NULL,
    name character varying(255),
    applied_on character varying(255),
    checksum character varying(255)
);


--
-- Name: scripts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scripts (
    id integer NOT NULL,
    lang public.script_lang NOT NULL,
    name text NOT NULL,
    source bytea NOT NULL
);


--
-- Name: scripts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.scripts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: scripts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.scripts_id_seq OWNED BY public.scripts.id;


--
-- Name: cdc_batch_table id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batch_table ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.cdc_batch_table_id_seq'::regclass);


--
-- Name: cdc_batches id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batches ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.cdc_batches_id_seq'::regclass);


--
-- Name: peer_slot_size id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.peer_slot_size ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.peer_slot_size_id_seq'::regclass);


--
-- Name: qrep_partitions id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.qrep_partitions_id_seq'::regclass);


--
-- Name: qrep_runs id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_runs ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.qrep_runs_id_seq'::regclass);


--
-- Name: ch_s3_stage id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ch_s3_stage ALTER COLUMN id SET DEFAULT nextval('public.ch_s3_stage_id_seq'::regclass);


--
-- Name: flows id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows ALTER COLUMN id SET DEFAULT nextval('public.flows_id_seq'::regclass);


--
-- Name: peer_connections id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_connections ALTER COLUMN id SET DEFAULT nextval('public.peer_connections_id_seq'::regclass);


--
-- Name: peers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers ALTER COLUMN id SET DEFAULT nextval('public.peers_id_seq'::regclass);


--
-- Name: scripts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scripts ALTER COLUMN id SET DEFAULT nextval('public.scripts_id_seq'::regclass);


--
-- Data for Name: alerting_config; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: alerts_v1; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: cdc_batch_table; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: cdc_batches; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: cdc_flows; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: flow_errors; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: peer_slot_size; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: qrep_partitions; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: qrep_runs; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: schema_deltas_audit_log; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: alerting_settings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: ch_s3_stage; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: flows; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: metadata_last_sync_state; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: metadata_qrep_partitions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: peer_connections; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: peers; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: refinery_schema_history; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.refinery_schema_history VALUES (1, 'initial', '2026-09-19T03:54:16.789274Z', '317466231964947673');
INSERT INTO public.refinery_schema_history VALUES (2, 'peer_connections', '2026-09-19T03:54:16.797441Z', '9510416485190653187');
INSERT INTO public.refinery_schema_history VALUES (3, 'add_workflow_id_to_flows', '2026-09-19T03:54:16.800901Z', '9526738116552750384');
INSERT INTO public.refinery_schema_history VALUES (4, 'add_query_string_to_flows', '2026-09-19T03:54:16.802229Z', '1571797677579114495');
INSERT INTO public.refinery_schema_history VALUES (5, 'monitoring_init', '2026-09-19T03:54:16.803317Z', '17147852651748911186');
INSERT INTO public.refinery_schema_history VALUES (6, 'monitoring_refine_1', '2026-09-19T03:54:16.80948Z', '12733216586154322753');
INSERT INTO public.refinery_schema_history VALUES (7, 'store_flow_config', '2026-09-19T03:54:16.811918Z', '3841591031556082634');
INSERT INTO public.refinery_schema_history VALUES (8, 'qrep_runs_config', '2026-09-19T03:54:16.813072Z', '5927494245025043350');
INSERT INTO public.refinery_schema_history VALUES (9, 'mirror_stats_rels', '2026-09-19T03:54:16.814172Z', '13000952657914098367');
INSERT INTO public.refinery_schema_history VALUES (10, 'mirror_drop_bad_constraints', '2026-09-19T03:54:16.83105Z', '3630930488426919111');
INSERT INTO public.refinery_schema_history VALUES (11, 'qrep_runs_start_time_nullable', '2026-09-19T03:54:16.834041Z', '11255414106938188277');
INSERT INTO public.refinery_schema_history VALUES (12, 'slot_size', '2026-09-19T03:54:16.835317Z', '8739771444349636273');
INSERT INTO public.refinery_schema_history VALUES (13, 'wal_status', '2026-09-19T03:54:16.837716Z', '2875942383793936038');
INSERT INTO public.refinery_schema_history VALUES (14, 'qrep_rows_synced', '2026-09-19T03:54:16.838666Z', '4026054801065481486');
INSERT INTO public.refinery_schema_history VALUES (15, 'schema_deltas_audit_log', '2026-09-19T03:54:16.839901Z', '12517139953083567662');
INSERT INTO public.refinery_schema_history VALUES (16, 'alerting_config_init', '2026-09-19T03:54:16.842314Z', '6398415499274181706');
INSERT INTO public.refinery_schema_history VALUES (17, 'mirror_errors', '2026-09-19T03:54:16.845854Z', '11991210397828356650');
INSERT INTO public.refinery_schema_history VALUES (18, 'alerting_config', '2026-09-19T03:54:16.848302Z', '4988073000243152825');
INSERT INTO public.refinery_schema_history VALUES (19, 'metadata', '2026-09-19T03:54:16.850491Z', '89813014211755958');
INSERT INTO public.refinery_schema_history VALUES (20, 'slot_updated_at', '2026-09-19T03:54:16.853783Z', '10355115740518284288');
INSERT INTO public.refinery_schema_history VALUES (21, 'alert_constraint_update', '2026-09-19T03:54:16.854839Z', '13363861936102858799');
INSERT INTO public.refinery_schema_history VALUES (22, 'alert_column_add_config_id', '2026-09-19T03:54:16.855855Z', '4659718188229983732');
INSERT INTO public.refinery_schema_history VALUES (23, 'scripts', '2026-09-19T03:54:16.856949Z', '6784575351368366998');
INSERT INTO public.refinery_schema_history VALUES (24, 'qrep_runs_destination', '2026-09-19T03:54:16.859425Z', '12104297750535716767');
INSERT INTO public.refinery_schema_history VALUES (25, 'recordtypecounts', '2026-09-19T03:54:16.860654Z', '4110056849956132365');
INSERT INTO public.refinery_schema_history VALUES (26, 'qrep_parts_bigint_rows_synced', '2026-09-19T03:54:16.861774Z', '3701185371960680588');
INSERT INTO public.refinery_schema_history VALUES (27, 'ch_s3_stage', '2026-09-19T03:54:16.864694Z', '11546309230777725569');
INSERT INTO public.refinery_schema_history VALUES (28, 'ch_s3_stage_unique_constraint', '2026-09-19T03:54:16.867256Z', '13285355265084632949');


--
-- Data for Name: scripts; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: alerting_config_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.alerting_config_id_seq', 1, false);


--
-- Name: alerts_v1_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.alerts_v1_id_seq', 1, false);


--
-- Name: cdc_batch_table_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.cdc_batch_table_id_seq', 1, false);


--
-- Name: cdc_batches_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.cdc_batches_id_seq', 1, false);


--
-- Name: flow_errors_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.flow_errors_id_seq', 1, false);


--
-- Name: peer_slot_size_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.peer_slot_size_id_seq', 1, false);


--
-- Name: qrep_partitions_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.qrep_partitions_id_seq', 1, false);


--
-- Name: qrep_runs_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.qrep_runs_id_seq', 1, false);


--
-- Name: schema_deltas_audit_log_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.schema_deltas_audit_log_id_seq', 1, false);


--
-- Name: alerting_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.alerting_settings_id_seq', 1, false);


--
-- Name: ch_s3_stage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ch_s3_stage_id_seq', 1, false);


--
-- Name: flows_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.flows_id_seq', 1, false);


--
-- Name: peer_connections_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.peer_connections_id_seq', 1, false);


--
-- Name: peers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.peers_id_seq', 1, false);


--
-- Name: scripts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.scripts_id_seq', 1, false);


--
-- Name: alerting_config alerting_config_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.alerting_config
    ADD CONSTRAINT alerting_config_pkey PRIMARY KEY (id);


--
-- Name: alerts_v1 alerts_v1_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.alerts_v1
    ADD CONSTRAINT alerts_v1_pkey PRIMARY KEY (id);


--
-- Name: cdc_batch_table cdc_batch_table_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batch_table
    ADD CONSTRAINT cdc_batch_table_pkey PRIMARY KEY (id);


--
-- Name: cdc_batches cdc_batches_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batches
    ADD CONSTRAINT cdc_batches_pkey PRIMARY KEY (id);


--
-- Name: cdc_flows cdc_flows_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_flows
    ADD CONSTRAINT cdc_flows_pkey PRIMARY KEY (flow_name);


--
-- Name: flow_errors flow_errors_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.flow_errors
    ADD CONSTRAINT flow_errors_pkey PRIMARY KEY (id);


--
-- Name: peer_slot_size peer_slot_size_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.peer_slot_size
    ADD CONSTRAINT peer_slot_size_pkey PRIMARY KEY (id);


--
-- Name: qrep_partitions qrep_partitions_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions
    ADD CONSTRAINT qrep_partitions_pkey PRIMARY KEY (id);


--
-- Name: qrep_partitions qrep_partitions_run_uuid_partition_uuid_key; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions
    ADD CONSTRAINT qrep_partitions_run_uuid_partition_uuid_key UNIQUE (run_uuid, partition_uuid);


--
-- Name: qrep_runs qrep_runs_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_runs
    ADD CONSTRAINT qrep_runs_pkey PRIMARY KEY (id);


--
-- Name: schema_deltas_audit_log schema_deltas_audit_log_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.schema_deltas_audit_log
    ADD CONSTRAINT schema_deltas_audit_log_pkey PRIMARY KEY (id);


--
-- Name: qrep_runs uq_qrep_runs_flow_run; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_runs
    ADD CONSTRAINT uq_qrep_runs_flow_run UNIQUE (flow_name, run_uuid);


--
-- Name: alerting_settings alerting_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alerting_settings
    ADD CONSTRAINT alerting_settings_pkey PRIMARY KEY (id);


--
-- Name: ch_s3_stage ch_s3_stage_flow_job_name_sync_batch_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ch_s3_stage
    ADD CONSTRAINT ch_s3_stage_flow_job_name_sync_batch_id_key UNIQUE (flow_job_name, sync_batch_id);


--
-- Name: ch_s3_stage ch_s3_stage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ch_s3_stage
    ADD CONSTRAINT ch_s3_stage_pkey PRIMARY KEY (id);


--
-- Name: flows flows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_pkey PRIMARY KEY (id);


--
-- Name: metadata_last_sync_state metadata_last_sync_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata_last_sync_state
    ADD CONSTRAINT metadata_last_sync_state_pkey PRIMARY KEY (job_name);


--
-- Name: metadata_qrep_partitions metadata_qrep_partitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata_qrep_partitions
    ADD CONSTRAINT metadata_qrep_partitions_pkey PRIMARY KEY (job_name, partition_id);


--
-- Name: peer_connections peer_connections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_connections
    ADD CONSTRAINT peer_connections_pkey PRIMARY KEY (id);


--
-- Name: peers peers_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers
    ADD CONSTRAINT peers_name_key UNIQUE (name);


--
-- Name: peers peers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers
    ADD CONSTRAINT peers_pkey PRIMARY KEY (id);


--
-- Name: refinery_schema_history refinery_schema_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refinery_schema_history
    ADD CONSTRAINT refinery_schema_history_pkey PRIMARY KEY (version);


--
-- Name: scripts scripts_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scripts
    ADD CONSTRAINT scripts_name_key UNIQUE (name);


--
-- Name: scripts scripts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scripts
    ADD CONSTRAINT scripts_pkey PRIMARY KEY (id);


--
-- Name: idx_cdc_batch_table_flow_name_batch_id; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batch_table_flow_name_batch_id ON peerdb_stats.cdc_batch_table USING btree (flow_name, batch_id);


--
-- Name: idx_cdc_batches_batch_id; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batches_batch_id ON peerdb_stats.cdc_batches USING btree (batch_id);


--
-- Name: idx_cdc_batches_flow_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batches_flow_name ON peerdb_stats.cdc_batches USING hash (flow_name);


--
-- Name: idx_cdc_batches_start_time; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batches_start_time ON peerdb_stats.cdc_batches USING btree (start_time);


--
-- Name: idx_flow_errors_flow_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_flow_errors_flow_name ON peerdb_stats.flow_errors USING btree (flow_name);


--
-- Name: idx_qrep_partitions_flow_name_run_uuid; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_partitions_flow_name_run_uuid ON peerdb_stats.qrep_partitions USING btree (flow_name, run_uuid);


--
-- Name: idx_qrep_partitions_partition_uuid; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_partitions_partition_uuid ON peerdb_stats.qrep_partitions USING hash (partition_uuid);


--
-- Name: idx_qrep_partitions_start_time; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_partitions_start_time ON peerdb_stats.qrep_partitions USING btree (start_time);


--
-- Name: idx_qrep_runs_flow_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_runs_flow_name ON peerdb_stats.qrep_runs USING hash (flow_name);


--
-- Name: idx_qrep_runs_run_uuid; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_runs_run_uuid ON peerdb_stats.qrep_runs USING hash (run_uuid);


--
-- Name: idx_qrep_runs_start_time; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_runs_start_time ON peerdb_stats.qrep_runs USING btree (start_time);


--
-- Name: index_slot_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX index_slot_name ON peerdb_stats.peer_slot_size USING btree (slot_name);


--
-- Name: index_slot_updated_at; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX index_slot_updated_at ON peerdb_stats.peer_slot_size USING btree (updated_at);


--
-- Name: ch_s3_stage_flow_job_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ch_s3_stage_flow_job_name_idx ON public.ch_s3_stage USING btree (flow_job_name);


--
-- Name: ch_s3_stage_sync_batch_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ch_s3_stage_sync_batch_id_idx ON public.ch_s3_stage USING btree (sync_batch_id);


--
-- Name: idx_alerting_settings_config_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_alerting_settings_config_name ON public.alerting_settings USING btree (config_name);


--
-- Name: cdc_batch_table fk_cdc_batch_table_flow_name; Type: FK CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batch_table
    ADD CONSTRAINT fk_cdc_batch_table_flow_name FOREIGN KEY (flow_name) REFERENCES peerdb_stats.cdc_flows(flow_name) ON DELETE CASCADE;


--
-- Name: cdc_batches fk_cdc_batches_flow_name; Type: FK CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batches
    ADD CONSTRAINT fk_cdc_batches_flow_name FOREIGN KEY (flow_name) REFERENCES peerdb_stats.cdc_flows(flow_name) ON DELETE CASCADE;


--
-- Name: qrep_partitions fk_qrep_partitions_run; Type: FK CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions
    ADD CONSTRAINT fk_qrep_partitions_run FOREIGN KEY (flow_name, run_uuid) REFERENCES peerdb_stats.qrep_runs(flow_name, run_uuid) ON DELETE CASCADE;


--
-- Name: flows flows_destination_peer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_destination_peer_fkey FOREIGN KEY (destination_peer) REFERENCES public.peers(id);


--
-- Name: flows flows_source_peer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_source_peer_fkey FOREIGN KEY (source_peer) REFERENCES public.peers(id);


--
-- Name: peer_connections peer_connections_peer_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_connections
    ADD CONSTRAINT peer_connections_peer_name_fkey FOREIGN KEY (peer_name) REFERENCES public.peers(name);


--
-- PostgreSQL database dump complete
--


