--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: maintenance; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA maintenance;


--
-- Name: peerdb_stats; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA peerdb_stats;


--
-- Name: script_lang; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.script_lang AS ENUM (
    'lua'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: maintenance_flows; Type: TABLE; Schema: maintenance; Owner: -
--

CREATE TABLE maintenance.maintenance_flows (
    id integer NOT NULL,
    flow_id bigint NOT NULL,
    flow_name text NOT NULL,
    workflow_id text NOT NULL,
    flow_created_at timestamp without time zone NOT NULL,
    is_cdc boolean NOT NULL,
    state text NOT NULL,
    restored_at timestamp without time zone,
    from_version text,
    to_version text
);


--
-- Name: maintenance_flows_id_seq; Type: SEQUENCE; Schema: maintenance; Owner: -
--

CREATE SEQUENCE maintenance.maintenance_flows_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: maintenance_flows_id_seq; Type: SEQUENCE OWNED BY; Schema: maintenance; Owner: -
--

ALTER SEQUENCE maintenance.maintenance_flows_id_seq OWNED BY maintenance.maintenance_flows.id;


--
-- Name: start_maintenance_outputs; Type: TABLE; Schema: maintenance; Owner: -
--

CREATE TABLE maintenance.start_maintenance_outputs (
    id integer NOT NULL,
    api_version text NOT NULL,
    cli_version text NOT NULL,
    skipped boolean NOT NULL,
    skipped_reason text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    api_deploy_version text DEFAULT ''::text NOT NULL,
    cli_deploy_version text DEFAULT ''::text NOT NULL
);


--
-- Name: start_maintenance_outputs_id_seq; Type: SEQUENCE; Schema: maintenance; Owner: -
--

CREATE SEQUENCE maintenance.start_maintenance_outputs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: start_maintenance_outputs_id_seq; Type: SEQUENCE OWNED BY; Schema: maintenance; Owner: -
--

ALTER SEQUENCE maintenance.start_maintenance_outputs_id_seq OWNED BY maintenance.start_maintenance_outputs.id;


--
-- Name: alerting_config; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.alerting_config (
    id bigint NOT NULL,
    service_type text NOT NULL,
    service_config bytea NOT NULL,
    enc_key_id text DEFAULT ''::text NOT NULL,
    alert_for_mirrors text[],
    CONSTRAINT alerting_config_service_type_check CHECK ((service_type = ANY (ARRAY['slack'::text, 'email'::text])))
);


--
-- Name: alerting_config_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.alerting_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME peerdb_stats.alerting_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alerts_v1; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.alerts_v1 (
    id bigint NOT NULL,
    alert_key text NOT NULL,
    alert_level text DEFAULT 'critical'::text NOT NULL,
    alert_message text NOT NULL,
    created_timestamp timestamp without time zone DEFAULT now(),
    alert_config_id bigint,
    CONSTRAINT alerts_v1_alert_level_check CHECK ((alert_level = 'critical'::text))
);


--
-- Name: alerts_v1_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.alerts_v1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME peerdb_stats.alerts_v1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cdc_batches; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.cdc_batches (
    flow_name text NOT NULL,
    batch_id bigint NOT NULL,
    rows_in_batch bigint NOT NULL,
    batch_start_lsn numeric NOT NULL,
    batch_end_lsn numeric NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    metadata jsonb,
    id integer NOT NULL,
    batch_end_lsn_text text DEFAULT ''::text NOT NULL,
    sync_time timestamp without time zone,
    first_row_received_at timestamp without time zone,
    first_row_commit_time timestamp without time zone
);


--
-- Name: COLUMN cdc_batches.sync_time; Type: COMMENT; Schema: peerdb_stats; Owner: -
--

COMMENT ON COLUMN peerdb_stats.cdc_batches.sync_time IS 'Set via PG NOW() for clock-skew-safe lag calculation';


--
-- Name: COLUMN cdc_batches.first_row_received_at; Type: COMMENT; Schema: peerdb_stats; Owner: -
--

COMMENT ON COLUMN peerdb_stats.cdc_batches.first_row_received_at IS 'Wall-clock time (UTC) when PeerDB received the first row event of the batch; used for destination lag';


--
-- Name: COLUMN cdc_batches.first_row_commit_time; Type: COMMENT; Schema: peerdb_stats; Owner: -
--

COMMENT ON COLUMN peerdb_stats.cdc_batches.first_row_commit_time IS 'Commit time (UTC) of the first row event of the batch, shifted into the worker clock frame (source commit minus source/worker clock offset); used for skew-corrected end-to-end lag';


--
-- Name: cdc_batches_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.cdc_batches_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cdc_batches_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.cdc_batches_id_seq OWNED BY peerdb_stats.cdc_batches.id;


--
-- Name: cdc_flows; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.cdc_flows (
    flow_name text NOT NULL,
    latest_lsn_at_source numeric NOT NULL,
    latest_lsn_at_target numeric NOT NULL,
    metadata jsonb
);


--
-- Name: cdc_table_aggregate_counts; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.cdc_table_aggregate_counts (
    flow_name text NOT NULL,
    destination_table_name text NOT NULL,
    inserts_count bigint DEFAULT 0 NOT NULL,
    updates_count bigint DEFAULT 0 NOT NULL,
    deletes_count bigint DEFAULT 0 NOT NULL,
    total_count bigint DEFAULT 0 NOT NULL,
    latest_batch_id bigint DEFAULT 0 NOT NULL,
    last_updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE cdc_table_aggregate_counts; Type: COMMENT; Schema: peerdb_stats; Owner: -
--

COMMENT ON TABLE peerdb_stats.cdc_table_aggregate_counts IS 'Stores pre-aggregated counts of CDC operations by flow and table to optimize query performance.';


--
-- Name: flow_errors; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.flow_errors (
    id bigint NOT NULL,
    flow_name text NOT NULL,
    error_message text NOT NULL,
    error_type text NOT NULL,
    error_timestamp timestamp without time zone DEFAULT now() NOT NULL,
    ack boolean DEFAULT false NOT NULL
);


--
-- Name: flow_errors_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.flow_errors ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME peerdb_stats.flow_errors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: peer_slot_size; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.peer_slot_size (
    id integer NOT NULL,
    slot_name text NOT NULL,
    peer_name text NOT NULL,
    redo_lsn text,
    restart_lsn text,
    confirmed_flush_lsn text,
    slot_size bigint,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    wal_status text
);


--
-- Name: peer_slot_size_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.peer_slot_size_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: peer_slot_size_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.peer_slot_size_id_seq OWNED BY peerdb_stats.peer_slot_size.id;


--
-- Name: qrep_partitions; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.qrep_partitions (
    flow_name text NOT NULL,
    run_uuid text NOT NULL,
    partition_uuid text NOT NULL,
    partition_start text,
    partition_end text,
    rows_in_partition bigint,
    start_time timestamp without time zone,
    pull_end_time timestamp without time zone,
    end_time timestamp without time zone,
    restart_count integer NOT NULL,
    metadata jsonb,
    id integer NOT NULL,
    rows_synced bigint,
    parent_mirror_name text,
    child_table_ranges jsonb
);


--
-- Name: qrep_partitions_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.qrep_partitions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: qrep_partitions_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.qrep_partitions_id_seq OWNED BY peerdb_stats.qrep_partitions.id;


--
-- Name: qrep_runs; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.qrep_runs (
    flow_name text NOT NULL,
    run_uuid text NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    metadata jsonb,
    id integer NOT NULL,
    destination_table text,
    source_table text,
    fetch_complete boolean DEFAULT false,
    consolidate_complete boolean DEFAULT false,
    parent_mirror_name text,
    failed boolean DEFAULT false NOT NULL
);


--
-- Name: qrep_runs_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

CREATE SEQUENCE peerdb_stats.qrep_runs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: qrep_runs_id_seq; Type: SEQUENCE OWNED BY; Schema: peerdb_stats; Owner: -
--

ALTER SEQUENCE peerdb_stats.qrep_runs_id_seq OWNED BY peerdb_stats.qrep_runs.id;


--
-- Name: schema_deltas_audit_log; Type: TABLE; Schema: peerdb_stats; Owner: -
--

CREATE TABLE peerdb_stats.schema_deltas_audit_log (
    id bigint NOT NULL,
    flow_job_name text NOT NULL,
    read_timestamp timestamp without time zone DEFAULT now(),
    workflow_id text NOT NULL,
    run_id text NOT NULL,
    delta_info jsonb NOT NULL
);


--
-- Name: schema_deltas_audit_log_id_seq; Type: SEQUENCE; Schema: peerdb_stats; Owner: -
--

ALTER TABLE peerdb_stats.schema_deltas_audit_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME peerdb_stats.schema_deltas_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dynamic_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dynamic_settings (
    id integer CONSTRAINT alerting_settings_id_not_null NOT NULL,
    config_name text CONSTRAINT alerting_settings_config_name_not_null NOT NULL,
    config_value text NOT NULL
);


--
-- Name: alerting_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dynamic_settings ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.alerting_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ch_s3_stage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ch_s3_stage (
    id integer NOT NULL,
    flow_job_name text NOT NULL,
    sync_batch_id bigint NOT NULL,
    avro_file jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ch_s3_stage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ch_s3_stage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ch_s3_stage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ch_s3_stage_id_seq OWNED BY public.ch_s3_stage.id;


--
-- Name: flow_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flow_migrations (
    flow_name text NOT NULL,
    migration_name text NOT NULL,
    completed boolean NOT NULL
);


--
-- Name: flows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flows (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    source_peer integer NOT NULL,
    destination_peer integer NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    source_table_identifier text,
    destination_table_identifier text,
    workflow_id text,
    flow_status text,
    flow_metadata jsonb,
    query_string text,
    config_proto bytea,
    tags jsonb,
    status integer DEFAULT 0 NOT NULL
);


--
-- Name: flows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.flows_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: flows_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.flows_id_seq OWNED BY public.flows.id;


--
-- Name: metadata_last_sync_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metadata_last_sync_state (
    job_name text NOT NULL,
    last_offset bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    sync_batch_id bigint NOT NULL,
    normalize_batch_id bigint,
    last_text text DEFAULT ''::text NOT NULL,
    latest_batch_id_in_raw_table bigint,
    table_batch_id_data jsonb DEFAULT '{}'::jsonb
);


--
-- Name: metadata_qrep_offloaded_partition_ranges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metadata_qrep_offloaded_partition_ranges (
    parent_mirror_name text CONSTRAINT metadata_qrep_offloaded_partition_r_parent_mirror_name_not_null NOT NULL,
    run_uuid text NOT NULL,
    partition_uuid text CONSTRAINT metadata_qrep_offloaded_partition_range_partition_uuid_not_null NOT NULL,
    enc_key_id text NOT NULL,
    range_payload bytea NOT NULL,
    inserted_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: metadata_qrep_partitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metadata_qrep_partitions (
    job_name text NOT NULL,
    partition_id text NOT NULL,
    sync_partition json NOT NULL,
    sync_start_time timestamp with time zone NOT NULL,
    sync_finish_time timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: peer_connections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peer_connections (
    id integer NOT NULL,
    conn_uuid uuid,
    peer_name text NOT NULL,
    query text,
    opened_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone
);


--
-- Name: peer_connections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.peer_connections_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: peer_connections_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.peer_connections_id_seq OWNED BY public.peer_connections.id;


--
-- Name: peers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peers (
    id integer NOT NULL,
    name text NOT NULL,
    type integer NOT NULL,
    options bytea NOT NULL,
    enc_key_id text DEFAULT ''::text NOT NULL
);


--
-- Name: peers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.peers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: peers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.peers_id_seq OWNED BY public.peers.id;


--
-- Name: query_cdc_avro_stage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.query_cdc_avro_stage (
    flow_name text NOT NULL,
    source_table_identifier text NOT NULL,
    batch_id bigint NOT NULL,
    avro_file jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    inserts_count bigint DEFAULT 0 NOT NULL,
    updates_count bigint DEFAULT 0 NOT NULL,
    deletes_count bigint DEFAULT 0 NOT NULL
);


--
-- Name: query_cdc_replication_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.query_cdc_replication_state (
    flow_name text NOT NULL,
    source_table_identifier text NOT NULL,
    cursor_text text DEFAULT ''::text NOT NULL,
    last_attempt_at timestamp with time zone,
    last_synced_at timestamp with time zone,
    synced_batch_id bigint DEFAULT 0 NOT NULL,
    normalized_batch_id bigint DEFAULT 0 NOT NULL,
    last_normalized_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    inserts_count bigint DEFAULT 0 NOT NULL,
    updates_count bigint DEFAULT 0 NOT NULL,
    deletes_count bigint DEFAULT 0 NOT NULL
);


--
-- Name: refinery_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refinery_schema_history (
    version integer NOT NULL,
    name character varying(255),
    applied_on character varying(255),
    checksum character varying(255)
);


--
-- Name: scripts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scripts (
    id integer NOT NULL,
    lang public.script_lang NOT NULL,
    name text NOT NULL,
    source bytea NOT NULL
);


--
-- Name: scripts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.scripts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: scripts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.scripts_id_seq OWNED BY public.scripts.id;


--
-- Name: table_schema_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.table_schema_mapping (
    flow_name character varying(255) NOT NULL,
    table_name text NOT NULL,
    table_schema bytea NOT NULL
);


--
-- Name: maintenance_flows id; Type: DEFAULT; Schema: maintenance; Owner: -
--

ALTER TABLE ONLY maintenance.maintenance_flows ALTER COLUMN id SET DEFAULT nextval('maintenance.maintenance_flows_id_seq'::regclass);


--
-- Name: start_maintenance_outputs id; Type: DEFAULT; Schema: maintenance; Owner: -
--

ALTER TABLE ONLY maintenance.start_maintenance_outputs ALTER COLUMN id SET DEFAULT nextval('maintenance.start_maintenance_outputs_id_seq'::regclass);


--
-- Name: cdc_batches id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batches ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.cdc_batches_id_seq'::regclass);


--
-- Name: peer_slot_size id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.peer_slot_size ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.peer_slot_size_id_seq'::regclass);


--
-- Name: qrep_partitions id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.qrep_partitions_id_seq'::regclass);


--
-- Name: qrep_runs id; Type: DEFAULT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_runs ALTER COLUMN id SET DEFAULT nextval('peerdb_stats.qrep_runs_id_seq'::regclass);


--
-- Name: ch_s3_stage id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ch_s3_stage ALTER COLUMN id SET DEFAULT nextval('public.ch_s3_stage_id_seq'::regclass);


--
-- Name: flows id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows ALTER COLUMN id SET DEFAULT nextval('public.flows_id_seq'::regclass);


--
-- Name: peer_connections id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_connections ALTER COLUMN id SET DEFAULT nextval('public.peer_connections_id_seq'::regclass);


--
-- Name: peers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers ALTER COLUMN id SET DEFAULT nextval('public.peers_id_seq'::regclass);


--
-- Name: scripts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scripts ALTER COLUMN id SET DEFAULT nextval('public.scripts_id_seq'::regclass);


--
-- Data for Name: maintenance_flows; Type: TABLE DATA; Schema: maintenance; Owner: -
--



--
-- Data for Name: start_maintenance_outputs; Type: TABLE DATA; Schema: maintenance; Owner: -
--



--
-- Data for Name: alerting_config; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: alerts_v1; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: cdc_batches; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: cdc_flows; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: cdc_table_aggregate_counts; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: flow_errors; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: peer_slot_size; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: qrep_partitions; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: qrep_runs; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: schema_deltas_audit_log; Type: TABLE DATA; Schema: peerdb_stats; Owner: -
--



--
-- Data for Name: ch_s3_stage; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: dynamic_settings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: flow_migrations; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: flows; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: metadata_last_sync_state; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: metadata_qrep_offloaded_partition_ranges; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: metadata_qrep_partitions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: peer_connections; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: peers; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: query_cdc_avro_stage; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: query_cdc_replication_state; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: refinery_schema_history; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.refinery_schema_history VALUES (1, 'initial', '2026-09-19T03:54:17.167169Z', '317466231964947673');
INSERT INTO public.refinery_schema_history VALUES (2, 'peer_connections', '2026-09-19T03:54:17.172824Z', '9510416485190653187');
INSERT INTO public.refinery_schema_history VALUES (3, 'add_workflow_id_to_flows', '2026-09-19T03:54:17.175275Z', '9526738116552750384');
INSERT INTO public.refinery_schema_history VALUES (4, 'add_query_string_to_flows', '2026-09-19T03:54:17.17634Z', '1571797677579114495');
INSERT INTO public.refinery_schema_history VALUES (5, 'monitoring_init', '2026-09-19T03:54:17.177188Z', '17147852651748911186');
INSERT INTO public.refinery_schema_history VALUES (6, 'monitoring_refine_1', '2026-09-19T03:54:17.181734Z', '12733216586154322753');
INSERT INTO public.refinery_schema_history VALUES (7, 'store_flow_config', '2026-09-19T03:54:17.183546Z', '3841591031556082634');
INSERT INTO public.refinery_schema_history VALUES (8, 'qrep_runs_config', '2026-09-19T03:54:17.184408Z', '5927494245025043350');
INSERT INTO public.refinery_schema_history VALUES (9, 'mirror_stats_rels', '2026-09-19T03:54:17.185201Z', '13000952657914098367');
INSERT INTO public.refinery_schema_history VALUES (10, 'mirror_drop_bad_constraints', '2026-09-19T03:54:17.197875Z', '3630930488426919111');
INSERT INTO public.refinery_schema_history VALUES (11, 'qrep_runs_start_time_nullable', '2026-09-19T03:54:17.200357Z', '11255414106938188277');
INSERT INTO public.refinery_schema_history VALUES (12, 'slot_size', '2026-09-19T03:54:17.201444Z', '8739771444349636273');
INSERT INTO public.refinery_schema_history VALUES (13, 'wal_status', '2026-09-19T03:54:17.203528Z', '2875942383793936038');
INSERT INTO public.refinery_schema_history VALUES (14, 'qrep_rows_synced', '2026-09-19T03:54:17.204496Z', '4026054801065481486');
INSERT INTO public.refinery_schema_history VALUES (15, 'schema_deltas_audit_log', '2026-09-19T03:54:17.205339Z', '12517139953083567662');
INSERT INTO public.refinery_schema_history VALUES (16, 'alerting_config_init', '2026-09-19T03:54:17.207454Z', '6398415499274181706');
INSERT INTO public.refinery_schema_history VALUES (17, 'mirror_errors', '2026-09-19T03:54:17.2104Z', '11991210397828356650');
INSERT INTO public.refinery_schema_history VALUES (18, 'alerting_config', '2026-09-19T03:54:17.212556Z', '4988073000243152825');
INSERT INTO public.refinery_schema_history VALUES (19, 'metadata', '2026-09-19T03:54:17.214535Z', '89813014211755958');
INSERT INTO public.refinery_schema_history VALUES (20, 'slot_updated_at', '2026-09-19T03:54:17.217259Z', '10355115740518284288');
INSERT INTO public.refinery_schema_history VALUES (21, 'alert_constraint_update', '2026-09-19T03:54:17.218231Z', '13363861936102858799');
INSERT INTO public.refinery_schema_history VALUES (22, 'alert_column_add_config_id', '2026-09-19T03:54:17.220112Z', '4659718188229983732');
INSERT INTO public.refinery_schema_history VALUES (23, 'scripts', '2026-09-19T03:54:17.220912Z', '6784575351368366998');
INSERT INTO public.refinery_schema_history VALUES (24, 'qrep_runs_destination', '2026-09-19T03:54:17.223234Z', '12104297750535716767');
INSERT INTO public.refinery_schema_history VALUES (25, 'recordtypecounts', '2026-09-19T03:54:17.224598Z', '4110056849956132365');
INSERT INTO public.refinery_schema_history VALUES (26, 'qrep_parts_bigint_rows_synced', '2026-09-19T03:54:17.225495Z', '3701185371960680588');
INSERT INTO public.refinery_schema_history VALUES (27, 'ch_s3_stage', '2026-09-19T03:54:17.228335Z', '11546309230777725569');
INSERT INTO public.refinery_schema_history VALUES (28, 'ch_s3_stage_unique_constraint', '2026-09-19T03:54:17.230606Z', '13285355265084632949');
INSERT INTO public.refinery_schema_history VALUES (29, 'dynconf_table_and_settings', '2026-09-19T03:54:17.23186Z', '10279271054791807229');
INSERT INTO public.refinery_schema_history VALUES (30, 'more_dynconf_settings', '2026-09-19T03:54:17.233137Z', '16508133862251097848');
INSERT INTO public.refinery_schema_history VALUES (31, 'more_more_dynconf_settings', '2026-09-19T03:54:17.234099Z', '10294189175499319975');
INSERT INTO public.refinery_schema_history VALUES (32, 'remove_config_qrep_runs', '2026-09-19T03:54:17.234799Z', '4790385939442513290');
INSERT INTO public.refinery_schema_history VALUES (33, 'aes', '2026-09-19T03:54:17.235645Z', '6932842108824495476');
INSERT INTO public.refinery_schema_history VALUES (34, 'more_counts_bigint', '2026-09-19T03:54:17.236775Z', '6148723562768986672');
INSERT INTO public.refinery_schema_history VALUES (35, 'encrypt_alert_config', '2026-09-19T03:54:17.245157Z', '4467309223224532244');
INSERT INTO public.refinery_schema_history VALUES (36, 'reduce_dynamic_settings', '2026-09-19T03:54:17.247631Z', '9703400193673313997');
INSERT INTO public.refinery_schema_history VALUES (37, 'qrep_parent_mirror', '2026-09-19T03:54:17.248995Z', '7141442499055406040');
INSERT INTO public.refinery_schema_history VALUES (38, 'alerting_config_mirror_names', '2026-09-19T03:54:17.249901Z', '12183269910268654645');
INSERT INTO public.refinery_schema_history VALUES (39, 'table_schema_mapping', '2026-09-19T03:54:17.250667Z', '9905090251193754090');
INSERT INTO public.refinery_schema_history VALUES (40, 'maintenance_flows', '2026-09-19T03:54:17.252358Z', '8048367508522158641');
INSERT INTO public.refinery_schema_history VALUES (41, 'add_metadata_tags', '2026-09-19T03:54:17.255826Z', '9846506165717915461');
INSERT INTO public.refinery_schema_history VALUES (42, 'mysql_metadata', '2026-09-19T03:54:17.256634Z', '15275665903172057810');
INSERT INTO public.refinery_schema_history VALUES (43, 'cdc_table_aggregate_counts', '2026-09-19T03:54:17.257823Z', '12835042659460781513');
INSERT INTO public.refinery_schema_history VALUES (44, 'flow_status', '2026-09-19T03:54:17.260645Z', '8074017032514915470');
INSERT INTO public.refinery_schema_history VALUES (45, 'maintenance_deploy_version', '2026-09-19T03:54:17.261611Z', '14799696886102776752');
INSERT INTO public.refinery_schema_history VALUES (46, 'metadata_raw_table_column', '2026-09-19T03:54:17.26294Z', '11751639597227885747');
INSERT INTO public.refinery_schema_history VALUES (47, 'drop_cdc_batch_table', '2026-09-19T03:54:17.263855Z', '7226302546562324421');
INSERT INTO public.refinery_schema_history VALUES (48, 'unique_flows', '2026-09-19T03:54:17.265919Z', '15771532107609900280');
INSERT INTO public.refinery_schema_history VALUES (49, 'flow_migrations', '2026-09-19T03:54:17.267148Z', '2120414377077843584');
INSERT INTO public.refinery_schema_history VALUES (50, 'cdc_batches_sync_time', '2026-09-19T03:54:17.268749Z', '6659931673421132684');
INSERT INTO public.refinery_schema_history VALUES (51, 'qrep_partitions_nullable_range', '2026-09-19T03:54:17.269533Z', '16107541365351175131');
INSERT INTO public.refinery_schema_history VALUES (52, 'qrep_partitions_child_table_ranges', '2026-09-19T03:54:17.270531Z', '16014840694307388098');
INSERT INTO public.refinery_schema_history VALUES (53, 'cdc_batches_open_index', '2026-09-19T03:54:17.271271Z', '511141347195706818');
INSERT INTO public.refinery_schema_history VALUES (54, 'qrep_offloaded_partition_ranges', '2026-09-19T03:54:17.272246Z', '2716824217306229516');
INSERT INTO public.refinery_schema_history VALUES (55, 'cdc_batches_first_row_times', '2026-09-19T03:54:17.274094Z', '816690195298559525');
INSERT INTO public.refinery_schema_history VALUES (56, 'query_cdc_replication_state', '2026-09-19T03:54:17.274969Z', '14445442305554216490');
INSERT INTO public.refinery_schema_history VALUES (57, 'qrep_runs_failed', '2026-09-19T03:54:17.277965Z', '11029513540134340181');


--
-- Data for Name: scripts; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: table_schema_mapping; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: maintenance_flows_id_seq; Type: SEQUENCE SET; Schema: maintenance; Owner: -
--

SELECT pg_catalog.setval('maintenance.maintenance_flows_id_seq', 1, false);


--
-- Name: start_maintenance_outputs_id_seq; Type: SEQUENCE SET; Schema: maintenance; Owner: -
--

SELECT pg_catalog.setval('maintenance.start_maintenance_outputs_id_seq', 1, false);


--
-- Name: alerting_config_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.alerting_config_id_seq', 1, false);


--
-- Name: alerts_v1_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.alerts_v1_id_seq', 1, false);


--
-- Name: cdc_batches_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.cdc_batches_id_seq', 1, false);


--
-- Name: flow_errors_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.flow_errors_id_seq', 1, false);


--
-- Name: peer_slot_size_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.peer_slot_size_id_seq', 1, false);


--
-- Name: qrep_partitions_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.qrep_partitions_id_seq', 1, false);


--
-- Name: qrep_runs_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.qrep_runs_id_seq', 1, false);


--
-- Name: schema_deltas_audit_log_id_seq; Type: SEQUENCE SET; Schema: peerdb_stats; Owner: -
--

SELECT pg_catalog.setval('peerdb_stats.schema_deltas_audit_log_id_seq', 1, false);


--
-- Name: alerting_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.alerting_settings_id_seq', 16, true);


--
-- Name: ch_s3_stage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ch_s3_stage_id_seq', 1, false);


--
-- Name: flows_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.flows_id_seq', 1, false);


--
-- Name: peer_connections_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.peer_connections_id_seq', 1, false);


--
-- Name: peers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.peers_id_seq', 1, false);


--
-- Name: scripts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.scripts_id_seq', 1, false);


--
-- Name: maintenance_flows maintenance_flows_pkey; Type: CONSTRAINT; Schema: maintenance; Owner: -
--

ALTER TABLE ONLY maintenance.maintenance_flows
    ADD CONSTRAINT maintenance_flows_pkey PRIMARY KEY (id);


--
-- Name: start_maintenance_outputs start_maintenance_outputs_pkey; Type: CONSTRAINT; Schema: maintenance; Owner: -
--

ALTER TABLE ONLY maintenance.start_maintenance_outputs
    ADD CONSTRAINT start_maintenance_outputs_pkey PRIMARY KEY (id);


--
-- Name: alerting_config alerting_config_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.alerting_config
    ADD CONSTRAINT alerting_config_pkey PRIMARY KEY (id);


--
-- Name: alerts_v1 alerts_v1_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.alerts_v1
    ADD CONSTRAINT alerts_v1_pkey PRIMARY KEY (id);


--
-- Name: cdc_batches cdc_batches_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batches
    ADD CONSTRAINT cdc_batches_pkey PRIMARY KEY (id);


--
-- Name: cdc_flows cdc_flows_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_flows
    ADD CONSTRAINT cdc_flows_pkey PRIMARY KEY (flow_name);


--
-- Name: cdc_table_aggregate_counts cdc_table_aggregate_counts_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_table_aggregate_counts
    ADD CONSTRAINT cdc_table_aggregate_counts_pkey PRIMARY KEY (flow_name, destination_table_name);


--
-- Name: flow_errors flow_errors_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.flow_errors
    ADD CONSTRAINT flow_errors_pkey PRIMARY KEY (id);


--
-- Name: peer_slot_size peer_slot_size_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.peer_slot_size
    ADD CONSTRAINT peer_slot_size_pkey PRIMARY KEY (id);


--
-- Name: qrep_partitions qrep_partitions_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions
    ADD CONSTRAINT qrep_partitions_pkey PRIMARY KEY (id);


--
-- Name: qrep_partitions qrep_partitions_run_uuid_partition_uuid_key; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions
    ADD CONSTRAINT qrep_partitions_run_uuid_partition_uuid_key UNIQUE (run_uuid, partition_uuid);


--
-- Name: qrep_runs qrep_runs_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_runs
    ADD CONSTRAINT qrep_runs_pkey PRIMARY KEY (id);


--
-- Name: schema_deltas_audit_log schema_deltas_audit_log_pkey; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.schema_deltas_audit_log
    ADD CONSTRAINT schema_deltas_audit_log_pkey PRIMARY KEY (id);


--
-- Name: qrep_runs uq_qrep_runs_flow_run; Type: CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_runs
    ADD CONSTRAINT uq_qrep_runs_flow_run UNIQUE (flow_name, run_uuid);


--
-- Name: dynamic_settings alerting_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dynamic_settings
    ADD CONSTRAINT alerting_settings_pkey PRIMARY KEY (id);


--
-- Name: ch_s3_stage ch_s3_stage_flow_job_name_sync_batch_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ch_s3_stage
    ADD CONSTRAINT ch_s3_stage_flow_job_name_sync_batch_id_key UNIQUE (flow_job_name, sync_batch_id);


--
-- Name: ch_s3_stage ch_s3_stage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ch_s3_stage
    ADD CONSTRAINT ch_s3_stage_pkey PRIMARY KEY (id);


--
-- Name: flow_migrations flow_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flow_migrations
    ADD CONSTRAINT flow_migrations_pkey PRIMARY KEY (flow_name, migration_name);


--
-- Name: flows flows_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_name_unique UNIQUE (name);


--
-- Name: flows flows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_pkey PRIMARY KEY (id);


--
-- Name: metadata_last_sync_state metadata_last_sync_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata_last_sync_state
    ADD CONSTRAINT metadata_last_sync_state_pkey PRIMARY KEY (job_name);


--
-- Name: metadata_qrep_offloaded_partition_ranges metadata_qrep_offloaded_partition_ranges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata_qrep_offloaded_partition_ranges
    ADD CONSTRAINT metadata_qrep_offloaded_partition_ranges_pkey PRIMARY KEY (run_uuid, partition_uuid);


--
-- Name: metadata_qrep_partitions metadata_qrep_partitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata_qrep_partitions
    ADD CONSTRAINT metadata_qrep_partitions_pkey PRIMARY KEY (job_name, partition_id);


--
-- Name: peer_connections peer_connections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_connections
    ADD CONSTRAINT peer_connections_pkey PRIMARY KEY (id);


--
-- Name: peers peers_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers
    ADD CONSTRAINT peers_name_key UNIQUE (name);


--
-- Name: peers peers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peers
    ADD CONSTRAINT peers_pkey PRIMARY KEY (id);


--
-- Name: query_cdc_avro_stage query_cdc_avro_stage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.query_cdc_avro_stage
    ADD CONSTRAINT query_cdc_avro_stage_pkey PRIMARY KEY (flow_name, source_table_identifier, batch_id);


--
-- Name: query_cdc_replication_state query_cdc_replication_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.query_cdc_replication_state
    ADD CONSTRAINT query_cdc_replication_state_pkey PRIMARY KEY (flow_name, source_table_identifier);


--
-- Name: refinery_schema_history refinery_schema_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refinery_schema_history
    ADD CONSTRAINT refinery_schema_history_pkey PRIMARY KEY (version);


--
-- Name: scripts scripts_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scripts
    ADD CONSTRAINT scripts_name_key UNIQUE (name);


--
-- Name: scripts scripts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scripts
    ADD CONSTRAINT scripts_pkey PRIMARY KEY (id);


--
-- Name: table_schema_mapping table_schema_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_schema_mapping
    ADD CONSTRAINT table_schema_mapping_pkey PRIMARY KEY (flow_name, table_name);


--
-- Name: idx_maintenance_flows_state; Type: INDEX; Schema: maintenance; Owner: -
--

CREATE INDEX idx_maintenance_flows_state ON maintenance.maintenance_flows USING btree (state);


--
-- Name: idx_start_maintenance_outputs_created_at; Type: INDEX; Schema: maintenance; Owner: -
--

CREATE INDEX idx_start_maintenance_outputs_created_at ON maintenance.start_maintenance_outputs USING btree (created_at DESC);


--
-- Name: cdc_table_aggregate_counts_dest_table_idx; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX cdc_table_aggregate_counts_dest_table_idx ON peerdb_stats.cdc_table_aggregate_counts USING btree (destination_table_name);


--
-- Name: cdc_table_aggregate_counts_flow_name_idx; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX cdc_table_aggregate_counts_flow_name_idx ON peerdb_stats.cdc_table_aggregate_counts USING btree (flow_name);


--
-- Name: cdc_table_aggregate_counts_last_updated_idx; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX cdc_table_aggregate_counts_last_updated_idx ON peerdb_stats.cdc_table_aggregate_counts USING btree (last_updated_at);


--
-- Name: idx_cdc_batches_batch_id; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batches_batch_id ON peerdb_stats.cdc_batches USING btree (batch_id);


--
-- Name: idx_cdc_batches_flow_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batches_flow_name ON peerdb_stats.cdc_batches USING hash (flow_name);


--
-- Name: idx_cdc_batches_flow_name_batch_id_open; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batches_flow_name_batch_id_open ON peerdb_stats.cdc_batches USING btree (flow_name, batch_id) WHERE (end_time IS NULL);


--
-- Name: idx_cdc_batches_start_time; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_cdc_batches_start_time ON peerdb_stats.cdc_batches USING btree (start_time);


--
-- Name: idx_flow_errors_flow_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_flow_errors_flow_name ON peerdb_stats.flow_errors USING btree (flow_name);


--
-- Name: idx_qrep_partitions_flow_name_run_uuid; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_partitions_flow_name_run_uuid ON peerdb_stats.qrep_partitions USING btree (flow_name, run_uuid);


--
-- Name: idx_qrep_partitions_partition_uuid; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_partitions_partition_uuid ON peerdb_stats.qrep_partitions USING hash (partition_uuid);


--
-- Name: idx_qrep_partitions_start_time; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_partitions_start_time ON peerdb_stats.qrep_partitions USING btree (start_time);


--
-- Name: idx_qrep_runs_flow_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_runs_flow_name ON peerdb_stats.qrep_runs USING hash (flow_name);


--
-- Name: idx_qrep_runs_run_uuid; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_runs_run_uuid ON peerdb_stats.qrep_runs USING hash (run_uuid);


--
-- Name: idx_qrep_runs_start_time; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX idx_qrep_runs_start_time ON peerdb_stats.qrep_runs USING btree (start_time);


--
-- Name: index_slot_name; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX index_slot_name ON peerdb_stats.peer_slot_size USING btree (slot_name);


--
-- Name: index_slot_updated_at; Type: INDEX; Schema: peerdb_stats; Owner: -
--

CREATE INDEX index_slot_updated_at ON peerdb_stats.peer_slot_size USING btree (updated_at);


--
-- Name: ch_s3_stage_flow_job_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ch_s3_stage_flow_job_name_idx ON public.ch_s3_stage USING btree (flow_job_name);


--
-- Name: ch_s3_stage_sync_batch_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ch_s3_stage_sync_batch_id_idx ON public.ch_s3_stage USING btree (sync_batch_id);


--
-- Name: idx_alerting_settings_config_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_alerting_settings_config_name ON public.dynamic_settings USING btree (config_name);


--
-- Name: idx_metadata_qrep_offloaded_partition_ranges_parent_mirror_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metadata_qrep_offloaded_partition_ranges_parent_mirror_name ON public.metadata_qrep_offloaded_partition_ranges USING btree (parent_mirror_name);


--
-- Name: cdc_batches fk_cdc_batches_flow_name; Type: FK CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.cdc_batches
    ADD CONSTRAINT fk_cdc_batches_flow_name FOREIGN KEY (flow_name) REFERENCES peerdb_stats.cdc_flows(flow_name) ON DELETE CASCADE;


--
-- Name: qrep_partitions fk_qrep_partitions_run; Type: FK CONSTRAINT; Schema: peerdb_stats; Owner: -
--

ALTER TABLE ONLY peerdb_stats.qrep_partitions
    ADD CONSTRAINT fk_qrep_partitions_run FOREIGN KEY (flow_name, run_uuid) REFERENCES peerdb_stats.qrep_runs(flow_name, run_uuid) ON DELETE CASCADE;


--
-- Name: flows flows_destination_peer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_destination_peer_fkey FOREIGN KEY (destination_peer) REFERENCES public.peers(id);


--
-- Name: flows flows_source_peer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flows
    ADD CONSTRAINT flows_source_peer_fkey FOREIGN KEY (source_peer) REFERENCES public.peers(id);


--
-- Name: peer_connections peer_connections_peer_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_connections
    ADD CONSTRAINT peer_connections_peer_name_fkey FOREIGN KEY (peer_name) REFERENCES public.peers(name);


--
-- PostgreSQL database dump complete
--


