package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"reflect"
	"sort"
	"strings"
	"text/template"
)

const converterTemplate = `// Code generated by codegen. DO NOT EDIT.

package proto_conversions

import (
	"github.com/PeerDB-io/peerdb/flow/generated/protos"
)

// FlowConnectionConfigsToCore converts API FlowConnectionConfigs to internal FlowConnectionConfigsCore
func FlowConnectionConfigsToCore(api *protos.FlowConnectionConfigs, tableMappingsVersion int64) *protos.FlowConnectionConfigsCore {
	if api == nil {
		return nil
	}

	core := &protos.FlowConnectionConfigsCore{
{{range .Fields}}		{{.GoName}}: api.{{.GoName}},
{{end}}
		TableMappings: api.TableMappings, // TODO: remove
		// TableMappingsVersion: tableMappingsVersion, // TODO: uncomment
	}
{{.ToCoreOneofSwitches}}
	return core
}

// FlowConnectionConfigsCoreToAPI converts internal FlowConnectionConfigsCore to API FlowConnectionConfigs
func FlowConnectionConfigsCoreToAPI(
	core *protos.FlowConnectionConfigsCore,
	tableMappings []*protos.TableMapping,
) *protos.FlowConnectionConfigs {
	if core == nil {
		return nil
	}

	api := &protos.FlowConnectionConfigs{
{{range .Fields}}		{{.GoName}}: core.{{.GoName}},
{{end}}
		TableMappings: tableMappings, // TODO: remove
	}
{{.ToAPIOneofSwitches}}
	return api
}
`

type Field struct {
	GoName string
}

type ConverterTemplateData struct {
	ToCoreOneofSwitches string
	ToAPIOneofSwitches  string
	Fields              []Field
}

func generateFlowConfigConverter() error {
	// Parse the generated proto Go file to extract field information
	protoPath := "generated/protos/flow.pb.go"
	if _, err := os.Stat(protoPath); os.IsNotExist(err) {
		return fmt.Errorf("proto file %s does not exist, run 'buf generate protos' first", protoPath)
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, protoPath, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("failed to parse flow.pb.go: %w", err)
	}

	// Extract fields from both structs and verify equality
	apiFields, _, err := extractAndCompareFields(node)
	if err != nil {
		return fmt.Errorf("proto equality verification failed: %w", err)
	}

	apiOneofVariants, coreOneofVariants := extractOneofVariants(node)
	if err := compareOneofVariants(apiOneofVariants, coreOneofVariants); err != nil {
		return fmt.Errorf("oneof equality verification failed: %w", err)
	}

	// oneof fields can't be copied with a plain `Core.X = api.X` (the two
	// structs' oneof interfaces are distinct, message-scoped types even for
	// the same wire field) - they're rendered as type switches instead, and
	// excluded from the straight-copy field list below.
	oneofFieldNames := make(map[string]bool, len(apiOneofVariants))
	oneofFieldOrder := make([]string, 0, len(apiOneofVariants))
	for fieldName := range apiOneofVariants {
		oneofFieldNames[fieldName] = true
		oneofFieldOrder = append(oneofFieldOrder, fieldName)
	}
	sort.Strings(oneofFieldOrder)

	fields := make([]Field, 0, len(apiFields))
	for _, fieldName := range apiFields {
		if oneofFieldNames[fieldName] {
			continue
		}
		fields = append(fields, Field{GoName: fieldName})
	}

	if len(fields) == 0 {
		return fmt.Errorf("no fields found in FlowConnectionConfigs")
	}

	var toCoreSwitches, toAPISwitches strings.Builder
	for _, oneofField := range oneofFieldOrder {
		variants := append([]string(nil), apiOneofVariants[oneofField]...)
		sort.Strings(variants)
		toCoreSwitches.WriteString(buildOneofSwitch("api", "core", oneofField, variants, "FlowConnectionConfigs", "FlowConnectionConfigsCore"))
		toAPISwitches.WriteString(buildOneofSwitch("core", "api", oneofField, variants, "FlowConnectionConfigsCore", "FlowConnectionConfigs"))
	}

	// Generate the conversion functions
	tmpl, err := template.New("converter").Parse(converterTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ConverterTemplateData{
		Fields:              fields,
		ToCoreOneofSwitches: toCoreSwitches.String(),
		ToAPIOneofSwitches:  toAPISwitches.String(),
	}); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Write conversion functions to file
	outputDir := "generated/proto_conversions"
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outputPath := "generated/proto_conversions/flow_config_converter.go"
	if err := os.WriteFile(outputPath, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	log.Printf("Generated %s with %d fields and %d oneof field(s)\n", outputPath, len(fields), len(oneofFieldOrder))
	return nil
}

// buildOneofSwitch renders a type switch that copies a single oneof field
// from fromVar (of type fromType) to toVar (of type toType), one case per
// variant. Returns "" if the oneof has no variants.
func buildOneofSwitch(fromVar, toVar, oneofField string, variants []string, fromType, toType string) string {
	if len(variants) == 0 {
		return ""
	}

	var b strings.Builder
	fmt.Fprintf(&b, "\n\tswitch cfg := %s.%s.(type) {\n", fromVar, oneofField)
	for _, variant := range variants {
		fmt.Fprintf(&b, "\tcase *protos.%s_%s:\n", fromType, variant)
		fmt.Fprintf(&b, "\t\t%s.%s = &protos.%s_%s{%s: cfg.%s}\n", toVar, oneofField, toType, variant, variant, variant)
	}
	b.WriteString("\t}\n")
	return b.String()
}

func extractAndCompareFields(node *ast.File) ([]string, []string, error) {
	var apiFields, coreFields []string
	seenFlowConnectionConfigs := false
	seenFlowConnectionConfigsCore := false
	// Extract fields from both structs
	ast.Inspect(node, func(n ast.Node) bool {
		if typeSpec, ok := n.(*ast.TypeSpec); ok {
			var targetFields *[]string
			if typeSpec.Name.Name == "FlowConnectionConfigs" {
				seenFlowConnectionConfigs = true
				targetFields = &apiFields
			} else if typeSpec.Name.Name == "FlowConnectionConfigsCore" {
				seenFlowConnectionConfigsCore = true
				targetFields = &coreFields
			}

			if targetFields != nil {
				if structType, ok := typeSpec.Type.(*ast.StructType); ok {
					for _, field := range structType.Fields.List {
						if len(field.Names) == 0 {
							continue
						}

						fieldName := field.Names[0].Name
						if strings.HasPrefix(fieldName, "XXX_") ||
							fieldName == "state" ||
							fieldName == "sizeCache" ||
							fieldName == "unknownFields" ||
							(typeSpec.Name.Name == "FlowConnectionConfigs" && fieldName == "TableMappings") ||
							(typeSpec.Name.Name == "FlowConnectionConfigsCore" && fieldName == "TableMappings") || // TODO: remove
							(typeSpec.Name.Name == "FlowConnectionConfigsCore" && fieldName == "TableMappingsVersion") {
							continue
						}

						*targetFields = append(*targetFields, fieldName)
					}
				}
			}
		}
		return true
	})

	if !seenFlowConnectionConfigs {
		return nil, nil, fmt.Errorf("couldn't find FlowConnectionConfigs struct, are protos correctly generated?")
	}

	if !seenFlowConnectionConfigsCore {
		return nil, nil, fmt.Errorf("couldn't find FlowConnectionConfigsCore struct, are protos correctly generated?")
	}

	// Sort for comparison
	sort.Strings(apiFields)
	sort.Strings(coreFields)

	// Check if they're equal
	if !reflect.DeepEqual(apiFields, coreFields) {
		apiSet := make(map[string]bool)
		for _, f := range apiFields {
			apiSet[f] = true
		}
		coreSet := make(map[string]bool)
		for _, f := range coreFields {
			coreSet[f] = true
		}

		var onlyInAPI, onlyInCore []string
		for f := range apiSet {
			if !coreSet[f] {
				onlyInAPI = append(onlyInAPI, f)
			}
		}
		for f := range coreSet {
			if !apiSet[f] {
				onlyInCore = append(onlyInCore, f)
			}
		}

		errMsg := "FlowConnectionConfigs and FlowConnectionConfigsCore have different fields\n"
		if len(onlyInAPI) > 0 {
			errMsg += fmt.Sprintf("Fields only in API: %v\n", strings.Join(onlyInAPI, ", "))
		}
		if len(onlyInCore) > 0 {
			errMsg += fmt.Sprintf("Fields only in Core: %v\n", strings.Join(onlyInCore, ", "))
		}
		return nil, nil, errors.New(errMsg)
	}

	log.Println("FlowConnectionConfigs are equal")
	return apiFields, coreFields, nil
}

// extractOneofVariants maps each oneof field's Go name (e.g. SourceConnectorConfig)
// to its variant suffixes (e.g. BigqueryCdcConfig), separately for
// FlowConnectionConfigs and FlowConnectionConfigsCore. It reads the marker
// methods protoc-gen-go emits for each variant wrapper, e.g.:
//
//	func (*FlowConnectionConfigs_BigqueryCdcConfig) isFlowConnectionConfigs_SourceConnectorConfig() {}
func extractOneofVariants(node *ast.File) (map[string][]string, map[string][]string) {
	const apiMarkerPrefix = "isFlowConnectionConfigs_"
	const coreMarkerPrefix = "isFlowConnectionConfigsCore_"
	const apiWrapperPrefix = "FlowConnectionConfigs_"
	const coreWrapperPrefix = "FlowConnectionConfigsCore_"

	apiVariants := make(map[string][]string)
	coreVariants := make(map[string][]string)

	ast.Inspect(node, func(n ast.Node) bool {
		funcDecl, ok := n.(*ast.FuncDecl)
		if !ok || funcDecl.Recv == nil || len(funcDecl.Recv.List) != 1 {
			return true
		}
		starExpr, ok := funcDecl.Recv.List[0].Type.(*ast.StarExpr)
		if !ok {
			return true
		}
		wrapperIdent, ok := starExpr.X.(*ast.Ident)
		if !ok {
			return true
		}

		name := funcDecl.Name.Name
		switch {
		case strings.HasPrefix(name, coreMarkerPrefix):
			oneofField := strings.TrimPrefix(name, coreMarkerPrefix)
			variant := strings.TrimPrefix(wrapperIdent.Name, coreWrapperPrefix)
			coreVariants[oneofField] = append(coreVariants[oneofField], variant)
		case strings.HasPrefix(name, apiMarkerPrefix):
			oneofField := strings.TrimPrefix(name, apiMarkerPrefix)
			variant := strings.TrimPrefix(wrapperIdent.Name, apiWrapperPrefix)
			apiVariants[oneofField] = append(apiVariants[oneofField], variant)
		}
		return true
	})

	return apiVariants, coreVariants
}

func compareOneofVariants(api, core map[string][]string) error {
	if len(api) != len(core) {
		return fmt.Errorf("FlowConnectionConfigs and FlowConnectionConfigsCore have different oneof fields: api=%v core=%v",
			sortedKeys(api), sortedKeys(core))
	}

	for oneofField, apiVariants := range api {
		coreVariants, ok := core[oneofField]
		if !ok {
			return fmt.Errorf("oneof field %s is missing from FlowConnectionConfigsCore", oneofField)
		}

		sortedAPI := append([]string(nil), apiVariants...)
		sortedCore := append([]string(nil), coreVariants...)
		sort.Strings(sortedAPI)
		sort.Strings(sortedCore)
		if !reflect.DeepEqual(sortedAPI, sortedCore) {
			return fmt.Errorf("oneof field %s has different variants: api=%v core=%v", oneofField, sortedAPI, sortedCore)
		}
	}

	return nil
}

func sortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
