package main

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/PeerDB-io/peerdb/flow/generated/proto_conversions"
	"github.com/PeerDB-io/peerdb/flow/generated/protos"
)

// Test_FlowConnectionConfigs_SourceConnectorConfig_OneofRoundTrip exercises the
// type switch buildOneofSwitch generates for the source_connector_config oneof
// (added in chunk 1 to fix the compile break a naive `core.X = api.X` field copy
// hits for a oneof) by round-tripping a real *protos.FlowConnectionConfigs with
// BigqueryCdcConfig set through the actual generated converters.
//
// This lives here, alongside the codegen tool, rather than as a _test.go file
// under flow/generated/proto_conversions/: that whole directory is gitignored
// (regenerated by ./generate-protos.sh), so anything placed there would never
// be committed. Importing the generated package from a committed test file is
// the same thing every real caller already does (cmd/validate_mirror.go,
// e2e/test_utils.go's ExecuteDropFlow), and, like the generator itself
// (generateFlowConfigConverter reads generated/protos/flow.pb.go), it assumes
// protos have already been generated -- true both here and in CI, where
// generate-protos.sh always runs before `go test`.
func Test_FlowConnectionConfigs_SourceConnectorConfig_OneofRoundTrip(t *testing.T) {
	api := &protos.FlowConnectionConfigs{
		FlowJobName: "oneof_roundtrip_test",
		SourceConnectorConfig: &protos.FlowConnectionConfigs_BigqueryCdcConfig{
			BigqueryCdcConfig: &protos.BigqueryCdcConfig{
				CdcMode: protos.BigqueryCdcMode_BIGQUERY_CDC_MODE_CHANGES,
			},
		},
	}

	core := proto_conversions.FlowConnectionConfigsToCore(api, 0)
	require.NotNil(t, core)
	coreVariant, ok := core.SourceConnectorConfig.(*protos.FlowConnectionConfigsCore_BigqueryCdcConfig)
	require.True(t, ok, "expected *FlowConnectionConfigsCore_BigqueryCdcConfig, got %T", core.SourceConnectorConfig)
	require.Equal(t, protos.BigqueryCdcMode_BIGQUERY_CDC_MODE_CHANGES, coreVariant.BigqueryCdcConfig.CdcMode)

	roundTripped := proto_conversions.FlowConnectionConfigsCoreToAPI(core, nil)
	require.NotNil(t, roundTripped)
	apiVariant, ok := roundTripped.SourceConnectorConfig.(*protos.FlowConnectionConfigs_BigqueryCdcConfig)
	require.True(t, ok, "expected *FlowConnectionConfigs_BigqueryCdcConfig, got %T", roundTripped.SourceConnectorConfig)
	require.Equal(t, protos.BigqueryCdcMode_BIGQUERY_CDC_MODE_CHANGES, apiVariant.BigqueryCdcConfig.CdcMode)

	// Non-BigQuery mirrors leave the oneof unset - must round-trip to nil, not
	// panic or spuriously populate a variant via a stale type switch case.
	emptyAPI := &protos.FlowConnectionConfigs{FlowJobName: "no_oneof_test"}
	emptyCore := proto_conversions.FlowConnectionConfigsToCore(emptyAPI, 0)
	require.Nil(t, emptyCore.SourceConnectorConfig)

	emptyRoundTripped := proto_conversions.FlowConnectionConfigsCoreToAPI(emptyCore, nil)
	require.Nil(t, emptyRoundTripped.SourceConnectorConfig)
}
