[package]
name = "postgres-connection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
pt = { path = "../pt" }
openssl = "0.10.55"
postgres-openssl = "0.5.0"
urlencoding = "2"
tokio-postgres = "0.7.2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
