name: 'PeerDB genprotos'
description: 'Install buf with local plugins, generate protos and cache'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: check cache
      id: cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ./flow/generated/protos
          ./nexus/pt/src/gen
          ./ui/grpc_generated
        key: ${{ runner.os }}-build-genprotos-${{ hashFiles('buf.gen.yaml', './protos/peers.proto', './protos/flow.proto', './protos/route.proto') }}

    - if: steps.cache.outputs.cache-hit != 'true'
      uses: bufbuild/buf-action@c231a1aa9281e5db706c970f468f0744a37561fd # v1
      with:
        setup_only: true
        github_token: ${{ github.token }}
    - if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      run: buf generate protos
