name: 'PeerDB genprotos'
description: 'Install buf with local plugins, generate protos and cache'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: check cache
      id: cache
      uses: ubicloud/cache@92361f338d82d2c58a98875f1b5c95cd14cd6b2a # v4
      with:
        path: |
          ./flow/generated/protos
          ./nexus/pt/src/gen
          ./ui/grpc_generated
        key: ${{ runner.os }}-build-genprotos-${{ hashFiles('buf.gen.yaml', './protos/peers.proto', './protos/flow.proto', './protos/route.proto') }}

    - if: steps.cache.outputs.cache-hit != 'true'
      uses: bufbuild/buf-action@3fb70352251376e958c4c2c92c3818de82a71c2b # v1
      with:
        setup_only: true
        github_token: ${{ github.token }}
    - if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      run: buf generate protos
