name: 'PeerDB genprotos'
description: 'Install buf with local plugins, generate protos and cache'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: check cache
      id: cache
      uses: ubicloud/cache@v4
      with:
        path: |
          ./flow/generated/protos
          ./nexus/pt/src/gen
          ./ui/grpc_generated
        key: ${{ runner.os }}-build-genprotos-${{ hashFiles('buf.gen.yaml', './protos/peers.proto', './protos/flow.proto', './protos/route.proto') }}

    - if: steps.cache.outputs.cache-hit != 'true'
      uses: bufbuild/buf-action@v1
      with:
        github_token: ${{ github.token }}
