name: 'PeerDB genprotos'
description: 'Install buf with local plugins, generate protos and cache'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: check cache
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ./flow/generated/protos
          ./nexus/pt/src/gen
          ./ui/grpc_generated
        key: ${{ runner.os }}-build-genprotos-${{ hashFiles('buf.gen.yaml', './protos/peers.proto', './protos/flow.proto', './protos/route.proto') }}

    - if: steps.cache.outputs.cache-hit != 'true'
      uses: bufbuild/buf-action@1b8e0a0e793562b7850d7e6ff0228b5c0b16111c # v1
      with:
        setup_only: true
        github_token: ${{ github.token }}
    - if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      run: buf generate protos
