name: 'PeerDB genprotos'
description: 'Install buf with local plugins, generate protos and cache'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: check cache
      id: cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: |
          ./flow/generated/protos
          ./nexus/pt/src/gen
          ./ui/grpc_generated
        key: ${{ runner.os }}-build-genprotos-${{ hashFiles('buf.gen.yaml', './protos/peers.proto', './protos/flow.proto', './protos/route.proto') }}

    - if: steps.cache.outputs.cache-hit != 'true'
      uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1
      with:
        setup_only: true
        github_token: ${{ github.token }}
    - if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      run: buf generate protos
