// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: peers.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadPreference int32

const (
	ReadPreference_PREFERENCE_UNKNOWN  ReadPreference = 0
	ReadPreference_PRIMARY             ReadPreference = 1
	ReadPreference_PRIMARY_PREFERRED   ReadPreference = 2
	ReadPreference_SECONDARY           ReadPreference = 3
	ReadPreference_SECONDARY_PREFERRED ReadPreference = 4
	ReadPreference_NEAREST             ReadPreference = 5
)

// Enum value maps for ReadPreference.
var (
	ReadPreference_name = map[int32]string{
		0: "PREFERENCE_UNKNOWN",
		1: "PRIMARY",
		2: "PRIMARY_PREFERRED",
		3: "SECONDARY",
		4: "SECONDARY_PREFERRED",
		5: "NEAREST",
	}
	ReadPreference_value = map[string]int32{
		"PREFERENCE_UNKNOWN":  0,
		"PRIMARY":             1,
		"PRIMARY_PREFERRED":   2,
		"SECONDARY":           3,
		"SECONDARY_PREFERRED": 4,
		"NEAREST":             5,
	}
)

func (x ReadPreference) Enum() *ReadPreference {
	p := new(ReadPreference)
	*p = x
	return p
}

func (x ReadPreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadPreference) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[0].Descriptor()
}

func (ReadPreference) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[0]
}

func (x ReadPreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadPreference.Descriptor instead.
func (ReadPreference) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{0}
}

type AwsIAMAuthConfigType int32

const (
	AwsIAMAuthConfigType_IAM_AUTH_AUTOMATIC          AwsIAMAuthConfigType = 0
	AwsIAMAuthConfigType_IAM_AUTH_STATIC_CREDENTIALS AwsIAMAuthConfigType = 1
	AwsIAMAuthConfigType_IAM_AUTH_ASSUME_ROLE        AwsIAMAuthConfigType = 2
)

// Enum value maps for AwsIAMAuthConfigType.
var (
	AwsIAMAuthConfigType_name = map[int32]string{
		0: "IAM_AUTH_AUTOMATIC",
		1: "IAM_AUTH_STATIC_CREDENTIALS",
		2: "IAM_AUTH_ASSUME_ROLE",
	}
	AwsIAMAuthConfigType_value = map[string]int32{
		"IAM_AUTH_AUTOMATIC":          0,
		"IAM_AUTH_STATIC_CREDENTIALS": 1,
		"IAM_AUTH_ASSUME_ROLE":        2,
	}
)

func (x AwsIAMAuthConfigType) Enum() *AwsIAMAuthConfigType {
	p := new(AwsIAMAuthConfigType)
	*p = x
	return p
}

func (x AwsIAMAuthConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AwsIAMAuthConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[1].Descriptor()
}

func (AwsIAMAuthConfigType) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[1]
}

func (x AwsIAMAuthConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AwsIAMAuthConfigType.Descriptor instead.
func (AwsIAMAuthConfigType) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{1}
}

type PostgresAuthType int32

const (
	PostgresAuthType_POSTGRES_PASSWORD PostgresAuthType = 0
	PostgresAuthType_POSTGRES_IAM_AUTH PostgresAuthType = 1
)

// Enum value maps for PostgresAuthType.
var (
	PostgresAuthType_name = map[int32]string{
		0: "POSTGRES_PASSWORD",
		1: "POSTGRES_IAM_AUTH",
	}
	PostgresAuthType_value = map[string]int32{
		"POSTGRES_PASSWORD": 0,
		"POSTGRES_IAM_AUTH": 1,
	}
)

func (x PostgresAuthType) Enum() *PostgresAuthType {
	p := new(PostgresAuthType)
	*p = x
	return p
}

func (x PostgresAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostgresAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[2].Descriptor()
}

func (PostgresAuthType) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[2]
}

func (x PostgresAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostgresAuthType.Descriptor instead.
func (PostgresAuthType) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{2}
}

type AvroCodec int32

const (
	AvroCodec_Null      AvroCodec = 0
	AvroCodec_Deflate   AvroCodec = 1
	AvroCodec_Snappy    AvroCodec = 2
	AvroCodec_ZStandard AvroCodec = 3
)

// Enum value maps for AvroCodec.
var (
	AvroCodec_name = map[int32]string{
		0: "Null",
		1: "Deflate",
		2: "Snappy",
		3: "ZStandard",
	}
	AvroCodec_value = map[string]int32{
		"Null":      0,
		"Deflate":   1,
		"Snappy":    2,
		"ZStandard": 3,
	}
)

func (x AvroCodec) Enum() *AvroCodec {
	p := new(AvroCodec)
	*p = x
	return p
}

func (x AvroCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvroCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[3].Descriptor()
}

func (AvroCodec) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[3]
}

func (x AvroCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvroCodec.Descriptor instead.
func (AvroCodec) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{3}
}

type MySqlFlavor int32

const (
	MySqlFlavor_MYSQL_UNKNOWN MySqlFlavor = 0
	MySqlFlavor_MYSQL_MYSQL   MySqlFlavor = 1
	MySqlFlavor_MYSQL_MARIA   MySqlFlavor = 2
)

// Enum value maps for MySqlFlavor.
var (
	MySqlFlavor_name = map[int32]string{
		0: "MYSQL_UNKNOWN",
		1: "MYSQL_MYSQL",
		2: "MYSQL_MARIA",
	}
	MySqlFlavor_value = map[string]int32{
		"MYSQL_UNKNOWN": 0,
		"MYSQL_MYSQL":   1,
		"MYSQL_MARIA":   2,
	}
)

func (x MySqlFlavor) Enum() *MySqlFlavor {
	p := new(MySqlFlavor)
	*p = x
	return p
}

func (x MySqlFlavor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MySqlFlavor) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[4].Descriptor()
}

func (MySqlFlavor) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[4]
}

func (x MySqlFlavor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MySqlFlavor.Descriptor instead.
func (MySqlFlavor) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{4}
}

type MySqlReplicationMechanism int32

const (
	MySqlReplicationMechanism_MYSQL_AUTO    MySqlReplicationMechanism = 0
	MySqlReplicationMechanism_MYSQL_GTID    MySqlReplicationMechanism = 1
	MySqlReplicationMechanism_MYSQL_FILEPOS MySqlReplicationMechanism = 2
)

// Enum value maps for MySqlReplicationMechanism.
var (
	MySqlReplicationMechanism_name = map[int32]string{
		0: "MYSQL_AUTO",
		1: "MYSQL_GTID",
		2: "MYSQL_FILEPOS",
	}
	MySqlReplicationMechanism_value = map[string]int32{
		"MYSQL_AUTO":    0,
		"MYSQL_GTID":    1,
		"MYSQL_FILEPOS": 2,
	}
)

func (x MySqlReplicationMechanism) Enum() *MySqlReplicationMechanism {
	p := new(MySqlReplicationMechanism)
	*p = x
	return p
}

func (x MySqlReplicationMechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MySqlReplicationMechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[5].Descriptor()
}

func (MySqlReplicationMechanism) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[5]
}

func (x MySqlReplicationMechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MySqlReplicationMechanism.Descriptor instead.
func (MySqlReplicationMechanism) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{5}
}

type MySqlAuthType int32

const (
	MySqlAuthType_MYSQL_PASSWORD MySqlAuthType = 0
	MySqlAuthType_MYSQL_IAM_AUTH MySqlAuthType = 1
)

// Enum value maps for MySqlAuthType.
var (
	MySqlAuthType_name = map[int32]string{
		0: "MYSQL_PASSWORD",
		1: "MYSQL_IAM_AUTH",
	}
	MySqlAuthType_value = map[string]int32{
		"MYSQL_PASSWORD": 0,
		"MYSQL_IAM_AUTH": 1,
	}
)

func (x MySqlAuthType) Enum() *MySqlAuthType {
	p := new(MySqlAuthType)
	*p = x
	return p
}

func (x MySqlAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MySqlAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[6].Descriptor()
}

func (MySqlAuthType) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[6]
}

func (x MySqlAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MySqlAuthType.Descriptor instead.
func (MySqlAuthType) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{6}
}

type ElasticsearchAuthType int32

const (
	ElasticsearchAuthType_UNKNOWN ElasticsearchAuthType = 0
	ElasticsearchAuthType_NONE    ElasticsearchAuthType = 1
	ElasticsearchAuthType_BASIC   ElasticsearchAuthType = 2
	ElasticsearchAuthType_APIKEY  ElasticsearchAuthType = 3
)

// Enum value maps for ElasticsearchAuthType.
var (
	ElasticsearchAuthType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NONE",
		2: "BASIC",
		3: "APIKEY",
	}
	ElasticsearchAuthType_value = map[string]int32{
		"UNKNOWN": 0,
		"NONE":    1,
		"BASIC":   2,
		"APIKEY":  3,
	}
)

func (x ElasticsearchAuthType) Enum() *ElasticsearchAuthType {
	p := new(ElasticsearchAuthType)
	*p = x
	return p
}

func (x ElasticsearchAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElasticsearchAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[7].Descriptor()
}

func (ElasticsearchAuthType) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[7]
}

func (x ElasticsearchAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElasticsearchAuthType.Descriptor instead.
func (ElasticsearchAuthType) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{7}
}

type DBType int32

const (
	DBType_BIGQUERY       DBType = 0
	DBType_SNOWFLAKE      DBType = 1
	DBType_MONGO          DBType = 2
	DBType_POSTGRES       DBType = 3
	DBType_S3             DBType = 5
	DBType_SQLSERVER      DBType = 6
	DBType_MYSQL          DBType = 7
	DBType_CLICKHOUSE     DBType = 8
	DBType_KAFKA          DBType = 9
	DBType_PUBSUB         DBType = 10
	DBType_EVENTHUBS      DBType = 11
	DBType_ELASTICSEARCH  DBType = 12
	DBType_DBTYPE_UNKNOWN DBType = -1
)

// Enum value maps for DBType.
var (
	DBType_name = map[int32]string{
		0:  "BIGQUERY",
		1:  "SNOWFLAKE",
		2:  "MONGO",
		3:  "POSTGRES",
		5:  "S3",
		6:  "SQLSERVER",
		7:  "MYSQL",
		8:  "CLICKHOUSE",
		9:  "KAFKA",
		10: "PUBSUB",
		11: "EVENTHUBS",
		12: "ELASTICSEARCH",
		-1: "DBTYPE_UNKNOWN",
	}
	DBType_value = map[string]int32{
		"BIGQUERY":       0,
		"SNOWFLAKE":      1,
		"MONGO":          2,
		"POSTGRES":       3,
		"S3":             5,
		"SQLSERVER":      6,
		"MYSQL":          7,
		"CLICKHOUSE":     8,
		"KAFKA":          9,
		"PUBSUB":         10,
		"EVENTHUBS":      11,
		"ELASTICSEARCH":  12,
		"DBTYPE_UNKNOWN": -1,
	}
)

func (x DBType) Enum() *DBType {
	p := new(DBType)
	*p = x
	return p
}

func (x DBType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DBType) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[8].Descriptor()
}

func (DBType) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[8]
}

func (x DBType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DBType.Descriptor instead.
func (DBType) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{8}
}

type DatabaseVariant int32

const (
	// either vanilla or something not listed here
	DatabaseVariant_VARIANT_UNKNOWN  DatabaseVariant = 0
	DatabaseVariant_AWS_RDS          DatabaseVariant = 2
	DatabaseVariant_AWS_AURORA       DatabaseVariant = 3
	DatabaseVariant_GOOGLE_CLOUD_SQL DatabaseVariant = 4
	DatabaseVariant_AZURE_DATABASE   DatabaseVariant = 5
	// only Postgres
	DatabaseVariant_NEON DatabaseVariant = 6
	// has Vitess, but only Postgres for now
	DatabaseVariant_PLANETSCALE DatabaseVariant = 7
	// only Postgres
	DatabaseVariant_SUPABASE DatabaseVariant = 8
)

// Enum value maps for DatabaseVariant.
var (
	DatabaseVariant_name = map[int32]string{
		0: "VARIANT_UNKNOWN",
		2: "AWS_RDS",
		3: "AWS_AURORA",
		4: "GOOGLE_CLOUD_SQL",
		5: "AZURE_DATABASE",
		6: "NEON",
		7: "PLANETSCALE",
		8: "SUPABASE",
	}
	DatabaseVariant_value = map[string]int32{
		"VARIANT_UNKNOWN":  0,
		"AWS_RDS":          2,
		"AWS_AURORA":       3,
		"GOOGLE_CLOUD_SQL": 4,
		"AZURE_DATABASE":   5,
		"NEON":             6,
		"PLANETSCALE":      7,
		"SUPABASE":         8,
	}
)

func (x DatabaseVariant) Enum() *DatabaseVariant {
	p := new(DatabaseVariant)
	*p = x
	return p
}

func (x DatabaseVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_peers_proto_enumTypes[9].Descriptor()
}

func (DatabaseVariant) Type() protoreflect.EnumType {
	return &file_peers_proto_enumTypes[9]
}

func (x DatabaseVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseVariant.Descriptor instead.
func (DatabaseVariant) EnumDescriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{9}
}

type SSHConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	HostKey       string                 `protobuf:"bytes,6,opt,name=host_key,json=hostKey,proto3" json:"host_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHConfig) Reset() {
	*x = SSHConfig{}
	mi := &file_peers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHConfig) ProtoMessage() {}

func (x *SSHConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHConfig.ProtoReflect.Descriptor instead.
func (*SSHConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{0}
}

func (x *SSHConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SSHConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SSHConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SSHConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SSHConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SSHConfig) GetHostKey() string {
	if x != nil {
		return x.HostKey
	}
	return ""
}

type SnowflakeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Database      string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Warehouse     string                 `protobuf:"bytes,6,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	QueryTimeout  uint64                 `protobuf:"varint,8,opt,name=query_timeout,json=queryTimeout,proto3" json:"query_timeout,omitempty"`
	S3Integration string                 `protobuf:"bytes,9,opt,name=s3_integration,json=s3Integration,proto3" json:"s3_integration,omitempty"`
	Password      *string                `protobuf:"bytes,10,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// defaults to _PEERDB_INTERNAL
	MetadataSchema *string `protobuf:"bytes,11,opt,name=metadata_schema,json=metadataSchema,proto3,oneof" json:"metadata_schema,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnowflakeConfig) Reset() {
	*x = SnowflakeConfig{}
	mi := &file_peers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnowflakeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnowflakeConfig) ProtoMessage() {}

func (x *SnowflakeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnowflakeConfig.ProtoReflect.Descriptor instead.
func (*SnowflakeConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{1}
}

func (x *SnowflakeConfig) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SnowflakeConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SnowflakeConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SnowflakeConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SnowflakeConfig) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

func (x *SnowflakeConfig) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SnowflakeConfig) GetQueryTimeout() uint64 {
	if x != nil {
		return x.QueryTimeout
	}
	return 0
}

func (x *SnowflakeConfig) GetS3Integration() string {
	if x != nil {
		return x.S3Integration
	}
	return ""
}

func (x *SnowflakeConfig) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SnowflakeConfig) GetMetadataSchema() string {
	if x != nil && x.MetadataSchema != nil {
		return *x.MetadataSchema
	}
	return ""
}

type GcpServiceAccount struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AuthType                string                 `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	ProjectId               string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PrivateKeyId            string                 `protobuf:"bytes,3,opt,name=private_key_id,json=privateKeyId,proto3" json:"private_key_id,omitempty"`
	PrivateKey              string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ClientEmail             string                 `protobuf:"bytes,5,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientId                string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuthUri                 string                 `protobuf:"bytes,7,opt,name=auth_uri,json=authUri,proto3" json:"auth_uri,omitempty"`
	TokenUri                string                 `protobuf:"bytes,8,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`
	AuthProviderX509CertUrl string                 `protobuf:"bytes,9,opt,name=auth_provider_x509_cert_url,json=authProviderX509CertUrl,proto3" json:"auth_provider_x509_cert_url,omitempty"`
	ClientX509CertUrl       string                 `protobuf:"bytes,10,opt,name=client_x509_cert_url,json=clientX509CertUrl,proto3" json:"client_x509_cert_url,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GcpServiceAccount) Reset() {
	*x = GcpServiceAccount{}
	mi := &file_peers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpServiceAccount) ProtoMessage() {}

func (x *GcpServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpServiceAccount.ProtoReflect.Descriptor instead.
func (*GcpServiceAccount) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{2}
}

func (x *GcpServiceAccount) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *GcpServiceAccount) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GcpServiceAccount) GetPrivateKeyId() string {
	if x != nil {
		return x.PrivateKeyId
	}
	return ""
}

func (x *GcpServiceAccount) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GcpServiceAccount) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *GcpServiceAccount) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GcpServiceAccount) GetAuthUri() string {
	if x != nil {
		return x.AuthUri
	}
	return ""
}

func (x *GcpServiceAccount) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *GcpServiceAccount) GetAuthProviderX509CertUrl() string {
	if x != nil {
		return x.AuthProviderX509CertUrl
	}
	return ""
}

func (x *GcpServiceAccount) GetClientX509CertUrl() string {
	if x != nil {
		return x.ClientX509CertUrl
	}
	return ""
}

type BigqueryConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AuthType                string                 `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	ProjectId               string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PrivateKeyId            string                 `protobuf:"bytes,3,opt,name=private_key_id,json=privateKeyId,proto3" json:"private_key_id,omitempty"`
	PrivateKey              string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ClientEmail             string                 `protobuf:"bytes,5,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientId                string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuthUri                 string                 `protobuf:"bytes,7,opt,name=auth_uri,json=authUri,proto3" json:"auth_uri,omitempty"`
	TokenUri                string                 `protobuf:"bytes,8,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`
	AuthProviderX509CertUrl string                 `protobuf:"bytes,9,opt,name=auth_provider_x509_cert_url,json=authProviderX509CertUrl,proto3" json:"auth_provider_x509_cert_url,omitempty"`
	ClientX509CertUrl       string                 `protobuf:"bytes,10,opt,name=client_x509_cert_url,json=clientX509CertUrl,proto3" json:"client_x509_cert_url,omitempty"`
	DatasetId               string                 `protobuf:"bytes,11,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BigqueryConfig) Reset() {
	*x = BigqueryConfig{}
	mi := &file_peers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigqueryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigqueryConfig) ProtoMessage() {}

func (x *BigqueryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigqueryConfig.ProtoReflect.Descriptor instead.
func (*BigqueryConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{3}
}

func (x *BigqueryConfig) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *BigqueryConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BigqueryConfig) GetPrivateKeyId() string {
	if x != nil {
		return x.PrivateKeyId
	}
	return ""
}

func (x *BigqueryConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *BigqueryConfig) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *BigqueryConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BigqueryConfig) GetAuthUri() string {
	if x != nil {
		return x.AuthUri
	}
	return ""
}

func (x *BigqueryConfig) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *BigqueryConfig) GetAuthProviderX509CertUrl() string {
	if x != nil {
		return x.AuthProviderX509CertUrl
	}
	return ""
}

func (x *BigqueryConfig) GetClientX509CertUrl() string {
	if x != nil {
		return x.ClientX509CertUrl
	}
	return ""
}

func (x *BigqueryConfig) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type PubSubConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount *GcpServiceAccount     `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PubSubConfig) Reset() {
	*x = PubSubConfig{}
	mi := &file_peers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubConfig) ProtoMessage() {}

func (x *PubSubConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubConfig.ProtoReflect.Descriptor instead.
func (*PubSubConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{4}
}

func (x *PubSubConfig) GetServiceAccount() *GcpServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

type MongoConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// can be a mongodb:// URI mapping to discrete hosts or a mongodb+srv:// URI
	// mapping to a DNS SRV record.
	Uri            string         `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Username       string         `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password       string         `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DisableTls     bool           `protobuf:"varint,4,opt,name=disable_tls,json=disableTls,proto3" json:"disable_tls,omitempty"`
	TlsHost        string         `protobuf:"bytes,5,opt,name=tls_host,json=tlsHost,proto3" json:"tls_host,omitempty"`
	RootCa         *string        `protobuf:"bytes,6,opt,name=root_ca,json=rootCa,proto3,oneof" json:"root_ca,omitempty"`
	ReadPreference ReadPreference `protobuf:"varint,7,opt,name=read_preference,json=readPreference,proto3,enum=peerdb_peers.ReadPreference" json:"read_preference,omitempty"`
	SshConfig      *SSHConfig     `protobuf:"bytes,8,opt,name=ssh_config,json=sshConfig,proto3,oneof" json:"ssh_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MongoConfig) Reset() {
	*x = MongoConfig{}
	mi := &file_peers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoConfig) ProtoMessage() {}

func (x *MongoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoConfig.ProtoReflect.Descriptor instead.
func (*MongoConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{5}
}

func (x *MongoConfig) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MongoConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MongoConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MongoConfig) GetDisableTls() bool {
	if x != nil {
		return x.DisableTls
	}
	return false
}

func (x *MongoConfig) GetTlsHost() string {
	if x != nil {
		return x.TlsHost
	}
	return ""
}

func (x *MongoConfig) GetRootCa() string {
	if x != nil && x.RootCa != nil {
		return *x.RootCa
	}
	return ""
}

func (x *MongoConfig) GetReadPreference() ReadPreference {
	if x != nil {
		return x.ReadPreference
	}
	return ReadPreference_PREFERENCE_UNKNOWN
}

func (x *MongoConfig) GetSshConfig() *SSHConfig {
	if x != nil {
		return x.SshConfig
	}
	return nil
}

type AwsAuthStaticCredentialsConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AwsAuthStaticCredentialsConfig) Reset() {
	*x = AwsAuthStaticCredentialsConfig{}
	mi := &file_peers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsAuthStaticCredentialsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsAuthStaticCredentialsConfig) ProtoMessage() {}

func (x *AwsAuthStaticCredentialsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsAuthStaticCredentialsConfig.ProtoReflect.Descriptor instead.
func (*AwsAuthStaticCredentialsConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{6}
}

func (x *AwsAuthStaticCredentialsConfig) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AwsAuthStaticCredentialsConfig) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

type AWSAuthAssumeRoleConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssumeRoleArn  string                 `protobuf:"bytes,1,opt,name=assume_role_arn,json=assumeRoleArn,proto3" json:"assume_role_arn,omitempty"`
	ChainedRoleArn *string                `protobuf:"bytes,2,opt,name=chained_role_arn,json=chainedRoleArn,proto3,oneof" json:"chained_role_arn,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AWSAuthAssumeRoleConfig) Reset() {
	*x = AWSAuthAssumeRoleConfig{}
	mi := &file_peers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSAuthAssumeRoleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSAuthAssumeRoleConfig) ProtoMessage() {}

func (x *AWSAuthAssumeRoleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSAuthAssumeRoleConfig.ProtoReflect.Descriptor instead.
func (*AWSAuthAssumeRoleConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{7}
}

func (x *AWSAuthAssumeRoleConfig) GetAssumeRoleArn() string {
	if x != nil {
		return x.AssumeRoleArn
	}
	return ""
}

func (x *AWSAuthAssumeRoleConfig) GetChainedRoleArn() string {
	if x != nil && x.ChainedRoleArn != nil {
		return *x.ChainedRoleArn
	}
	return ""
}

type AwsAuthenticationConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Region   string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	AuthType AwsIAMAuthConfigType   `protobuf:"varint,2,opt,name=auth_type,json=authType,proto3,enum=peerdb_peers.AwsIAMAuthConfigType" json:"auth_type,omitempty"`
	// Types that are valid to be assigned to AuthConfig:
	//
	//	*AwsAuthenticationConfig_StaticCredentials
	//	*AwsAuthenticationConfig_Role
	AuthConfig    isAwsAuthenticationConfig_AuthConfig `protobuf_oneof:"auth_config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsAuthenticationConfig) Reset() {
	*x = AwsAuthenticationConfig{}
	mi := &file_peers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsAuthenticationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsAuthenticationConfig) ProtoMessage() {}

func (x *AwsAuthenticationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsAuthenticationConfig.ProtoReflect.Descriptor instead.
func (*AwsAuthenticationConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{8}
}

func (x *AwsAuthenticationConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AwsAuthenticationConfig) GetAuthType() AwsIAMAuthConfigType {
	if x != nil {
		return x.AuthType
	}
	return AwsIAMAuthConfigType_IAM_AUTH_AUTOMATIC
}

func (x *AwsAuthenticationConfig) GetAuthConfig() isAwsAuthenticationConfig_AuthConfig {
	if x != nil {
		return x.AuthConfig
	}
	return nil
}

func (x *AwsAuthenticationConfig) GetStaticCredentials() *AwsAuthStaticCredentialsConfig {
	if x != nil {
		if x, ok := x.AuthConfig.(*AwsAuthenticationConfig_StaticCredentials); ok {
			return x.StaticCredentials
		}
	}
	return nil
}

func (x *AwsAuthenticationConfig) GetRole() *AWSAuthAssumeRoleConfig {
	if x != nil {
		if x, ok := x.AuthConfig.(*AwsAuthenticationConfig_Role); ok {
			return x.Role
		}
	}
	return nil
}

type isAwsAuthenticationConfig_AuthConfig interface {
	isAwsAuthenticationConfig_AuthConfig()
}

type AwsAuthenticationConfig_StaticCredentials struct {
	StaticCredentials *AwsAuthStaticCredentialsConfig `protobuf:"bytes,3,opt,name=static_credentials,json=staticCredentials,proto3,oneof"`
}

type AwsAuthenticationConfig_Role struct {
	Role *AWSAuthAssumeRoleConfig `protobuf:"bytes,4,opt,name=role,proto3,oneof"`
}

func (*AwsAuthenticationConfig_StaticCredentials) isAwsAuthenticationConfig_AuthConfig() {}

func (*AwsAuthenticationConfig_Role) isAwsAuthenticationConfig_AuthConfig() {}

type PostgresConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Host     string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port     uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User     string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Database string                 `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	TlsHost  string                 `protobuf:"bytes,6,opt,name=tls_host,json=tlsHost,proto3" json:"tls_host,omitempty"`
	// defaults to _peerdb_internal
	MetadataSchema *string                  `protobuf:"bytes,7,opt,name=metadata_schema,json=metadataSchema,proto3,oneof" json:"metadata_schema,omitempty"`
	SshConfig      *SSHConfig               `protobuf:"bytes,8,opt,name=ssh_config,json=sshConfig,proto3,oneof" json:"ssh_config,omitempty"`
	RootCa         *string                  `protobuf:"bytes,9,opt,name=root_ca,json=rootCa,proto3,oneof" json:"root_ca,omitempty"`
	RequireTls     bool                     `protobuf:"varint,10,opt,name=require_tls,json=requireTls,proto3" json:"require_tls,omitempty"`
	AuthType       PostgresAuthType         `protobuf:"varint,11,opt,name=auth_type,json=authType,proto3,enum=peerdb_peers.PostgresAuthType" json:"auth_type,omitempty"`
	AwsAuth        *AwsAuthenticationConfig `protobuf:"bytes,12,opt,name=aws_auth,json=awsAuth,proto3,oneof" json:"aws_auth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostgresConfig) Reset() {
	*x = PostgresConfig{}
	mi := &file_peers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresConfig) ProtoMessage() {}

func (x *PostgresConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresConfig.ProtoReflect.Descriptor instead.
func (*PostgresConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{9}
}

func (x *PostgresConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PostgresConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PostgresConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PostgresConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PostgresConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *PostgresConfig) GetTlsHost() string {
	if x != nil {
		return x.TlsHost
	}
	return ""
}

func (x *PostgresConfig) GetMetadataSchema() string {
	if x != nil && x.MetadataSchema != nil {
		return *x.MetadataSchema
	}
	return ""
}

func (x *PostgresConfig) GetSshConfig() *SSHConfig {
	if x != nil {
		return x.SshConfig
	}
	return nil
}

func (x *PostgresConfig) GetRootCa() string {
	if x != nil && x.RootCa != nil {
		return *x.RootCa
	}
	return ""
}

func (x *PostgresConfig) GetRequireTls() bool {
	if x != nil {
		return x.RequireTls
	}
	return false
}

func (x *PostgresConfig) GetAuthType() PostgresAuthType {
	if x != nil {
		return x.AuthType
	}
	return PostgresAuthType_POSTGRES_PASSWORD
}

func (x *PostgresConfig) GetAwsAuth() *AwsAuthenticationConfig {
	if x != nil {
		return x.AwsAuth
	}
	return nil
}

type EventHubConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceGroup string                 `protobuf:"bytes,2,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// if this is empty PeerDB uses `AZURE_SUBSCRIPTION_ID` environment variable.
	SubscriptionId string `protobuf:"bytes,5,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// defaults to 3
	PartitionCount uint32 `protobuf:"varint,6,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	// defaults to 7
	MessageRetentionInDays uint32 `protobuf:"varint,7,opt,name=message_retention_in_days,json=messageRetentionInDays,proto3" json:"message_retention_in_days,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventHubConfig) Reset() {
	*x = EventHubConfig{}
	mi := &file_peers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventHubConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHubConfig) ProtoMessage() {}

func (x *EventHubConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHubConfig.ProtoReflect.Descriptor instead.
func (*EventHubConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{10}
}

func (x *EventHubConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EventHubConfig) GetResourceGroup() string {
	if x != nil {
		return x.ResourceGroup
	}
	return ""
}

func (x *EventHubConfig) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventHubConfig) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *EventHubConfig) GetPartitionCount() uint32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

func (x *EventHubConfig) GetMessageRetentionInDays() uint32 {
	if x != nil {
		return x.MessageRetentionInDays
	}
	return 0
}

type EventHubGroupConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event hub namespace name to event hub config
	Eventhubs     map[string]*EventHubConfig `protobuf:"bytes,1,rep,name=eventhubs,proto3" json:"eventhubs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UnnestColumns []string                   `protobuf:"bytes,3,rep,name=unnest_columns,json=unnestColumns,proto3" json:"unnest_columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventHubGroupConfig) Reset() {
	*x = EventHubGroupConfig{}
	mi := &file_peers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventHubGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHubGroupConfig) ProtoMessage() {}

func (x *EventHubGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHubGroupConfig.ProtoReflect.Descriptor instead.
func (*EventHubGroupConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{11}
}

func (x *EventHubGroupConfig) GetEventhubs() map[string]*EventHubConfig {
	if x != nil {
		return x.Eventhubs
	}
	return nil
}

func (x *EventHubGroupConfig) GetUnnestColumns() []string {
	if x != nil {
		return x.UnnestColumns
	}
	return nil
}

type S3Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AccessKeyId     *string                `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3,oneof" json:"access_key_id,omitempty"`
	SecretAccessKey *string                `protobuf:"bytes,3,opt,name=secret_access_key,json=secretAccessKey,proto3,oneof" json:"secret_access_key,omitempty"`
	RoleArn         *string                `protobuf:"bytes,4,opt,name=role_arn,json=roleArn,proto3,oneof" json:"role_arn,omitempty"`
	Region          *string                `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Endpoint        *string                `protobuf:"bytes,6,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	RootCa          *string                `protobuf:"bytes,7,opt,name=root_ca,json=rootCa,proto3,oneof" json:"root_ca,omitempty"`
	TlsHost         string                 `protobuf:"bytes,8,opt,name=tls_host,json=tlsHost,proto3" json:"tls_host,omitempty"`
	Codec           AvroCodec              `protobuf:"varint,9,opt,name=codec,proto3,enum=peerdb_peers.AvroCodec" json:"codec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_peers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{12}
}

func (x *S3Config) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *S3Config) GetAccessKeyId() string {
	if x != nil && x.AccessKeyId != nil {
		return *x.AccessKeyId
	}
	return ""
}

func (x *S3Config) GetSecretAccessKey() string {
	if x != nil && x.SecretAccessKey != nil {
		return *x.SecretAccessKey
	}
	return ""
}

func (x *S3Config) GetRoleArn() string {
	if x != nil && x.RoleArn != nil {
		return *x.RoleArn
	}
	return ""
}

func (x *S3Config) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *S3Config) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *S3Config) GetRootCa() string {
	if x != nil && x.RootCa != nil {
		return *x.RootCa
	}
	return ""
}

func (x *S3Config) GetTlsHost() string {
	if x != nil {
		return x.TlsHost
	}
	return ""
}

func (x *S3Config) GetCodec() AvroCodec {
	if x != nil {
		return x.Codec
	}
	return AvroCodec_Null
}

type ClickhouseConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Host            string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port            uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User            string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Database        string                 `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	S3Path          string                 `protobuf:"bytes,6,opt,name=s3_path,json=s3Path,proto3" json:"s3_path,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,7,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,8,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Region          string                 `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	DisableTls      bool                   `protobuf:"varint,10,opt,name=disable_tls,json=disableTls,proto3" json:"disable_tls,omitempty"`
	Endpoint        *string                `protobuf:"bytes,11,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	Certificate     *string                `protobuf:"bytes,12,opt,name=certificate,proto3,oneof" json:"certificate,omitempty"`
	PrivateKey      *string                `protobuf:"bytes,13,opt,name=private_key,json=privateKey,proto3,oneof" json:"private_key,omitempty"`
	RootCa          *string                `protobuf:"bytes,14,opt,name=root_ca,json=rootCa,proto3,oneof" json:"root_ca,omitempty"`
	TlsHost         string                 `protobuf:"bytes,15,opt,name=tls_host,json=tlsHost,proto3" json:"tls_host,omitempty"`
	S3              *S3Config              `protobuf:"bytes,16,opt,name=s3,proto3,oneof" json:"s3,omitempty"`
	Cluster         string                 `protobuf:"bytes,17,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Replicated      bool                   `protobuf:"varint,18,opt,name=replicated,proto3" json:"replicated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClickhouseConfig) Reset() {
	*x = ClickhouseConfig{}
	mi := &file_peers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickhouseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickhouseConfig) ProtoMessage() {}

func (x *ClickhouseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickhouseConfig.ProtoReflect.Descriptor instead.
func (*ClickhouseConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{13}
}

func (x *ClickhouseConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ClickhouseConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClickhouseConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ClickhouseConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClickhouseConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ClickhouseConfig) GetS3Path() string {
	if x != nil {
		return x.S3Path
	}
	return ""
}

func (x *ClickhouseConfig) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *ClickhouseConfig) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *ClickhouseConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClickhouseConfig) GetDisableTls() bool {
	if x != nil {
		return x.DisableTls
	}
	return false
}

func (x *ClickhouseConfig) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *ClickhouseConfig) GetCertificate() string {
	if x != nil && x.Certificate != nil {
		return *x.Certificate
	}
	return ""
}

func (x *ClickhouseConfig) GetPrivateKey() string {
	if x != nil && x.PrivateKey != nil {
		return *x.PrivateKey
	}
	return ""
}

func (x *ClickhouseConfig) GetRootCa() string {
	if x != nil && x.RootCa != nil {
		return *x.RootCa
	}
	return ""
}

func (x *ClickhouseConfig) GetTlsHost() string {
	if x != nil {
		return x.TlsHost
	}
	return ""
}

func (x *ClickhouseConfig) GetS3() *S3Config {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *ClickhouseConfig) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ClickhouseConfig) GetReplicated() bool {
	if x != nil {
		return x.Replicated
	}
	return false
}

type SqlServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Database      string                 `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlServerConfig) Reset() {
	*x = SqlServerConfig{}
	mi := &file_peers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlServerConfig) ProtoMessage() {}

func (x *SqlServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlServerConfig.ProtoReflect.Descriptor instead.
func (*SqlServerConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{14}
}

func (x *SqlServerConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SqlServerConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SqlServerConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SqlServerConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SqlServerConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type MySqlConfig struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	Host                 string                    `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32                    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User                 string                    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password             string                    `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Database             string                    `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Setup                []string                  `protobuf:"bytes,6,rep,name=setup,proto3" json:"setup,omitempty"`
	Compression          uint32                    `protobuf:"varint,7,opt,name=compression,proto3" json:"compression,omitempty"`
	DisableTls           bool                      `protobuf:"varint,8,opt,name=disable_tls,json=disableTls,proto3" json:"disable_tls,omitempty"`
	Flavor               MySqlFlavor               `protobuf:"varint,9,opt,name=flavor,proto3,enum=peerdb_peers.MySqlFlavor" json:"flavor,omitempty"`
	SshConfig            *SSHConfig                `protobuf:"bytes,10,opt,name=ssh_config,json=sshConfig,proto3,oneof" json:"ssh_config,omitempty"`
	ReplicationMechanism MySqlReplicationMechanism `protobuf:"varint,11,opt,name=replication_mechanism,json=replicationMechanism,proto3,enum=peerdb_peers.MySqlReplicationMechanism" json:"replication_mechanism,omitempty"`
	TlsHost              string                    `protobuf:"bytes,13,opt,name=tls_host,json=tlsHost,proto3" json:"tls_host,omitempty"`
	RootCa               *string                   `protobuf:"bytes,14,opt,name=root_ca,json=rootCa,proto3,oneof" json:"root_ca,omitempty"`
	AuthType             MySqlAuthType             `protobuf:"varint,15,opt,name=auth_type,json=authType,proto3,enum=peerdb_peers.MySqlAuthType" json:"auth_type,omitempty"`
	AwsAuth              *AwsAuthenticationConfig  `protobuf:"bytes,16,opt,name=aws_auth,json=awsAuth,proto3,oneof" json:"aws_auth,omitempty"`
	SkipCertVerification bool                      `protobuf:"varint,17,opt,name=skip_cert_verification,json=skipCertVerification,proto3" json:"skip_cert_verification,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MySqlConfig) Reset() {
	*x = MySqlConfig{}
	mi := &file_peers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySqlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySqlConfig) ProtoMessage() {}

func (x *MySqlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySqlConfig.ProtoReflect.Descriptor instead.
func (*MySqlConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{15}
}

func (x *MySqlConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MySqlConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MySqlConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MySqlConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MySqlConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *MySqlConfig) GetSetup() []string {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *MySqlConfig) GetCompression() uint32 {
	if x != nil {
		return x.Compression
	}
	return 0
}

func (x *MySqlConfig) GetDisableTls() bool {
	if x != nil {
		return x.DisableTls
	}
	return false
}

func (x *MySqlConfig) GetFlavor() MySqlFlavor {
	if x != nil {
		return x.Flavor
	}
	return MySqlFlavor_MYSQL_UNKNOWN
}

func (x *MySqlConfig) GetSshConfig() *SSHConfig {
	if x != nil {
		return x.SshConfig
	}
	return nil
}

func (x *MySqlConfig) GetReplicationMechanism() MySqlReplicationMechanism {
	if x != nil {
		return x.ReplicationMechanism
	}
	return MySqlReplicationMechanism_MYSQL_AUTO
}

func (x *MySqlConfig) GetTlsHost() string {
	if x != nil {
		return x.TlsHost
	}
	return ""
}

func (x *MySqlConfig) GetRootCa() string {
	if x != nil && x.RootCa != nil {
		return *x.RootCa
	}
	return ""
}

func (x *MySqlConfig) GetAuthType() MySqlAuthType {
	if x != nil {
		return x.AuthType
	}
	return MySqlAuthType_MYSQL_PASSWORD
}

func (x *MySqlConfig) GetAwsAuth() *AwsAuthenticationConfig {
	if x != nil {
		return x.AwsAuth
	}
	return nil
}

func (x *MySqlConfig) GetSkipCertVerification() bool {
	if x != nil {
		return x.SkipCertVerification
	}
	return false
}

type KafkaConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []string               `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Sasl          string                 `protobuf:"bytes,4,opt,name=sasl,proto3" json:"sasl,omitempty"`
	DisableTls    bool                   `protobuf:"varint,5,opt,name=disable_tls,json=disableTls,proto3" json:"disable_tls,omitempty"`
	Partitioner   string                 `protobuf:"bytes,6,opt,name=partitioner,proto3" json:"partitioner,omitempty"`
	Certificate   *string                `protobuf:"bytes,7,opt,name=certificate,proto3,oneof" json:"certificate,omitempty"`
	PrivateKey    *string                `protobuf:"bytes,8,opt,name=private_key,json=privateKey,proto3,oneof" json:"private_key,omitempty"`
	RootCa        *string                `protobuf:"bytes,9,opt,name=root_ca,json=rootCa,proto3,oneof" json:"root_ca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaConfig) Reset() {
	*x = KafkaConfig{}
	mi := &file_peers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaConfig) ProtoMessage() {}

func (x *KafkaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaConfig.ProtoReflect.Descriptor instead.
func (*KafkaConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{16}
}

func (x *KafkaConfig) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *KafkaConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *KafkaConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *KafkaConfig) GetSasl() string {
	if x != nil {
		return x.Sasl
	}
	return ""
}

func (x *KafkaConfig) GetDisableTls() bool {
	if x != nil {
		return x.DisableTls
	}
	return false
}

func (x *KafkaConfig) GetPartitioner() string {
	if x != nil {
		return x.Partitioner
	}
	return ""
}

func (x *KafkaConfig) GetCertificate() string {
	if x != nil && x.Certificate != nil {
		return *x.Certificate
	}
	return ""
}

func (x *KafkaConfig) GetPrivateKey() string {
	if x != nil && x.PrivateKey != nil {
		return *x.PrivateKey
	}
	return ""
}

func (x *KafkaConfig) GetRootCa() string {
	if x != nil && x.RootCa != nil {
		return *x.RootCa
	}
	return ""
}

type ElasticsearchConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// decide if this is something actually used or single address is enough
	Addresses     []string              `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	AuthType      ElasticsearchAuthType `protobuf:"varint,2,opt,name=auth_type,json=authType,proto3,enum=peerdb_peers.ElasticsearchAuthType" json:"auth_type,omitempty"`
	Username      *string               `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string               `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	ApiKey        *string               `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3,oneof" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElasticsearchConfig) Reset() {
	*x = ElasticsearchConfig{}
	mi := &file_peers_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElasticsearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticsearchConfig) ProtoMessage() {}

func (x *ElasticsearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticsearchConfig.ProtoReflect.Descriptor instead.
func (*ElasticsearchConfig) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{17}
}

func (x *ElasticsearchConfig) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ElasticsearchConfig) GetAuthType() ElasticsearchAuthType {
	if x != nil {
		return x.AuthType
	}
	return ElasticsearchAuthType_UNKNOWN
}

func (x *ElasticsearchConfig) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ElasticsearchConfig) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *ElasticsearchConfig) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  DBType                 `protobuf:"varint,2,opt,name=type,proto3,enum=peerdb_peers.DBType" json:"type,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*Peer_SnowflakeConfig
	//	*Peer_BigqueryConfig
	//	*Peer_MongoConfig
	//	*Peer_PostgresConfig
	//	*Peer_S3Config
	//	*Peer_SqlserverConfig
	//	*Peer_EventhubGroupConfig
	//	*Peer_ClickhouseConfig
	//	*Peer_KafkaConfig
	//	*Peer_PubsubConfig
	//	*Peer_ElasticsearchConfig
	//	*Peer_MysqlConfig
	Config        isPeer_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_peers_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_peers_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_peers_proto_rawDescGZIP(), []int{18}
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetType() DBType {
	if x != nil {
		return x.Type
	}
	return DBType_BIGQUERY
}

func (x *Peer) GetConfig() isPeer_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Peer) GetSnowflakeConfig() *SnowflakeConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_SnowflakeConfig); ok {
			return x.SnowflakeConfig
		}
	}
	return nil
}

func (x *Peer) GetBigqueryConfig() *BigqueryConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_BigqueryConfig); ok {
			return x.BigqueryConfig
		}
	}
	return nil
}

func (x *Peer) GetMongoConfig() *MongoConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_MongoConfig); ok {
			return x.MongoConfig
		}
	}
	return nil
}

func (x *Peer) GetPostgresConfig() *PostgresConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_PostgresConfig); ok {
			return x.PostgresConfig
		}
	}
	return nil
}

func (x *Peer) GetS3Config() *S3Config {
	if x != nil {
		if x, ok := x.Config.(*Peer_S3Config); ok {
			return x.S3Config
		}
	}
	return nil
}

func (x *Peer) GetSqlserverConfig() *SqlServerConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_SqlserverConfig); ok {
			return x.SqlserverConfig
		}
	}
	return nil
}

func (x *Peer) GetEventhubGroupConfig() *EventHubGroupConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_EventhubGroupConfig); ok {
			return x.EventhubGroupConfig
		}
	}
	return nil
}

func (x *Peer) GetClickhouseConfig() *ClickhouseConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_ClickhouseConfig); ok {
			return x.ClickhouseConfig
		}
	}
	return nil
}

func (x *Peer) GetKafkaConfig() *KafkaConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_KafkaConfig); ok {
			return x.KafkaConfig
		}
	}
	return nil
}

func (x *Peer) GetPubsubConfig() *PubSubConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_PubsubConfig); ok {
			return x.PubsubConfig
		}
	}
	return nil
}

func (x *Peer) GetElasticsearchConfig() *ElasticsearchConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_ElasticsearchConfig); ok {
			return x.ElasticsearchConfig
		}
	}
	return nil
}

func (x *Peer) GetMysqlConfig() *MySqlConfig {
	if x != nil {
		if x, ok := x.Config.(*Peer_MysqlConfig); ok {
			return x.MysqlConfig
		}
	}
	return nil
}

type isPeer_Config interface {
	isPeer_Config()
}

type Peer_SnowflakeConfig struct {
	SnowflakeConfig *SnowflakeConfig `protobuf:"bytes,3,opt,name=snowflake_config,json=snowflakeConfig,proto3,oneof"`
}

type Peer_BigqueryConfig struct {
	BigqueryConfig *BigqueryConfig `protobuf:"bytes,4,opt,name=bigquery_config,json=bigqueryConfig,proto3,oneof"`
}

type Peer_MongoConfig struct {
	MongoConfig *MongoConfig `protobuf:"bytes,5,opt,name=mongo_config,json=mongoConfig,proto3,oneof"`
}

type Peer_PostgresConfig struct {
	PostgresConfig *PostgresConfig `protobuf:"bytes,6,opt,name=postgres_config,json=postgresConfig,proto3,oneof"`
}

type Peer_S3Config struct {
	S3Config *S3Config `protobuf:"bytes,8,opt,name=s3_config,json=s3Config,proto3,oneof"`
}

type Peer_SqlserverConfig struct {
	SqlserverConfig *SqlServerConfig `protobuf:"bytes,9,opt,name=sqlserver_config,json=sqlserverConfig,proto3,oneof"`
}

type Peer_EventhubGroupConfig struct {
	EventhubGroupConfig *EventHubGroupConfig `protobuf:"bytes,10,opt,name=eventhub_group_config,json=eventhubGroupConfig,proto3,oneof"`
}

type Peer_ClickhouseConfig struct {
	ClickhouseConfig *ClickhouseConfig `protobuf:"bytes,11,opt,name=clickhouse_config,json=clickhouseConfig,proto3,oneof"`
}

type Peer_KafkaConfig struct {
	KafkaConfig *KafkaConfig `protobuf:"bytes,12,opt,name=kafka_config,json=kafkaConfig,proto3,oneof"`
}

type Peer_PubsubConfig struct {
	PubsubConfig *PubSubConfig `protobuf:"bytes,13,opt,name=pubsub_config,json=pubsubConfig,proto3,oneof"`
}

type Peer_ElasticsearchConfig struct {
	ElasticsearchConfig *ElasticsearchConfig `protobuf:"bytes,14,opt,name=elasticsearch_config,json=elasticsearchConfig,proto3,oneof"`
}

type Peer_MysqlConfig struct {
	MysqlConfig *MySqlConfig `protobuf:"bytes,15,opt,name=mysql_config,json=mysqlConfig,proto3,oneof"`
}

func (*Peer_SnowflakeConfig) isPeer_Config() {}

func (*Peer_BigqueryConfig) isPeer_Config() {}

func (*Peer_MongoConfig) isPeer_Config() {}

func (*Peer_PostgresConfig) isPeer_Config() {}

func (*Peer_S3Config) isPeer_Config() {}

func (*Peer_SqlserverConfig) isPeer_Config() {}

func (*Peer_EventhubGroupConfig) isPeer_Config() {}

func (*Peer_ClickhouseConfig) isPeer_Config() {}

func (*Peer_KafkaConfig) isPeer_Config() {}

func (*Peer_PubsubConfig) isPeer_Config() {}

func (*Peer_ElasticsearchConfig) isPeer_Config() {}

func (*Peer_MysqlConfig) isPeer_Config() {}

var file_peers_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         16551842,
		Name:          "peerdb_peers.peerdb_redacted",
		Tag:           "varint,16551842,opt,name=peerdb_redacted",
		Filename:      "peers.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool peerdb_redacted = 16551842;
	E_PeerdbRedacted = &file_peers_proto_extTypes[0]
)

var File_peers_proto protoreflect.FileDescriptor

const file_peers_proto_rawDesc = "" +
	"\n" +
	"\vpeers.proto\x12\fpeerdb_peers\x1a google/protobuf/descriptor.proto\"\xb4\x01\n" +
	"\tSSHConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12!\n" +
	"\bpassword\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01R\bpassword\x12&\n" +
	"\vprivate_key\x18\x05 \x01(\tB\x05\x90\xfa\x91?\x01R\n" +
	"privateKey\x12 \n" +
	"\bhost_key\x18\x06 \x01(\tB\x05\x90\xfa\x91?\x01R\ahostKey\"\x85\x03\n" +
	"\x0fSnowflakeConfig\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12&\n" +
	"\vprivate_key\x18\x03 \x01(\tB\x05\x90\xfa\x91?\x01R\n" +
	"privateKey\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x1c\n" +
	"\twarehouse\x18\x06 \x01(\tR\twarehouse\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12#\n" +
	"\rquery_timeout\x18\b \x01(\x04R\fqueryTimeout\x12%\n" +
	"\x0es3_integration\x18\t \x01(\tR\rs3Integration\x12&\n" +
	"\bpassword\x18\n" +
	" \x01(\tB\x05\x90\xfa\x91?\x01H\x00R\bpassword\x88\x01\x01\x12,\n" +
	"\x0fmetadata_schema\x18\v \x01(\tH\x01R\x0emetadataSchema\x88\x01\x01B\v\n" +
	"\t_passwordB\x12\n" +
	"\x10_metadata_schema\"\x8b\x03\n" +
	"\x11GcpServiceAccount\x12\x1b\n" +
	"\tauth_type\x18\x01 \x01(\tR\bauthType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12+\n" +
	"\x0eprivate_key_id\x18\x03 \x01(\tB\x05\x90\xfa\x91?\x01R\fprivateKeyId\x12&\n" +
	"\vprivate_key\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01R\n" +
	"privateKey\x12!\n" +
	"\fclient_email\x18\x05 \x01(\tR\vclientEmail\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x19\n" +
	"\bauth_uri\x18\a \x01(\tR\aauthUri\x12\x1b\n" +
	"\ttoken_uri\x18\b \x01(\tR\btokenUri\x12<\n" +
	"\x1bauth_provider_x509_cert_url\x18\t \x01(\tR\x17authProviderX509CertUrl\x12/\n" +
	"\x14client_x509_cert_url\x18\n" +
	" \x01(\tR\x11clientX509CertUrl\"\xa7\x03\n" +
	"\x0eBigqueryConfig\x12\x1b\n" +
	"\tauth_type\x18\x01 \x01(\tR\bauthType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12+\n" +
	"\x0eprivate_key_id\x18\x03 \x01(\tB\x05\x90\xfa\x91?\x01R\fprivateKeyId\x12&\n" +
	"\vprivate_key\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01R\n" +
	"privateKey\x12!\n" +
	"\fclient_email\x18\x05 \x01(\tR\vclientEmail\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x19\n" +
	"\bauth_uri\x18\a \x01(\tR\aauthUri\x12\x1b\n" +
	"\ttoken_uri\x18\b \x01(\tR\btokenUri\x12<\n" +
	"\x1bauth_provider_x509_cert_url\x18\t \x01(\tR\x17authProviderX509CertUrl\x12/\n" +
	"\x14client_x509_cert_url\x18\n" +
	" \x01(\tR\x11clientX509CertUrl\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\v \x01(\tR\tdatasetId\"X\n" +
	"\fPubSubConfig\x12H\n" +
	"\x0fservice_account\x18\x01 \x01(\v2\x1f.peerdb_peers.GcpServiceAccountR\x0eserviceAccount\"\xde\x02\n" +
	"\vMongoConfig\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\bpassword\x18\x03 \x01(\tB\x05\x90\xfa\x91?\x01R\bpassword\x12\x1f\n" +
	"\vdisable_tls\x18\x04 \x01(\bR\n" +
	"disableTls\x12\x19\n" +
	"\btls_host\x18\x05 \x01(\tR\atlsHost\x12#\n" +
	"\aroot_ca\x18\x06 \x01(\tB\x05\x90\xfa\x91?\x01H\x00R\x06rootCa\x88\x01\x01\x12E\n" +
	"\x0fread_preference\x18\a \x01(\x0e2\x1c.peerdb_peers.ReadPreferenceR\x0ereadPreference\x12;\n" +
	"\n" +
	"ssh_config\x18\b \x01(\v2\x17.peerdb_peers.SSHConfigH\x01R\tsshConfig\x88\x01\x01B\n" +
	"\n" +
	"\b_root_caB\r\n" +
	"\v_ssh_config\"~\n" +
	"\x1eAwsAuthStaticCredentialsConfig\x12)\n" +
	"\raccess_key_id\x18\x01 \x01(\tB\x05\x90\xfa\x91?\x01R\vaccessKeyId\x121\n" +
	"\x11secret_access_key\x18\x02 \x01(\tB\x05\x90\xfa\x91?\x01R\x0fsecretAccessKey\"\x85\x01\n" +
	"\x17AWSAuthAssumeRoleConfig\x12&\n" +
	"\x0fassume_role_arn\x18\x01 \x01(\tR\rassumeRoleArn\x12-\n" +
	"\x10chained_role_arn\x18\x02 \x01(\tH\x00R\x0echainedRoleArn\x88\x01\x01B\x13\n" +
	"\x11_chained_role_arn\"\x9d\x02\n" +
	"\x17AwsAuthenticationConfig\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12?\n" +
	"\tauth_type\x18\x02 \x01(\x0e2\".peerdb_peers.AwsIAMAuthConfigTypeR\bauthType\x12]\n" +
	"\x12static_credentials\x18\x03 \x01(\v2,.peerdb_peers.AwsAuthStaticCredentialsConfigH\x00R\x11staticCredentials\x12;\n" +
	"\x04role\x18\x04 \x01(\v2%.peerdb_peers.AWSAuthAssumeRoleConfigH\x00R\x04roleB\r\n" +
	"\vauth_config\"\x97\x04\n" +
	"\x0ePostgresConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12!\n" +
	"\bpassword\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01R\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\x12\x19\n" +
	"\btls_host\x18\x06 \x01(\tR\atlsHost\x12,\n" +
	"\x0fmetadata_schema\x18\a \x01(\tH\x00R\x0emetadataSchema\x88\x01\x01\x12;\n" +
	"\n" +
	"ssh_config\x18\b \x01(\v2\x17.peerdb_peers.SSHConfigH\x01R\tsshConfig\x88\x01\x01\x12#\n" +
	"\aroot_ca\x18\t \x01(\tB\x05\x90\xfa\x91?\x01H\x02R\x06rootCa\x88\x01\x01\x12\x1f\n" +
	"\vrequire_tls\x18\n" +
	" \x01(\bR\n" +
	"requireTls\x12;\n" +
	"\tauth_type\x18\v \x01(\x0e2\x1e.peerdb_peers.PostgresAuthTypeR\bauthType\x12E\n" +
	"\baws_auth\x18\f \x01(\v2%.peerdb_peers.AwsAuthenticationConfigH\x03R\aawsAuth\x88\x01\x01B\x12\n" +
	"\x10_metadata_schemaB\r\n" +
	"\v_ssh_configB\n" +
	"\n" +
	"\b_root_caB\v\n" +
	"\t_aws_auth\"\x85\x02\n" +
	"\x0eEventHubConfig\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12%\n" +
	"\x0eresource_group\x18\x02 \x01(\tR\rresourceGroup\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12.\n" +
	"\x0fsubscription_id\x18\x05 \x01(\tB\x05\x90\xfa\x91?\x01R\x0esubscriptionId\x12'\n" +
	"\x0fpartition_count\x18\x06 \x01(\rR\x0epartitionCount\x129\n" +
	"\x19message_retention_in_days\x18\a \x01(\rR\x16messageRetentionInDays\"\xe8\x01\n" +
	"\x13EventHubGroupConfig\x12N\n" +
	"\teventhubs\x18\x01 \x03(\v20.peerdb_peers.EventHubGroupConfig.EventhubsEntryR\teventhubs\x12%\n" +
	"\x0eunnest_columns\x18\x03 \x03(\tR\runnestColumns\x1aZ\n" +
	"\x0eEventhubsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.peerdb_peers.EventHubConfigR\x05value:\x028\x01\"\xaa\x03\n" +
	"\bS3Config\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12.\n" +
	"\raccess_key_id\x18\x02 \x01(\tB\x05\x90\xfa\x91?\x01H\x00R\vaccessKeyId\x88\x01\x01\x126\n" +
	"\x11secret_access_key\x18\x03 \x01(\tB\x05\x90\xfa\x91?\x01H\x01R\x0fsecretAccessKey\x88\x01\x01\x12\x1e\n" +
	"\brole_arn\x18\x04 \x01(\tH\x02R\aroleArn\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x03R\x06region\x88\x01\x01\x12\x1f\n" +
	"\bendpoint\x18\x06 \x01(\tH\x04R\bendpoint\x88\x01\x01\x12#\n" +
	"\aroot_ca\x18\a \x01(\tB\x05\x90\xfa\x91?\x01H\x05R\x06rootCa\x88\x01\x01\x12\x19\n" +
	"\btls_host\x18\b \x01(\tR\atlsHost\x12-\n" +
	"\x05codec\x18\t \x01(\x0e2\x17.peerdb_peers.AvroCodecR\x05codecB\x10\n" +
	"\x0e_access_key_idB\x14\n" +
	"\x12_secret_access_keyB\v\n" +
	"\t_role_arnB\t\n" +
	"\a_regionB\v\n" +
	"\t_endpointB\n" +
	"\n" +
	"\b_root_ca\"\xa0\x05\n" +
	"\x10ClickhouseConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12!\n" +
	"\bpassword\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01R\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\x12\x17\n" +
	"\as3_path\x18\x06 \x01(\tR\x06s3Path\x12)\n" +
	"\raccess_key_id\x18\a \x01(\tB\x05\x90\xfa\x91?\x01R\vaccessKeyId\x121\n" +
	"\x11secret_access_key\x18\b \x01(\tB\x05\x90\xfa\x91?\x01R\x0fsecretAccessKey\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12\x1f\n" +
	"\vdisable_tls\x18\n" +
	" \x01(\bR\n" +
	"disableTls\x12\x1f\n" +
	"\bendpoint\x18\v \x01(\tH\x00R\bendpoint\x88\x01\x01\x12,\n" +
	"\vcertificate\x18\f \x01(\tB\x05\x90\xfa\x91?\x01H\x01R\vcertificate\x88\x01\x01\x12+\n" +
	"\vprivate_key\x18\r \x01(\tB\x05\x90\xfa\x91?\x01H\x02R\n" +
	"privateKey\x88\x01\x01\x12#\n" +
	"\aroot_ca\x18\x0e \x01(\tB\x05\x90\xfa\x91?\x01H\x03R\x06rootCa\x88\x01\x01\x12\x19\n" +
	"\btls_host\x18\x0f \x01(\tR\atlsHost\x12+\n" +
	"\x02s3\x18\x10 \x01(\v2\x16.peerdb_peers.S3ConfigH\x04R\x02s3\x88\x01\x01\x12\x18\n" +
	"\acluster\x18\x11 \x01(\tR\acluster\x12\x1e\n" +
	"\n" +
	"replicated\x18\x12 \x01(\bR\n" +
	"replicatedB\v\n" +
	"\t_endpointB\x0e\n" +
	"\f_certificateB\x0e\n" +
	"\f_private_keyB\n" +
	"\n" +
	"\b_root_caB\x05\n" +
	"\x03_s3\"\x90\x01\n" +
	"\x0fSqlServerConfig\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12!\n" +
	"\bpassword\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01R\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\"\xce\x05\n" +
	"\vMySqlConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12!\n" +
	"\bpassword\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01R\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05setup\x18\x06 \x03(\tR\x05setup\x12 \n" +
	"\vcompression\x18\a \x01(\rR\vcompression\x12\x1f\n" +
	"\vdisable_tls\x18\b \x01(\bR\n" +
	"disableTls\x121\n" +
	"\x06flavor\x18\t \x01(\x0e2\x19.peerdb_peers.MySqlFlavorR\x06flavor\x12;\n" +
	"\n" +
	"ssh_config\x18\n" +
	" \x01(\v2\x17.peerdb_peers.SSHConfigH\x00R\tsshConfig\x88\x01\x01\x12\\\n" +
	"\x15replication_mechanism\x18\v \x01(\x0e2'.peerdb_peers.MySqlReplicationMechanismR\x14replicationMechanism\x12\x19\n" +
	"\btls_host\x18\r \x01(\tR\atlsHost\x12#\n" +
	"\aroot_ca\x18\x0e \x01(\tB\x05\x90\xfa\x91?\x01H\x01R\x06rootCa\x88\x01\x01\x128\n" +
	"\tauth_type\x18\x0f \x01(\x0e2\x1b.peerdb_peers.MySqlAuthTypeR\bauthType\x12E\n" +
	"\baws_auth\x18\x10 \x01(\v2%.peerdb_peers.AwsAuthenticationConfigH\x02R\aawsAuth\x88\x01\x01\x124\n" +
	"\x16skip_cert_verification\x18\x11 \x01(\bR\x14skipCertVerificationB\r\n" +
	"\v_ssh_configB\n" +
	"\n" +
	"\b_root_caB\v\n" +
	"\t_aws_auth\"\xe9\x02\n" +
	"\vKafkaConfig\x12\x18\n" +
	"\aservers\x18\x01 \x03(\tR\aservers\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\bpassword\x18\x03 \x01(\tB\x05\x90\xfa\x91?\x01R\bpassword\x12\x12\n" +
	"\x04sasl\x18\x04 \x01(\tR\x04sasl\x12\x1f\n" +
	"\vdisable_tls\x18\x05 \x01(\bR\n" +
	"disableTls\x12 \n" +
	"\vpartitioner\x18\x06 \x01(\tR\vpartitioner\x12,\n" +
	"\vcertificate\x18\a \x01(\tB\x05\x90\xfa\x91?\x01H\x00R\vcertificate\x88\x01\x01\x12+\n" +
	"\vprivate_key\x18\b \x01(\tB\x05\x90\xfa\x91?\x01H\x01R\n" +
	"privateKey\x88\x01\x01\x12#\n" +
	"\aroot_ca\x18\t \x01(\tB\x05\x90\xfa\x91?\x01H\x02R\x06rootCa\x88\x01\x01B\x0e\n" +
	"\f_certificateB\x0e\n" +
	"\f_private_keyB\n" +
	"\n" +
	"\b_root_ca\"\x89\x02\n" +
	"\x13ElasticsearchConfig\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12@\n" +
	"\tauth_type\x18\x02 \x01(\x0e2#.peerdb_peers.ElasticsearchAuthTypeR\bauthType\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12&\n" +
	"\bpassword\x18\x04 \x01(\tB\x05\x90\xfa\x91?\x01H\x01R\bpassword\x88\x01\x01\x12#\n" +
	"\aapi_key\x18\x05 \x01(\tB\x05\x90\xfa\x91?\x01H\x02R\x06apiKey\x88\x01\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\n" +
	"\n" +
	"\b_api_key\"\xb2\a\n" +
	"\x04Peer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.peerdb_peers.DBTypeR\x04type\x12J\n" +
	"\x10snowflake_config\x18\x03 \x01(\v2\x1d.peerdb_peers.SnowflakeConfigH\x00R\x0fsnowflakeConfig\x12G\n" +
	"\x0fbigquery_config\x18\x04 \x01(\v2\x1c.peerdb_peers.BigqueryConfigH\x00R\x0ebigqueryConfig\x12>\n" +
	"\fmongo_config\x18\x05 \x01(\v2\x19.peerdb_peers.MongoConfigH\x00R\vmongoConfig\x12G\n" +
	"\x0fpostgres_config\x18\x06 \x01(\v2\x1c.peerdb_peers.PostgresConfigH\x00R\x0epostgresConfig\x125\n" +
	"\ts3_config\x18\b \x01(\v2\x16.peerdb_peers.S3ConfigH\x00R\bs3Config\x12J\n" +
	"\x10sqlserver_config\x18\t \x01(\v2\x1d.peerdb_peers.SqlServerConfigH\x00R\x0fsqlserverConfig\x12W\n" +
	"\x15eventhub_group_config\x18\n" +
	" \x01(\v2!.peerdb_peers.EventHubGroupConfigH\x00R\x13eventhubGroupConfig\x12M\n" +
	"\x11clickhouse_config\x18\v \x01(\v2\x1e.peerdb_peers.ClickhouseConfigH\x00R\x10clickhouseConfig\x12>\n" +
	"\fkafka_config\x18\f \x01(\v2\x19.peerdb_peers.KafkaConfigH\x00R\vkafkaConfig\x12A\n" +
	"\rpubsub_config\x18\r \x01(\v2\x1a.peerdb_peers.PubSubConfigH\x00R\fpubsubConfig\x12V\n" +
	"\x14elasticsearch_config\x18\x0e \x01(\v2!.peerdb_peers.ElasticsearchConfigH\x00R\x13elasticsearchConfig\x12>\n" +
	"\fmysql_config\x18\x0f \x01(\v2\x19.peerdb_peers.MySqlConfigH\x00R\vmysqlConfigB\b\n" +
	"\x06config*\x81\x01\n" +
	"\x0eReadPreference\x12\x16\n" +
	"\x12PREFERENCE_UNKNOWN\x10\x00\x12\v\n" +
	"\aPRIMARY\x10\x01\x12\x15\n" +
	"\x11PRIMARY_PREFERRED\x10\x02\x12\r\n" +
	"\tSECONDARY\x10\x03\x12\x17\n" +
	"\x13SECONDARY_PREFERRED\x10\x04\x12\v\n" +
	"\aNEAREST\x10\x05*i\n" +
	"\x14AwsIAMAuthConfigType\x12\x16\n" +
	"\x12IAM_AUTH_AUTOMATIC\x10\x00\x12\x1f\n" +
	"\x1bIAM_AUTH_STATIC_CREDENTIALS\x10\x01\x12\x18\n" +
	"\x14IAM_AUTH_ASSUME_ROLE\x10\x02*@\n" +
	"\x10PostgresAuthType\x12\x15\n" +
	"\x11POSTGRES_PASSWORD\x10\x00\x12\x15\n" +
	"\x11POSTGRES_IAM_AUTH\x10\x01*=\n" +
	"\tAvroCodec\x12\b\n" +
	"\x04Null\x10\x00\x12\v\n" +
	"\aDeflate\x10\x01\x12\n" +
	"\n" +
	"\x06Snappy\x10\x02\x12\r\n" +
	"\tZStandard\x10\x03*B\n" +
	"\vMySqlFlavor\x12\x11\n" +
	"\rMYSQL_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vMYSQL_MYSQL\x10\x01\x12\x0f\n" +
	"\vMYSQL_MARIA\x10\x02*N\n" +
	"\x19MySqlReplicationMechanism\x12\x0e\n" +
	"\n" +
	"MYSQL_AUTO\x10\x00\x12\x0e\n" +
	"\n" +
	"MYSQL_GTID\x10\x01\x12\x11\n" +
	"\rMYSQL_FILEPOS\x10\x02*7\n" +
	"\rMySqlAuthType\x12\x12\n" +
	"\x0eMYSQL_PASSWORD\x10\x00\x12\x12\n" +
	"\x0eMYSQL_IAM_AUTH\x10\x01*E\n" +
	"\x15ElasticsearchAuthType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\t\n" +
	"\x05BASIC\x10\x02\x12\n" +
	"\n" +
	"\x06APIKEY\x10\x03*\xc6\x01\n" +
	"\x06DBType\x12\f\n" +
	"\bBIGQUERY\x10\x00\x12\r\n" +
	"\tSNOWFLAKE\x10\x01\x12\t\n" +
	"\x05MONGO\x10\x02\x12\f\n" +
	"\bPOSTGRES\x10\x03\x12\x06\n" +
	"\x02S3\x10\x05\x12\r\n" +
	"\tSQLSERVER\x10\x06\x12\t\n" +
	"\x05MYSQL\x10\a\x12\x0e\n" +
	"\n" +
	"CLICKHOUSE\x10\b\x12\t\n" +
	"\x05KAFKA\x10\t\x12\n" +
	"\n" +
	"\x06PUBSUB\x10\n" +
	"\x12\r\n" +
	"\tEVENTHUBS\x10\v\x12\x11\n" +
	"\rELASTICSEARCH\x10\f\x12\x1b\n" +
	"\x0eDBTYPE_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\x96\x01\n" +
	"\x0fDatabaseVariant\x12\x13\n" +
	"\x0fVARIANT_UNKNOWN\x10\x00\x12\v\n" +
	"\aAWS_RDS\x10\x02\x12\x0e\n" +
	"\n" +
	"AWS_AURORA\x10\x03\x12\x14\n" +
	"\x10GOOGLE_CLOUD_SQL\x10\x04\x12\x12\n" +
	"\x0eAZURE_DATABASE\x10\x05\x12\b\n" +
	"\x04NEON\x10\x06\x12\x0f\n" +
	"\vPLANETSCALE\x10\a\x12\f\n" +
	"\bSUPABASE\x10\b:L\n" +
	"\x0fpeerdb_redacted\x12\x1d.google.protobuf.FieldOptions\x18\xa2\x9f\xf2\a \x01(\bR\x0epeerdbRedacted\x88\x01\x01B|\n" +
	"\x10com.peerdb_peersB\n" +
	"PeersProtoP\x01Z\x10generated/protos\xa2\x02\x03PXX\xaa\x02\vPeerdbPeers\xca\x02\vPeerdbPeers\xe2\x02\x17PeerdbPeers\\GPBMetadata\xea\x02\vPeerdbPeersb\x06proto3"

var (
	file_peers_proto_rawDescOnce sync.Once
	file_peers_proto_rawDescData []byte
)

func file_peers_proto_rawDescGZIP() []byte {
	file_peers_proto_rawDescOnce.Do(func() {
		file_peers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peers_proto_rawDesc), len(file_peers_proto_rawDesc)))
	})
	return file_peers_proto_rawDescData
}

var file_peers_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_peers_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_peers_proto_goTypes = []any{
	(ReadPreference)(0),                    // 0: peerdb_peers.ReadPreference
	(AwsIAMAuthConfigType)(0),              // 1: peerdb_peers.AwsIAMAuthConfigType
	(PostgresAuthType)(0),                  // 2: peerdb_peers.PostgresAuthType
	(AvroCodec)(0),                         // 3: peerdb_peers.AvroCodec
	(MySqlFlavor)(0),                       // 4: peerdb_peers.MySqlFlavor
	(MySqlReplicationMechanism)(0),         // 5: peerdb_peers.MySqlReplicationMechanism
	(MySqlAuthType)(0),                     // 6: peerdb_peers.MySqlAuthType
	(ElasticsearchAuthType)(0),             // 7: peerdb_peers.ElasticsearchAuthType
	(DBType)(0),                            // 8: peerdb_peers.DBType
	(DatabaseVariant)(0),                   // 9: peerdb_peers.DatabaseVariant
	(*SSHConfig)(nil),                      // 10: peerdb_peers.SSHConfig
	(*SnowflakeConfig)(nil),                // 11: peerdb_peers.SnowflakeConfig
	(*GcpServiceAccount)(nil),              // 12: peerdb_peers.GcpServiceAccount
	(*BigqueryConfig)(nil),                 // 13: peerdb_peers.BigqueryConfig
	(*PubSubConfig)(nil),                   // 14: peerdb_peers.PubSubConfig
	(*MongoConfig)(nil),                    // 15: peerdb_peers.MongoConfig
	(*AwsAuthStaticCredentialsConfig)(nil), // 16: peerdb_peers.AwsAuthStaticCredentialsConfig
	(*AWSAuthAssumeRoleConfig)(nil),        // 17: peerdb_peers.AWSAuthAssumeRoleConfig
	(*AwsAuthenticationConfig)(nil),        // 18: peerdb_peers.AwsAuthenticationConfig
	(*PostgresConfig)(nil),                 // 19: peerdb_peers.PostgresConfig
	(*EventHubConfig)(nil),                 // 20: peerdb_peers.EventHubConfig
	(*EventHubGroupConfig)(nil),            // 21: peerdb_peers.EventHubGroupConfig
	(*S3Config)(nil),                       // 22: peerdb_peers.S3Config
	(*ClickhouseConfig)(nil),               // 23: peerdb_peers.ClickhouseConfig
	(*SqlServerConfig)(nil),                // 24: peerdb_peers.SqlServerConfig
	(*MySqlConfig)(nil),                    // 25: peerdb_peers.MySqlConfig
	(*KafkaConfig)(nil),                    // 26: peerdb_peers.KafkaConfig
	(*ElasticsearchConfig)(nil),            // 27: peerdb_peers.ElasticsearchConfig
	(*Peer)(nil),                           // 28: peerdb_peers.Peer
	nil,                                    // 29: peerdb_peers.EventHubGroupConfig.EventhubsEntry
	(*descriptorpb.FieldOptions)(nil),      // 30: google.protobuf.FieldOptions
}
var file_peers_proto_depIdxs = []int32{
	12, // 0: peerdb_peers.PubSubConfig.service_account:type_name -> peerdb_peers.GcpServiceAccount
	0,  // 1: peerdb_peers.MongoConfig.read_preference:type_name -> peerdb_peers.ReadPreference
	10, // 2: peerdb_peers.MongoConfig.ssh_config:type_name -> peerdb_peers.SSHConfig
	1,  // 3: peerdb_peers.AwsAuthenticationConfig.auth_type:type_name -> peerdb_peers.AwsIAMAuthConfigType
	16, // 4: peerdb_peers.AwsAuthenticationConfig.static_credentials:type_name -> peerdb_peers.AwsAuthStaticCredentialsConfig
	17, // 5: peerdb_peers.AwsAuthenticationConfig.role:type_name -> peerdb_peers.AWSAuthAssumeRoleConfig
	10, // 6: peerdb_peers.PostgresConfig.ssh_config:type_name -> peerdb_peers.SSHConfig
	2,  // 7: peerdb_peers.PostgresConfig.auth_type:type_name -> peerdb_peers.PostgresAuthType
	18, // 8: peerdb_peers.PostgresConfig.aws_auth:type_name -> peerdb_peers.AwsAuthenticationConfig
	29, // 9: peerdb_peers.EventHubGroupConfig.eventhubs:type_name -> peerdb_peers.EventHubGroupConfig.EventhubsEntry
	3,  // 10: peerdb_peers.S3Config.codec:type_name -> peerdb_peers.AvroCodec
	22, // 11: peerdb_peers.ClickhouseConfig.s3:type_name -> peerdb_peers.S3Config
	4,  // 12: peerdb_peers.MySqlConfig.flavor:type_name -> peerdb_peers.MySqlFlavor
	10, // 13: peerdb_peers.MySqlConfig.ssh_config:type_name -> peerdb_peers.SSHConfig
	5,  // 14: peerdb_peers.MySqlConfig.replication_mechanism:type_name -> peerdb_peers.MySqlReplicationMechanism
	6,  // 15: peerdb_peers.MySqlConfig.auth_type:type_name -> peerdb_peers.MySqlAuthType
	18, // 16: peerdb_peers.MySqlConfig.aws_auth:type_name -> peerdb_peers.AwsAuthenticationConfig
	7,  // 17: peerdb_peers.ElasticsearchConfig.auth_type:type_name -> peerdb_peers.ElasticsearchAuthType
	8,  // 18: peerdb_peers.Peer.type:type_name -> peerdb_peers.DBType
	11, // 19: peerdb_peers.Peer.snowflake_config:type_name -> peerdb_peers.SnowflakeConfig
	13, // 20: peerdb_peers.Peer.bigquery_config:type_name -> peerdb_peers.BigqueryConfig
	15, // 21: peerdb_peers.Peer.mongo_config:type_name -> peerdb_peers.MongoConfig
	19, // 22: peerdb_peers.Peer.postgres_config:type_name -> peerdb_peers.PostgresConfig
	22, // 23: peerdb_peers.Peer.s3_config:type_name -> peerdb_peers.S3Config
	24, // 24: peerdb_peers.Peer.sqlserver_config:type_name -> peerdb_peers.SqlServerConfig
	21, // 25: peerdb_peers.Peer.eventhub_group_config:type_name -> peerdb_peers.EventHubGroupConfig
	23, // 26: peerdb_peers.Peer.clickhouse_config:type_name -> peerdb_peers.ClickhouseConfig
	26, // 27: peerdb_peers.Peer.kafka_config:type_name -> peerdb_peers.KafkaConfig
	14, // 28: peerdb_peers.Peer.pubsub_config:type_name -> peerdb_peers.PubSubConfig
	27, // 29: peerdb_peers.Peer.elasticsearch_config:type_name -> peerdb_peers.ElasticsearchConfig
	25, // 30: peerdb_peers.Peer.mysql_config:type_name -> peerdb_peers.MySqlConfig
	20, // 31: peerdb_peers.EventHubGroupConfig.EventhubsEntry.value:type_name -> peerdb_peers.EventHubConfig
	30, // 32: peerdb_peers.peerdb_redacted:extendee -> google.protobuf.FieldOptions
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	32, // [32:33] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_peers_proto_init() }
func file_peers_proto_init() {
	if File_peers_proto != nil {
		return
	}
	file_peers_proto_msgTypes[1].OneofWrappers = []any{}
	file_peers_proto_msgTypes[5].OneofWrappers = []any{}
	file_peers_proto_msgTypes[7].OneofWrappers = []any{}
	file_peers_proto_msgTypes[8].OneofWrappers = []any{
		(*AwsAuthenticationConfig_StaticCredentials)(nil),
		(*AwsAuthenticationConfig_Role)(nil),
	}
	file_peers_proto_msgTypes[9].OneofWrappers = []any{}
	file_peers_proto_msgTypes[12].OneofWrappers = []any{}
	file_peers_proto_msgTypes[13].OneofWrappers = []any{}
	file_peers_proto_msgTypes[15].OneofWrappers = []any{}
	file_peers_proto_msgTypes[16].OneofWrappers = []any{}
	file_peers_proto_msgTypes[17].OneofWrappers = []any{}
	file_peers_proto_msgTypes[18].OneofWrappers = []any{
		(*Peer_SnowflakeConfig)(nil),
		(*Peer_BigqueryConfig)(nil),
		(*Peer_MongoConfig)(nil),
		(*Peer_PostgresConfig)(nil),
		(*Peer_S3Config)(nil),
		(*Peer_SqlserverConfig)(nil),
		(*Peer_EventhubGroupConfig)(nil),
		(*Peer_ClickhouseConfig)(nil),
		(*Peer_KafkaConfig)(nil),
		(*Peer_PubsubConfig)(nil),
		(*Peer_ElasticsearchConfig)(nil),
		(*Peer_MysqlConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peers_proto_rawDesc), len(file_peers_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   20,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_peers_proto_goTypes,
		DependencyIndexes: file_peers_proto_depIdxs,
		EnumInfos:         file_peers_proto_enumTypes,
		MessageInfos:      file_peers_proto_msgTypes,
		ExtensionInfos:    file_peers_proto_extTypes,
	}.Build()
	File_peers_proto = out.File
	file_peers_proto_goTypes = nil
	file_peers_proto_depIdxs = nil
}
