name: build docker

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_CHECKOUT }}

      - name: Build PeerDB OSS Image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: stacks/Dockerfile
          push: false
          tags: peerdb-server:latest
