on:
  workflow_call:
    inputs:
      tags:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build PeerDB OSS Image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: stacks/Dockerfile
          push: true
          tags: 'peerdb-server:${{ inputs.tag }}'